LBNL-UCB-STI/beam

src/main/java/beam/agentsim/events/BeamEventsHandling.java
src/main/scala/beam/agentsim/config/BeamConfig.scala

[#2] beam-2 consolidate / reorganize config data

---

build.gradle
src/main/java/beam/utils/Collections.java

Feedback incorporated, from @dserdyuk.

Apache Collections 4 to refactor custom Utils

---

src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala
src/main/scala/beam/playground/dserdyuk/App.scala

for #18 Vehicles Part 2 - Managers and inputs minor changes

---

src/main/scala/beam/router/BeamRouter.scala
src/main/scala/beam/router/RoutingModel.scala
src/main/scala/beam/router/RoutingWorker.scala
src/main/scala/beam/router/opentripplanner/OtpRoutingWorker.scala
src/main/scala/beam/router/r5/R5Router.scala
src/main/scala/beam/router/r5/R5RoutingWorker.scala
src/main/scala/beam/sim/BeamSim.scala

- managing route requests before initialize by stashing and behaviors.
- r5 router issue resolution (Typo and unnecessary read of network file)
- Implemented akka router for r5 and otp with 5 workers
TODO: Worker count need to configure from config.

Router actor improvement

---

.travis.yml
README.md
build.gradle

- Travis build setup
- Dependency cache configure

Travis CI setup

---

src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala
src/main/scala/beam/agentsim/agents/vehicles/BeamVehicleAgent.scala
src/main/scala/beam/agentsim/agents/vehicles/household/HouseholdActor.scala
src/main/scala/beam/playground/dserdyuk/App.scala
src/main/scala/beam/sim/BeamServices.scala
src/main/scala/beam/sim/BeamSim.scala
test/input/beam/sf-bay/beam.conf
test/input/beam/sf-bay/population.xml

* associate the appropriate PersonAgent ActorRefs
* reinit beamvehicles and household actors on each iteration

for #18 Vehicles Part 2 - Managers and inputs

---

src/main/scala/beam/agentsim/agents/BeamAgent.scala
src/main/scala/beam/agentsim/agents/PersonAgent.scala
src/main/scala/beam/agentsim/agents/RideHailingManager.scala
src/main/scala/beam/agentsim/agents/modalBehaviors/DrivesVehicle.scala
src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala
src/main/scala/beam/agentsim/agents/vehicles/PassengerSchedule.scala
src/test/scala/beam/agentsim/agents/vehicles/PassengerScheduleTest.scala

* set carrier
* send NotifyLegEnd/NotifLegStart directly to PersonAgent

for #48 Complete Traveling Implementation

---

src/main/resources/beam-template.conf
src/main/scala/beam/agentsim/agents/BeamAgent.scala
src/main/scala/beam/agentsim/agents/PersonAgent.scala
src/main/scala/beam/agentsim/agents/TransitDriverAgent.scala
src/main/scala/beam/agentsim/agents/TriggerShortcuts.scala
src/main/scala/beam/agentsim/agents/modalBehaviors/ChoosesMode.scala
src/main/scala/beam/agentsim/agents/modalBehaviors/DrivesVehicle.scala
src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala
src/main/scala/beam/agentsim/agents/vehicles/PassengerSchedule.scala
src/main/scala/beam/agentsim/agents/vehicles/TransitVehicle.scala
src/main/scala/beam/agentsim/events/PathTraversalEvent.scala
src/main/scala/beam/agentsim/events/resources/vehicle/VehicleAccessRequest.scala
src/main/scala/beam/agentsim/scheduler/BeamAgentScheduler.scala
src/main/scala/beam/router/BeamRouter.scala
src/main/scala/beam/router/RoutingWorker.scala
src/main/scala/beam/router/r5/R5RoutingWorker.scala
src/main/scala/beam/sim/BeamServices.scala
src/main/scala/beam/sim/BeamSim.scala
src/main/scala/beam/sim/RunBeam.scala
src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala

* initial version
* create partial transit by sending message to the Router
* beamAgent state transition fixes

for  #54 Transit Vehicle Synthesis

---

src/main/scala/beam/agentsim/agents/modalBehaviors/DrivesVehicle.scala
src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala
src/main/scala/beam/agentsim/agents/vehicles/PassengerSchedule.scala
src/main/scala/beam/agentsim/agents/vehicles/household/HouseholdActor.scala
src/main/scala/beam/agentsim/events/package.scala
src/main/scala/beam/router/RoutingModel.scala
src/main/scala/beam/router/RoutingWorker.scala
src/main/scala/beam/router/TrajectoryResolver.scala
src/main/scala/beam/router/r5/BeamPathBuilder.scala
src/main/scala/beam/router/r5/R5RoutingWorker.scala
src/main/scala/beam/sim/BeamServices.scala
src/main/scala/beam/sim/BeamSim.scala
src/main/scala/beam/utils/ProfilingUtils.scala

get rid of full trajectory computation in beamvehicle. Let's keep only last coordinate

---

src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala
test/input/beamville/r5/bus.gtfs.zip
test/input/beamville/r5/bus.zip
test/input/beamville/r5/bus/stop_times.txt
test/input/beamville/r5/bus/stops.txt
test/input/beamville/r5/network.dat
test/input/beamville/r5/train.gtfs.zip
test/input/beamville/r5/train.zip
test/input/beamville/r5/train/stop_times.txt

GTFS updated, bus stops at every intersection.

#60 Updates gtfs files for beamville

---

docs/developers.rst

- Added extra step to replace text pointers by actual files
- Fixed typo in `git` command

Documentation: Improve GIT-LFS Configuration

---

src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceLCCM.scala
src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceMultinomialLogit.scala
src/main/scala/beam/agentsim/agents/rideHail/HistoricWaitingTimes.scala
src/main/scala/beam/agentsim/agents/rideHail/RideHailingManager.scala
src/main/scala/beam/agentsim/agents/rideHail/allocationManagers/RideHailAllocationManagerBufferedImplTemplate.scala
src/main/scala/beam/agentsim/agents/rideHail/allocationManagers/StanfordRideHailAllocationManagerV1.scala
src/main/scala/beam/router/RoutingModel.scala
src/test/scala/beam/router/TimeDependentRoutingSpec.scala

* General
- Removed unused fields: log, RIDE_HAIL_MANAGER
- Removed commented code: just noise. people never read it. Changes should be introduced with tests
- Removed empty file
- Unnecessary mutable: rideHailResourceAllocationManager, passengerScheduleOverrideRequests
- Removed warnings: return; shadowing names, type annotation for public and others
- Removed variables with values never queried: `todo_allocationsDuringReservation`
- extract variables
* Reliability
- Encapsulation issues
public var <-- very dangerous
public val <-- not big problem
- Removed possibility of `NoSuchElementException`: `resources.get(agentsim.vehicleId2BeamVehicleId(vehId)).get`
* performance
- test iterator emptyness checking size -> isEmpty(): 
some data structures need O(N) to identify the size and O(1) to …

Refactoring RideHailingManager - iteration 1

---

src/main/java/beam/agentsim/events/handling/BeamEventsLogger.java
src/main/java/beam/agentsim/events/handling/BeamEventsWriterCSV.java
src/main/java/beam/agentsim/events/handling/BeamEventsWriterXML.java
src/main/java/beam/analysis/plots/DeadHeadingStats.java
src/main/java/beam/analysis/plots/FuelUsageStats.java
src/main/java/beam/analysis/plots/RideHailingWaitingStats.java
src/main/java/beam/analysis/via/EventWriterXML_viaCompatible.java
src/main/java/beam/analysis/via/ExpectedMaxUtilityHeatMap.java
src/main/java/beam/physsim/jdeqsim/AgentSimPhysSimInterfaceDebugger.java
src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java
src/main/java/beam/utils/debug/DetectDriveTransitRemainingEnRoute.java
src/main/java/beam/utils/debug/FilterAllEventsOfAgent.java
src/main/scala/beam/replanning/GrabExperiencedPlan.scala
src/test/scala/beam/integration/ReadEventsBeam.scala

Cherry-picked extremely useful commit  https://github.com/LBNL-UCB-STI/beam/commit/b2f031c44c29a967b92122feb9a047dc054dd9bf which reduce GC Pressure a lot (there were a lot of unnecessary allocations)

Optimization: Extract Event.getAttributes for memory optimization

---

src/main/java/beam/agentsim/agents/choice/logit/LatentClassChoiceModel.scala
src/main/scala/beam/agentsim/agents/Population.scala
src/main/scala/beam/agentsim/agents/choice/logit/MultinomialLogit.scala
src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceDriveIfAvailable.scala
src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceLCCM.scala
src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceMultinomialLogit.scala
src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceRideHailIfAvailable.scala
src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceTransitIfAvailable.scala
src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceUniformRandom.scala
src/main/scala/beam/agentsim/agents/household/HouseholdActor.scala
src/main/scala/beam/agentsim/agents/memberships/HouseholdMembershipAllocator.scala
src/main/scala/beam/agentsim/agents/modalBehaviors/ChoosesMode.scala
src/main/scala/beam/agentsim/agents/rideHail/RideHailModifyPassengerScheduleManager.scala
src/main/scala/beam/agentsim/agents/rideHail/RideHailSurgePricingManager.scala
src/main/scala/beam/agentsim/agents/rideHail/RideHailingManager.scala
src/main/scala/beam/agentsim/agents/rideHail/allocationManagers/DefaultRideHailResourceAllocationManager.scala
src/main/scala/beam/agentsim/agents/rideHail/allocationManagers/RepositioningWithLowWaitingTimes.scala
src/main/scala/beam/agentsim/agents/rideHail/allocationManagers/RideHailAllocationManagerBufferedImplTemplate.scala
src/main/scala/beam/agentsim/agents/rideHail/allocationManagers/RideHailResourceAllocationManager.scala
src/main/scala/beam/agentsim/agents/rideHail/allocationManagers/StanfordRideHailAllocationManagerV1.scala
src/main/scala/beam/router/BeamRouter.scala
src/main/scala/beam/router/RoutingModel.scala
src/main/scala/beam/router/r5/R5RoutingWorker.scala
src/main/scala/beam/sim/BeamMobsim.scala
src/main/scala/beam/sim/BeamPrepareForSim.scala

- Immutable collection with var are replaced by appropriate mutable
- Added type for public methods and fields

Immutable collection with var are replaced by appropriate mutable

---

src/main/java/beam/agentsim/events/ReplanningEvent.java
src/main/java/beam/agentsim/events/handling/BeamEventsLogger.java
src/main/java/beam/analysis/plots/GraphsStatsAgentSimEventsListener.java
src/main/java/beam/analysis/plots/RealizedModeStats.java
src/main/java/beam/analysis/plots/RideHailingWaitingStats.java
src/main/scala/beam/agentsim/agents/PersonAgent.scala
src/main/scala/beam/agentsim/agents/rideHail/RideHailingManager.scala
src/main/scala/beam/agentsim/agents/rideHail/allocationManagers/RepositioningLowWaitingTimes.scala
src/main/scala/beam/sim/BeamMobsim.scala
src/main/scala/beam/utils/SpatialPlot.scala
test/input/beamville/beam.conf

changes are made for generating spatialplots in subfolder "rideHailDugging of each iteration

created subfolder for spatialplot

---

src/main/java/beam/analysis/plots/RealizedModeStats.java

Add null pointer check if occurrence of mode is empty

Resolve Null pointer if occurrence of mode is empty

---

src/main/java/beam/analysis/plots/RealizedModeStats.java

added support for if we got modechoice and replanning events in continuation

change code for support of continues modechoice and replanning event

---

src/test/scala/beam/router/WarmStartRoutingSpec.scala
test/input/beamville/test-data/beamville.linkstats.csv.gz

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/329)

test created against fixes #328

---

src/main/java/beam/analysis/plots/GraphsStatsAgentSimEventsListener.java
src/main/java/beam/analysis/plots/VehicleParkingStats.java

parking_occupancy.png graph and csv file for same is created
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/327)

created vehicleParkingStats for parking occupancy

---

src/main/scala/beam/agentsim/agents/ridehail/RideHailUtils.scala

- `getDistance` replaced by accumulator: the original approach was traversing the whole `Vector` for every iteration. The impact was quadratic time. Was replaced by an accumulator with similar behaviour
- `Vector` replaced by `ListBuffer`: a new instance object was created for every iteration. Since the variable was used locally (inside the method) there is no need of being immutable.
- Removed redundant variables
- Removed duplicate calculation
- Find a way to do the same calculation using functional approach. The breakable creates an `Exception` including the stacktrace and intercept it. It add a huge constant time because.
- Create a test case for this method …

Optimization: reduced quadratic complexity (space and time) to linear

---

src/main/java/beam/analysis/plots/AverageVehicleParkingStats.java
src/main/java/beam/analysis/plots/VehicleParkingStats.java

occupancy is calculated only on vehicle enter hour.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/353)

stats are updated for average occupancy

---

src/main/java/beam/utils/scripts/CreateRideHailDemandTAZSpatialData.java

ridehHailDemand is calculated for min distance taznad vehicle pichup coordinates
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/362)

calculate minimum distance between taz coordinates and vehicle pickup coordinates

---

src/main/java/beam/analysis/plots/GraphsStatsAgentSimEventsListener.java
src/main/java/beam/analysis/plots/ModeChosenStats.java
src/main/java/beam/analysis/plots/RealizedModeStats.java
src/main/scala/beam/sim/BeamSim.scala

fixed root graph for mode choice and realised mode choice
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/391)

created root graphs for mode choice and realized mode choice

---

build.gradle
gradle.properties
src/main/scala/beam/agentsim/agents/PersonAgent.scala
src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailRequest.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailRequestType.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailResponse.scala
src/main/scala/beam/agentsim/agents/ridehail/allocation/RandomRepositioning.scala
src/main/scala/beam/agentsim/agents/ridehail/allocation/RepositioningLowWaitingTimes.scala
src/main/scala/beam/agentsim/agents/ridehail/allocation/RideHailResourceAllocationManager.scala
src/main/scala/beam/agentsim/agents/ridehail/allocation/StanfordRideHailAllocationManagerV1.scala
src/main/scala/beam/agentsim/infrastructure/ZonalParkingManager.scala
src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala
src/test/scala/beam/agentsim/agents/ridehail/RideHailManagerTest.scala
src/test/scala/beam/agentsim/agents/ridehail/RideHailNetworkAPITest.scala
src/test/scala/beam/integration/ridehail/RideHailReplaceAllocationSpec.scala
src/test/scala/beam/integration/ridehail/allocation/ImmediateDispatchWithOverwrite.scala

- Added `override` when it fits
- Extracted `RideHailRequest`, `RideHailResponse` and `RideHailRequestType` to its own file
- Moved the commented method `StanfordRideHailAllocationManagerV1.apiExamples` to test classes
- Fixed typos: `numVechilesToReposition`, `unknonwn`
- Replaced negative test condition with Positive test condition
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/394)

Refactor ridehail package - iteration 01

---

build.gradle
src/main/scala/beam/agentsim/agents/PersonAgent.scala
src/main/scala/beam/agentsim/agents/Population.scala
src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceLCCM.scala
src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceMultinomialLogit.scala
src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala
src/main/scala/beam/agentsim/agents/modalbehaviors/ModeChoiceCalculator.scala
src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailRequest.scala
src/main/scala/beam/agentsim/agents/ridehail/allocation/RideHailResourceAllocationManager.scala
src/main/scala/beam/agentsim/agents/ridehail/allocation/StanfordRideHailAllocationManagerV1.scala
src/main/scala/beam/agentsim/infrastructure/ParkingManager.scala
src/main/scala/beam/calibration/Bounded.scala
src/main/scala/beam/calibration/ExperimentRunner.scala
src/main/scala/beam/calibration/api/ObjectiveFunction.scala
src/main/scala/beam/calibration/impl/example/ModeChoiceObjectiveFunction.scala
src/main/scala/beam/sim/BeamServices.scala
src/main/scala/beam/sim/BeamSim.scala
src/main/scala/beam/sim/config/BeamConfig.scala
src/main/scala/beam/utils/BeamVehicleUtils.scala
src/main/scala/beam/utils/CsvUtils.scala
src/main/scala/beam/utils/FileUtils.scala
src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala
src/test/scala/beam/agentsim/agents/choice/logit/MultinomialLogitSpec.scala
src/test/scala/beam/integration/ParkingSpec.scala
src/test/scala/beam/integration/ridehail/RideHailReplaceAllocationSpec.scala
src/test/scala/beam/integration/ridehail/allocation/ImmediateDispatchWithOverwrite.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/402)

Project: Update scalafmt 4ci

---

src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/386)

RideHailManager: getIdleVehiclesWithinRadius optimization

---

build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/420)

Project: Set scala version to 2.12.6

---

src/test/java/beam/analysis/plot/graph/ModeChosenGraphTest.java
src/test/java/beam/analysis/plot/graph/RealizedModeGraphTest.java

test cases removed from ignore status
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/423)

test cases passed after removal of classDefNotFound Exception

---

.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/445)

Project: Update scala version to 2.12.6 for travis

---

beam-gui/src/main/java/beam/gui/AsyncFileInputProgressDialog.java
beam-gui/src/main/java/beam/gui/ExeRunner.java
src/main/java/beam/playground/jdeqsim/akkaeventsampling/ActorBootStrap.java
src/main/java/beam/utils/gtfs/SFBayPT2MATSim.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/455)

Signal interrupted thread

---

src/main/scala/beam/agentsim/agents/PersonAgent.scala
src/main/scala/beam/agentsim/agents/Population.scala
src/main/scala/beam/agentsim/agents/choice/mode/BridgeTollDefaults.scala
src/main/scala/beam/agentsim/infrastructure/ZonalParkingManager.scala
src/main/scala/beam/router/r5/R5RoutingWorker.scala
src/test/scala/beam/integration/ParkingSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/463)

Project: Applied scalafmt on master

---

test/input/beamville/beam-calibration.conf
test/input/beamville/beam.conf
test/input/equil-square/equil-1k.conf

When I went to pull into cluster I realized that I had missed removing some of the common conf
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/450)

Removed common duplicates

---

src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/473)

BugFix: Clean-up stats after notifyIterationEnds finished

---

test/input/beamville/beam.conf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/475)

Add missing metrics.conf

---

src/main/scala/beam/agentsim/agents/PersonAgent.scala
src/test/scala/beam/agentsim/agents/ridehail/graph/FuelUsageStatsGraphSpec.scala
src/test/scala/beam/agentsim/agents/ridehail/graph/GraphRunHelper.scala
src/test/scala/beam/agentsim/agents/ridehail/graph/ModeChosenStatsGraphSpec.scala
src/test/scala/beam/agentsim/agents/ridehail/graph/PersonTravelTimeStatsGraphSpec.scala
src/test/scala/beam/agentsim/agents/ridehail/graph/RealizedModeStatsGraphSpec.scala
src/test/scala/beam/agentsim/agents/ridehail/graph/RideHailingWaitingGraphSpec.scala
src/test/scala/beam/agentsim/agents/ridehail/graph/RideHailingWaitingSingleStatsSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/479)

Fix master merge

---

src/main/java/beam/analysis/plots/PersonVehicleTransitionStats.java

Added trip histogram for car
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/492)

added trip histogram for car

---

docs/developers.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/466)

Documentation: Scala tips

---

src/main/scala/beam/agentsim/agents/ridehail/allocation/EVFleetAllocationManager.scala
src/main/scala/beam/agentsim/agents/ridehail/allocation/ImmediateDispatchWithOverwrite.scala
src/main/scala/beam/agentsim/agents/ridehail/allocation/RideHailResourceAllocationManager.scala

>>> Package names are written in all lower case to avoid conflict with the names of classes or interfaces.
http://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/499)

Project: Namespace must be in lowercase

---

src/main/scala/beam/sim/BeamMobsim.scala
src/main/scala/beam/utils/RandomUtils.scala

Here is simple benchmark to compare performance: https://pastebin.com/08pdHWiB
On my machine it gives:
```
useJava executed in 1645 ms. Total: 40000000
useScala executed in 723 ms. Total: 40000000
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/498)

Use `scala.util.Random` to shuffle persons

---

src/main/scala/beam/agentsim/scheduler/BeamAgentScheduler.scala
src/main/scala/beam/agentsim/scheduler/TriggerMeasurer.scala
src/main/scala/beam/utils/Statistics.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/478)

Measure trigger resolution time

---

src/test/scala/beam/integration/DriveTransitSpec.scala
src/test/scala/beam/integration/LCCMSpec.scala
src/test/scala/beam/integration/ModeChoiceSpec.scala
src/test/scala/beam/integration/MultinomialCustomConfigSpec.scala
src/test/scala/beam/integration/ParkingSpec.scala
src/test/scala/beam/integration/TestConstants.scala
src/test/scala/beam/integration/TollPriceSpec.scala
src/test/scala/beam/integration/TransitCapacitySpec.scala
src/test/scala/beam/integration/TransitPriceSpec.scala
src/test/scala/beam/integration/ridehail/RideHailAllocationRandomRepositioningSpec.scala
src/test/scala/beam/integration/ridehail/RideHailCostPerMileSpec.scala
src/test/scala/beam/integration/ridehail/RideHailCostPerMinuteSpec.scala
src/test/scala/beam/integration/ridehail/RideHailNumDriversSpec.scala
src/test/scala/beam/integration/ridehail/RideHailPriceSpec.scala
src/test/scala/beam/integration/ridehail/RideHailReplaceAllocationSpec.scala
src/test/scala/beam/integration/ridehail/RideHailTestHelper.scala

Small refactor for:
- Extraction methods: avoid redundance
- Linearization of variables declaration: increase readability
- Replaced magic string with constant definition
- Removed commented code
- Removed author
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/503)

Ridehail tests package - refactor

---

src/main/java/beam/analysis/plots/RealizedModeStats.java
src/test/java/beam/analysis/plots/RealizedModeGraphTest.java

realized mode optimization
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/527)

realized mode optimization

---

src/main/java/beam/analysis/plots/RealizedModeStats.java
src/main/scala/beam/sim/BeamHelper.scala
src/main/scala/beam/sim/LoggingParallelEventsManager.scala
src/test/java/beam/analysis/plots/RealizedModeGraphTest.java

- Fixed performance issue with `RealizedModeStats.java`
- Introduced `LoggingParallelEventsManager ` which will log an exceptions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/530)

Plots: Fixed RealizedModeStats

---

src/test/scala/beam/agentsim/agents/OtherPersonAgentSpec.scala
src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala
src/test/scala/beam/agentsim/agents/RideHailAgentSpec.scala
src/test/scala/beam/agentsim/agents/ridehail/RideHailSurgePricingManagerSpec.scala
src/test/scala/beam/agentsim/agents/ridehail/graph/FuelUsageStatsGraphSpec.scala
src/test/scala/beam/agentsim/agents/ridehail/graph/ModeChosenStatsGraphSpec.scala
src/test/scala/beam/agentsim/agents/ridehail/graph/PersonTravelTimeStatsGraphSpec.scala
src/test/scala/beam/agentsim/agents/ridehail/graph/RealizedModeStatsGraphSpec.scala
src/test/scala/beam/agentsim/agents/ridehail/graph/RideHailingWaitingGraphSpec.scala
src/test/scala/beam/agentsim/agents/ridehail/graph/RideHailingWaitingSingleStatsSpec.scala
src/test/scala/beam/agentsim/infrastructure/ZonalParkingManagerSpec.scala
src/test/scala/beam/integration/EventsFileSpec.scala
src/test/scala/beam/integration/IntegrationSpecCommon.scala
src/test/scala/beam/integration/StartWithCustomConfig.scala
src/test/scala/beam/performance/RouterPerformanceSpec.scala
src/test/scala/beam/replanning/utilitybased/ChainBasedTourAllocatorSpec.scala
src/test/scala/beam/sflight/AbstractSfLightSpec.scala
src/test/scala/beam/sim/BeamAgentSchedulerSpec.scala
src/test/scala/beam/tnctoday/TnctodayConversionSpec.scala

Closes #528
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/529)

lazify all non-trivial constructor vals

---

src/main/scala/beam/agentsim/agents/ridehail/allocation/RideHailResourceAllocationManager.scala
src/test/scala/beam/integration/ridehail/RideHailBufferedRidesSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/547)

Refactored the loading of RideHailManager to use reflection

---

build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/545)

Re-add scalafmt to compile

---

src/main/java/beam/analysis/plots/PersonVehicleTransitionStats.java

handled car events with hyphen(-) in vehicle id for trip histogram
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/553)

handled car events with hyphen(-) in vehicle id for trip histogram

---

src/main/java/beam/analysis/physsim/PhyssimCalcLinkSpeedStats.java
src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java

Signed-off-by: Bhavya Latha Bandaru <bhavyalathab@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/564)

calculate average link speed over free flow speed for a given day

---

src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/562)

Disabled failing test

---

src/main/scala/beam/agentsim/agents/Population.scala
src/main/scala/beam/agentsim/agents/TransitDriverAgent.scala
src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala
src/main/scala/beam/agentsim/agents/ridehail/BufferedRideHailRequests.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailModifyPassengerScheduleManager.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailRequest.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailResponse.scala
src/main/scala/beam/agentsim/agents/vehicles/EnergyEconomyAttributes.scala
src/main/scala/beam/agentsim/scheduler/BeamAgentScheduler.scala
src/main/scala/beam/agentsim/scheduler/TriggerMeasurer.scala
src/main/scala/beam/calibration/utils/CreateExperiment.scala
src/main/scala/beam/calibration/utils/DeleteSuggestion.scala
src/main/scala/beam/playground/rashid/physicalSim/jdeqsim/oneZone/ActorVersionJDEQSim.scala
src/main/scala/beam/replanning/utilitybased/ChainBasedTourVehicleAllocator.scala
src/main/scala/beam/router/BeamRouter.scala
src/main/scala/beam/router/r5/R5RoutingWorker.scala
src/main/scala/beam/sim/BeamHelper.scala
src/main/scala/beam/sim/BeamMobsim.scala
src/main/scala/beam/sim/BeamServices.scala
src/main/scala/beam/sim/BeamSim.scala
src/main/scala/beam/sim/LoggingParallelEventsManager.scala
src/main/scala/beam/sim/common/GeoUtils.scala
src/main/scala/beam/utils/SpatialPlot.scala
src/main/scala/beam/utils/StuckFinderHelper.scala
src/main/scala/beam/utils/matsim_conversion/ConversionConfig.scala
src/main/scala/beam/utils/matsim_conversion/MatsimConversionTool.scala

Removed redundant enclosing block: 22 warnings
Removed redundant braces: 5 warnings
Removed redundant conversion inspection: 1 warning
Removed unecessary braces in imports: 3 warnings
Replaced var with val: 9
Removed unused variables: 10 warning
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/570)

Refactor - removed 50 warnings

---

src/main/scala/beam/agentsim/agents/ridehail/RideHailModifyPassengerScheduleManager.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/575)

Clean up code - Simplified expression

---

src/main/scala/beam/agentsim/agents/ridehail/BufferedRideHailRequests.scala
src/main/scala/beam/agentsim/agents/ridehail/OutOfServiceVehicleManager.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailModifyPassengerScheduleManager.scala
src/main/scala/beam/agentsim/agents/ridehail/allocation/EVFleetAllocationManager.scala
src/main/scala/beam/agentsim/infrastructure/ZonalParkingManager.scala
src/main/scala/beam/router/BeamRouter.scala
src/main/scala/beam/router/TransitInitializer.scala
src/main/scala/beam/router/r5/R5RoutingWorker.scala
src/main/scala/beam/sim/metrics/Metrics.scala

- Replaced map with foreach for side-effect expressions: 1 warning
- Added type annotation for Unit and public methods: 7 warnings
- Replaced null initialization with scala syntax underscore: 2 warnings
- Removed redundant get when getting a value from a map: 8 warnings
- Simplified complex filter expressions: 2 warnings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/576)

Clean up - Removed 20 warnings

---

src/main/scala/beam/agentsim/agents/ridehail/RepositionVehicleRequest.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailModifyPassengerScheduleManager.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/577)

Cleanup - Extracted top-level class to exclusive file

---

aws/src/main/python/beam_lambda/lambda_function.py
src/main/bash/search-ec2.bat

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/579)

ec2 search utility fixed #574 and fixed #559

---

production/common/akka.conf
src/main/scala/beam/sim/BeamHelper.scala
test/input/common/akka.conf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/588)

Cluster: Fix cluster init

---

docs/developers.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/590)

Scala tips note

---

beam-gui/build.gradle
src/main/scala/beam/agentsim/scheduler/BeamAgentScheduler.scala
src/main/scala/beam/router/r5/R5RoutingWorker.scala
src/main/scala/beam/sim/LoggingParallelEventsManager.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/598)

Preparation of release 0.6.0 archives fixed #597

---

src/main/scala/beam/sim/BeamHelper.scala
src/main/scala/beam/utils/BashUtils.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/609)

fix broken build

---

src/main/java/beam/analysis/plots/DeadHeadingStats.java
src/main/java/beam/analysis/plots/passengerpertrip/CarPassengerPerTrip.java
src/main/java/beam/analysis/plots/passengerpertrip/GenericPassengerPerTrip.java
src/main/java/beam/analysis/plots/passengerpertrip/IGraphPassengerPerTrip.java
src/main/java/beam/analysis/plots/passengerpertrip/TncPassengerPerTrip.java
src/main/java/beam/utils/BeamCalcLinkStats.java

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/607)

Project: Memory optimizations

---

aws/src/main/python/beam_lambda/lambda_function.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/619)

lambda ending script fixed #618

---

src/main/java/beam/utils/LoggingUtil.java
src/main/scala/beam/sim/BeamHelper.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/617)

file logger fixed #599

---

src/main/scala/beam/router/r5/R5RoutingWorker.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/622)

BugFix: Explicitly set threads for ExecutorService to be daemon

---

src/main/scala/beam/replanning/ReplanningUtil.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/642)

add copyRemainingPlanElementsIfExperiencedPlanIncomplete

---

src/main/bash/prep-warmstart.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/637)

prepare warm start fixed #636

---

src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java
src/main/java/beam/utils/BeamCalcLinkStats.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/648)

large link stats writing issue fixed #639

---

aws/src/main/python/beam_lambda/lambda_function.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/650)

auto deployment changes fixed #649

---

src/main/java/beam/analysis/plots/ModeChosenStats.java
src/main/java/beam/analysis/plots/RealizedModeStats.java

modeChoice and realizedMode graphs are now tuning with each iteration, also data for 0th iteration is coming properly now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/651)

Done changes for updating modeChoice and realizedMode root graphs after each iteration.

---

src/main/java/beam/utils/UnzipUtility.java
src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceMultinomialLogit.scala
src/main/scala/beam/router/r5/R5RoutingWorker.scala
src/main/scala/beam/sim/BeamHelper.scala
src/main/scala/beam/sim/BeamMobsim.scala
src/main/scala/beam/sim/BeamServices.scala
src/main/scala/beam/sim/BeamWarmStart.scala
src/test/scala/beam/router/WarmStartRoutingSpec.scala
test/input/beamville/beam.conf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/653)

load population fixed #640

---

aws/src/main/python/beam_lambda/lambda_function.py
aws/src/main/python/beam_lambda/simulateBeam.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/658)

start web server with startup of auto-deploy instance fixed #657

---

src/main/java/beam/analysis/plots/PersonTravelTimeStats.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/690)

average_travel_times.csv mode change to string fixed #681

---

src/main/java/beam/utils/BeamCalcLinkStats.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/686)

Removed unused variable

---

src/main/scala/beam/agentsim/agents/ridehail/allocation/EVFleetAllocationManager.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/683)

simplified expression

---

src/main/scala/beam/calibration/utils/DeleteSuggestion.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/685)

removed redundancy and improved readability

---

src/main/scala/beam/agentsim/agents/ridehail/allocation/EVFleetAllocationManager.scala
src/main/scala/beam/agentsim/agents/vehicles/PassengerSchedule.scala
src/main/scala/beam/agentsim/infrastructure/ZonalParkingManager.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/684)

Removed unecessary semicolon

---

src/test/scala/beam/router/WarmStartRoutingSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/714)

warm start test fix

---

build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/709)

Update scala to 2.12.7

---

build.gradle
docs/users.rst
src/main/scala/beam/utils/matsim_conversion/VehiclesDataConversion.scala

As beam has already a gradle executable, it's just a matter of running command: 
`gradlew matsimConversion -PconfPath=/path/to/siouxfalls.conf.`
I guess the only dependency is to have beam downloaded and Java installed. 
Note: I had to add lazy to the vals because of null pointer exception while running the conversion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/723)

#703 - gradle task to run matsim conversion

---

src/test/scala/beam/router/WarmStartRoutingSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/728)

fixed router test

---

src/main/scala/beam/agentsim/agents/household/HouseholdActor.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/729)

fixed broken flow

---

src/main/java/beam/analysis/physsim/PhyssimCalcLinkStats.java
src/main/java/beam/analysis/plots/RideHailWaitingStats.java
src/main/java/beam/router/r5/OsmToMATSim.java
src/main/java/beam/router/r5/R5MnetBuilder.java
src/main/java/beam/utils/BeamCalcLinkStats.java
src/main/java/beam/utils/gtfs/merging/TransitScheduleSimplifier.java
src/test/java/beam/analysis/plots/PersonTravelTimeTest.java
src/test/scala/beam/analisis/physsim/BeamCalcLinkStatsSpec.scala

Removed unused variables
Transformed fields in local variables
Removed superflous override method
Removed dead code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/747)

Cleanup 0010

---

src/test/scala/beam/agentsim/agents/RideHailAgentSpec.scala
src/test/scala/beam/integration/TransitCapacitySpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/741)

fixed test warnings

---

src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java

fixed #730
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/731)

handle case, when counts compare not available

---

src/main/scala/beam/sim/BeamSim.scala
src/test/scala/beam/integration/ReplanningExpBetaModeChoiceSpec.scala

fixed #733
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/740)

replanning expbeta modechoice test

---

src/test/scala/beam/sim/BeamWarmStartSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/755)

tracing removed from tests

---

src/main/java/beam/analysis/plots/GraphsStatsAgentSimEventsListener.java
src/main/java/beam/analysis/plots/ModeChosenStats.java
src/test/scala/beam/agentsim/agents/ridehail/graph/ModeChosenStatsGraphSpec.scala

update root mode choice graph and reference mode choice graph with each iteration
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/750)

update root mode choice graph with each iteration

---

src/main/scala/beam/calibration/RunCalibration.scala
src/main/scala/beam/replanning/ReplanningUtil.scala
src/main/scala/beam/sim/BeamServices.scala
src/main/scala/beam/utils/OptionalUtils.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/745)

Simplifications and removed redundant code

---

src/main/scala/beam/replanning/utilitybased/ChainBasedTourVehicleAllocator.scala

fixed #764
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/766)

fix sort by start time

---

src/main/scala/beam/replanning/BeamExpBeta.scala
src/main/scala/beam/replanning/BeamTimeMutator.scala
src/main/scala/beam/replanning/ClearModes.scala
src/main/scala/beam/replanning/ClearRoutes.scala
src/main/scala/beam/replanning/PlansStrategyAdopter.scala
src/main/scala/beam/replanning/ReplanningUtil.scala
src/main/scala/beam/replanning/SwitchModalityStyle.scala
src/main/scala/beam/replanning/utilitybased/ChainBasedTourVehicleAllocator.scala
src/main/scala/beam/replanning/utilitybased/ChangeModeForTour.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/763)

refactror replanning, fixed warnings and duplications

---

src/main/java/beam/utils/gis/Network2ShpLines.java
src/main/java/beam/utils/gtfs/MATSim2GTFS.java
test/input/siouxfalls/conversion-input/Siouxfalls_facilities.xml.gz
test/input/siouxfalls/conversion-input/Siouxfalls_transitSchedule.xml
test/input/siouxfalls/conversion-input/Siouxfalls_vehicles.xml

Closes #754
Updates the sioux falls simulation with transit by using the MATSimToGTFS utility developed by conveyal. 
Also adds facilities.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/758)

Sioux falls updates

---

production/sfbay/base.conf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/777)

Fix path to benchmark

---

src/main/java/beam/analysis/plots/ModeChosenStats.java

- Load `benchMarkData` one time
- Log if can't load `benchMarkData`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/776)

ModeChosenStats: Log if can't load benchmark data

---

src/main/java/beam/analysis/plots/ModeChosenStats.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/778)

ModeChosenStats: Change log level from error to warn

---

docs/users.rst

Fixed #769
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/770)

update user's guide according to current released

---

src/test/scala/beam/analysis/physsim/BeamCalcLinkStatsSpec.scala

Fixed #694
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/773)

correct spelling of package analisis

---

src/main/scala/beam/sim/BeamHelper.scala
src/main/scala/beam/utils/BeamConfigUtils.scala

fixed #721
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/772)

report error if config not found

---

src/main/scala/beam/router/TransitInitializer.scala
src/main/scala/beam/sim/metrics/MetricsPrinter.scala
src/main/scala/beam/utils/matsim_conversion/VehiclesDataConversion.scala
src/test/scala/beam/agentsim/SingleModeSpec.scala
src/test/scala/beam/agentsim/agents/choice/logit/MultinomialLogitSpec.scala
src/test/scala/beam/agentsim/agents/ridehail/graph/RideHailingWaitingGraphSpec.scala
src/test/scala/beam/tnctoday/TnctodayConversionSpec.scala

Removed warnings due to unnecessary parenthesis
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/785)

Removed unnecessary/superfluous parenthesis

---

src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
src/main/scala/beam/agentsim/agents/ridehail/allocation/EVFleetAllocationManager.scala

Run on EV-fleet.conf with 5 iteration:
Only this branch: https://drive.google.com/open?id=1Mm7OCJbdCCQgl6KZ978_aG2jQfFeYWe1
With zonal parking optimization: https://drive.google.com/open?id=1wjdqxzLon_3ADtMz3OYdqOkx5Xtk0Tz4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/780)

EV: Fixed allocation

---

src/main/scala/beam/agentsim/infrastructure/IndexerForZonalParkingManager.scala
src/main/scala/beam/agentsim/infrastructure/ParkingStall.scala
src/main/scala/beam/agentsim/infrastructure/ZonalParkingManager.scala
src/test/scala/beam/agentsim/infrastructure/IndexerForZonalParkingManagerTest.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/744)

Optimized find pooled resources in ZonalParkingManager

---

src/main/scala/beam/utils/matsim_conversion/MatsimPlanConversion.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/789)

fix compilation issue

---

src/main/scala/beam/utils/matsim_conversion/MatsimPlanConversion.scala
src/test/scala/beam/router/RoutingModelSpec.scala

Added parameter names and removed magic strings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/787)

Cleanup - removed warnings

---

beam-gui/src/main/java/beam/gui/PopulationSampler.java
src/main/java/beam/analysis/plots/ModeChosenStats.java
src/main/java/beam/analysis/plots/RideHailWaitingStats.java
src/main/java/beam/analysis/plots/passengerpertrip/TncPassengerPerTrip.java
src/main/java/beam/utils/gtfs/MATSim2GTFS.java

Replaced for loop with foreach: 3 warnings
Removed unnecessary boxing: 1 warning
Removed unnecessary unboxing: 3 warnings
Fixed typo: 1 warning
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/792)

Cleanup - removed 8 warnings

---

src/main/scala/beam/sim/BeamSim.scala

Fixed #779 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/791)

modality style plot optional

---

src/main/java/beam/analysis/plots/PersonVehicleTransitionStats.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/797)

string comparison using == operator fixed

---

src/main/java/beam/analysis/plots/RealizedModeStats.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/796)

bug ModeHour.equals fixed

---

src/main/scala/beam/agentsim/agents/vehicles/BeamVehicleType.scala
src/main/scala/beam/calibration/utils/ListExperiments.scala
src/main/scala/beam/calibration/utils/ListSuggestions.scala
src/main/scala/beam/router/gtfs/FareCalculator.scala
src/main/scala/beam/router/osm/TollCalculator.scala
src/main/scala/beam/scoring/BeamScoringFunctionFactory.scala
src/main/scala/beam/sim/FakeTravelTimeCalculator.scala
src/main/scala/beam/sim/population/PopulationAdjustment.scala
src/main/scala/beam/utils/OptionalUtils.scala
src/main/scala/beam/utils/SpatialPlot.scala
src/main/scala/beam/utils/StuckFinder.scala
src/main/scala/beam/utils/matsim_conversion/MatsimPlanConversion.scala
src/main/scala/beam/utils/scripts/PopulationWriterCSV.scala
src/test/scala/beam/agentsim/agents/ridehail/RideHailSurgePricingManagerSpec.scala
src/test/scala/beam/integration/ridehail/RideHailBufferedRidesSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/798)

lambda function improvement, method signature and general warnings

---

src/main/java/beam/agentsim/agents/choice/logit/NestedLogit.java
src/main/java/beam/analysis/PathTraversalEventGenerationFromCsv.java
src/main/java/beam/analysis/PathTraversalLib.java
src/main/java/beam/analysis/R5NetworkReader.java
src/main/java/beam/analysis/plots/GraphUtils.java
src/main/java/beam/analysis/plots/IGraphStats.java
src/main/java/beam/analysis/plots/ModeChosenStats.java
src/main/java/beam/analysis/plots/RideHailWaitingStats.java
src/main/java/beam/analysis/plots/RideHailingWaitingSingleStats.java
src/main/java/beam/analysis/plots/passengerpertrip/CarPassengerPerTrip.java
src/main/java/beam/analysis/plots/passengerpertrip/GenericPassengerPerTrip.java
src/main/java/beam/analysis/plots/passengerpertrip/TncPassengerPerTrip.java
src/main/java/beam/analysis/spatialtemporalTAZ/SpatialTemporalTAZVizDataWriter.java
src/main/java/beam/analysis/via/EventWriterXML_viaCompatible.java
src/main/java/beam/router/r5/OsmToMATSim.java
src/main/java/beam/utils/gtfs/merging/VehicleMerger.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/795)

refactor redundant code(if, variable, exception)

---

src/main/java/beam/agentsim/events/PathTraversalEvent.java
src/main/java/beam/analysis/PathTraversalEventGenerationFromCsv.java
src/main/java/beam/analysis/PathTraversalSpatialTemporalTableGenerator.java
src/main/java/beam/analysis/plots/ModeChosenStats.java
src/main/java/beam/analysis/plots/PersonVehicleTransitionStats.java
src/main/java/beam/utils/gis/Network2ShpLines.java
src/main/java/beam/utils/gtfs/MATSim2GTFS.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/794)

unchecked warnings fixed

---

src/main/scala/beam/agentsim/agents/choice/mode/DrivingCostDefaults.scala
src/main/scala/beam/agentsim/agents/choice/mode/RideHailDefaults.scala
src/main/scala/beam/agentsim/agents/choice/mode/TransitFareDefaults.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/804)

Cost calculation: Use BigDecimal instead of Double to have less boxings

---

src/main/scala/beam/agentsim/agents/PersonAgent.scala
src/main/scala/beam/agentsim/agents/choice/logit/MultinomialLogit.scala
src/main/scala/beam/agentsim/agents/choice/mode/BridgeTollDefaults.scala
src/main/scala/beam/agentsim/agents/choice/mode/DrivingCostDefaults.scala
src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceDriveIfAvailable.scala
src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceLCCM.scala
src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceMultinomialLogit.scala
src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceRideHailIfAvailable.scala
src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceTransitIfAvailable.scala
src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceUniformRandom.scala
src/main/scala/beam/agentsim/agents/choice/mode/RideHailDefaults.scala
src/main/scala/beam/agentsim/agents/choice/mode/TransitFareDefaults.scala
src/main/scala/beam/agentsim/agents/household/HouseholdActor.scala
src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala
src/main/scala/beam/agentsim/agents/modalbehaviors/ModeChoiceCalculator.scala
src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
src/main/scala/beam/replanning/utilitybased/ChangeModeForTour.scala
src/main/scala/beam/router/model/EmbodiedBeamLeg.scala
src/main/scala/beam/router/model/EmbodiedBeamTrip.scala
src/main/scala/beam/router/r5/R5RoutingWorker.scala
src/main/scala/beam/utils/MathUtils.scala
src/test/scala/beam/agentsim/agents/OtherPersonAgentSpec.scala
src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala
src/test/scala/beam/agentsim/agents/ridehail/graph/FuelUsageStatsGraphSpec.scala
src/test/scala/beam/agentsim/agents/ridehail/graph/PersonTravelTimeStatsGraphSpec.scala
src/test/scala/beam/agentsim/agents/ridehail/graph/RideHailingWaitingGraphSpec.scala
src/test/scala/beam/agentsim/agents/ridehail/graph/RideHailingWaitingSingleStatsSpec.scala
src/test/scala/beam/integration/TransitCapacitySpec.scala
src/test/scala/beam/router/RoutingModelSpec.scala

replace BigDecimal with Double

---

aws/src/main/python/updateBeamAMI/lambda_function.py
aws/src/main/python/updateDependencies/lambda_function.py
docs/devops.rst

fixed #718
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/767)

implemented beam dependency auto update process

---

src/main/java/beam/analysis/plots/DeadHeadingStats.java

`collectEvents` check at first is it `PathTraversalEvent` and then call `event.getAttributes()`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/822)

DeadHeadingStats: Less GC pressure by handling only PathTraversalEvent

---

docs/developers.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/827)

added git-lfs link and fix typo

---

src/main/java/beam/analysis/plots/BeamStats.java
src/main/java/beam/analysis/plots/DeadHeadingStats.java
src/main/java/beam/analysis/plots/FuelUsageStats.java
src/main/java/beam/analysis/plots/GraphsStatsAgentSimEventsListener.java
src/main/java/beam/analysis/plots/IterationStats.java
src/main/java/beam/analysis/plots/ModeChosenStats.java
src/main/java/beam/analysis/plots/PersonTravelTimeStats.java
src/main/java/beam/analysis/plots/PersonVehicleTransitionStats.java
src/main/java/beam/analysis/plots/RealizedModeStats.java
src/main/java/beam/analysis/plots/RideHailWaitingStats.java
src/main/java/beam/analysis/plots/RideHailingWaitingSingleStats.java
src/main/java/beam/analysis/plots/StatsComputation.java
src/main/java/beam/analysis/plots/StatsFactory.java
src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java
test/input/beamville/transitVehicleTypesByRoute.csv

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/839)

refactor agentsim stats

---

src/main/java/beam/analysis/plots/ModeChosenStats.java

Mr. Balaian identified this compilation issue in master
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/851)

Wrong reference to the interface

---

src/main/java/beam/analysis/plots/GraphsStatsAgentSimEventsListener.java
src/main/java/beam/analysis/plots/IterationSummaryStats.java
src/main/java/beam/analysis/plots/PersonTravelTimeStats.java
src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java
src/main/scala/beam/sim/BeamSim.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/846)

summary stats collection

---

src/main/scala/beam/agentsim/agents/ridehail/TNCIterationsStatsCollector.scala

Fixed #844
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/845)

TNCIterationsStatsCollector.getTazId should not fail

---

src/main/java/beam/analysis/plots/DeadHeadingStats.java
src/main/java/beam/analysis/plots/GraphsStatsAgentSimEventsListener.java
src/main/java/beam/analysis/plots/StatsFactory.java
src/main/java/beam/analysis/plots/VehicleMilesTraveledStats.java
src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java
src/main/scala/beam/sim/BeamSim.scala

Fixed #853
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/855)

vehicle miles traveled stats

---

src/main/scala/beam/agentsim/agents/choice/mode/ModeSubsidy.scala
src/main/scala/beam/agentsim/agents/vehicles/PassengerSchedule.scala
src/main/scala/beam/replanning/utilitybased/ChainBasedTourVehicleAllocator.scala
src/main/scala/beam/router/r5/R5RoutingWorker.scala
src/main/scala/beam/sim/BeamWarmStart.scala
src/main/scala/beam/sim/metrics/MetricsPrinter.scala
src/main/scala/beam/sim/population/DiffusionPotentialPopulationAdjustment.scala
src/main/scala/beam/utils/BashUtils.scala
src/main/scala/beam/utils/FileUtils.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/843)

Clean out all scala return statements

---

src/main/java/beam/analysis/stats/AboveCapacityPtUsageDurationInSec.java
src/main/scala/beam/agentsim/agents/PersonAgent.scala
src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala

- generate PersonCostEvent for every cost/subsidy value
- update stats key AtCapacityPtUsageDurationInSec => atCapacityPtUsageDurationInSec
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/866)

stats refactoring

---

src/main/java/beam/analysis/plots/StatsFactory.java
src/main/java/beam/analysis/plots/VehicleTravelTimeStats.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/867)

add vehicle hours traveled to stats

---

src/main/java/beam/analysis/plots/AgentDelayStats.java
src/main/java/beam/analysis/stats/AboveCapacityPtUsageDurationInSec.java

Need to do this for scoring function text congruence. Also, all outputs should be in hrs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/869)

Fix stats names slightly

---

build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/878)

Project: Set akka version to 2.5.17

---

docs/users.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/877)

Calibration docs

---

src/main/scala/beam/agentsim/agents/choice/mode/Range.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailRepositioning.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/885)

Remove recent return

---

src/main/scala/beam/calibration/BeamSigoptTuner.scala
src/main/scala/beam/experiment/ExperimentDef.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/876)

Improve encapsulation and avoid NPE

---

src/main/java/beam/agentsim/events/PersonCostEvent.java
src/main/scala/beam/agentsim/agents/PersonAgent.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/901)

removing costIncludingSubsidy (replacing with cost)

---

docs/developers.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/915)

Add a perf tip when it comes to immutable vs mutable

---

src/main/scala/beam/agentsim/agents/TransitDriverAgent.scala
src/main/scala/beam/agentsim/agents/household/HouseholdActor.scala
src/main/scala/beam/agentsim/scheduler/BeamAgentScheduler.scala
src/test/scala/beam/agentsim/agents/OtherPersonAgentSpec.scala
src/test/scala/beam/agentsim/agents/PersonAndTransitDriverSpec.scala
src/test/scala/beam/integration/EventsFileSpec.scala
test/input/beamville/toll-prices.csv

Also, test a person with two transit drivers with maximal time window.
Closes #879
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/941)

Don't stop transit drivers prematurely

---

src/main/java/beam/analysis/plots/ModeChosenAnalysis.java
src/main/scala/beam/calibration/ExperimentRunner.scala

added log warning if benchmark.csv is missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/942)

add log warning for benchmarkFileLoc

---

src/main/scala/beam/agentsim/agents/PersonAgent.scala
src/test/scala/beam/agentsim/agents/OtherPersonAgentSpec.scala
src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala
src/test/scala/beam/agentsim/agents/PersonAndTransitDriverSpec.scala

added the check if cost is equal to 0.0 at personCost event
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/950)

prevent throwing person cost event when the cost is equal to 0.0

---

src/main/scala/beam/agentsim/agents/PersonAgent.scala
src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceMultinomialLogit.scala
src/main/scala/beam/agentsim/agents/choice/mode/ModeSubsidy.scala
src/main/scala/beam/router/BeamRouter.scala
src/main/scala/beam/router/r5/R5RoutingWorker.scala
src/main/scala/beam/sim/BeamServices.scala
src/test/scala/beam/agentsim/agents/OtherPersonAgentSpec.scala
src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala
src/test/scala/beam/agentsim/agents/PersonAndTransitDriverSpec.scala
src/test/scala/beam/agentsim/agents/choice/mode/ModeSubsidySpec.scala
src/test/scala/beam/integration/SingleModeSpec.scala
src/test/scala/beam/sflight/AbstractSfLightSpec.scala
test/input/beamville/subsidies.csv

Fixed #892
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/949)

add fare adjustments in r5

---

src/main/java/beam/agentsim/events/LeavingParkingEventAttrs.java
src/main/java/beam/agentsim/events/ParkEventAttrs.java
src/main/java/beam/agentsim/events/PathTraversalEvent.java
src/main/java/beam/agentsim/events/RefuelEventAttrs.java
src/main/java/beam/agentsim/events/ReserveRideHailEvent.java
src/main/scala/beam/agentsim/events/ParkEvent.scala
src/test/scala/beam/integration/EventsFileSpec.scala
test/input/beamville/test-data/beamville.events.xml

Fixed #954
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/956)

Harmonize event field names

---

src/main/scala/beam/router/model/BeamTrip.scala
src/main/scala/beam/router/r5/R5RoutingWorker.scala
src/test/scala/beam/sflight/SfLightRouterSpec.scala

Fixed #960
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/967)

remove accessMode from beamTrip

---

test/input/beamville/beam.conf
test/input/beamville/ptFares.csv

Closes #972
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/977)

added ptFares.csv to beamville

---

src/main/java/beam/analysis/plots/PersonTravelTimeAnalysis.java
src/test/scala/beam/agentsim/agents/ridehail/graph/PersonTravelTimeStatsGraphSpec.scala

add a root graph for average car  travel time which updates for each iteration,
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/970)

need average car travel time over iterations graph

---

src/main/scala/beam/agentsim/agents/choice/mode/PtFares.scala
test/input/sf-light/ptFares.csv
test/input/sf-light/sf-light-1k.conf
test/input/sf-light/subsidies.csv

Closes #980
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/981)

bug fix: pt fare age rule

---

build.gradle

Closes #983
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/984)

enable beam to publish build to local maven

---

src/main/java/beam/analysis/plots/GraphsStatsAgentSimEventsListener.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/982)

make simulation robust by handling person travel time computation

---

src/main/scala/beam/sim/BeamSim.scala
src/main/scala/beam/sim/config/BeamConfig.scala
src/main/scala/beam/utils/scripts/FailFast.scala

create a class FailFast and add a config option check for broken simulation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/998)

add first config option check in fail fast

---

src/main/scala/beam/sim/BeamPrepareForSim.scala

closes #1005
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1006)

fixes warm start

---

src/main/java/beam/analysis/plots/GraphUtils.java

colors are fixed of all modes in all graphs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1013)

colors of modes should be fixed and same between realized mode vs. chosen mode

---

src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala

Have update the calcFare function in RideHailManager
1. Added a parameter to it
2. Updated the fare calculation formula
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1033)

Added the embodied legs cost to the fare.

---

src/main/scala/beam/agentsim/agents/choice/mode/PtFares.scala

Fixed #1015
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1051)

Fixed #1015 if specified ptfares file missing, report error

---

src/main/scala/beam/agentsim/agents/choice/mode/PtFares.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1054)

Fixed compilation issue

---

src/main/java/beam/analysis/StatsFactory.java
src/main/java/beam/analysis/summary/MotorizedVehicleMilesTraveledAnalysis.java
src/main/java/beam/analysis/summary/VehicleMilesTraveledAnalysis.java
src/main/scala/beam/agentsim/agents/vehicles/BeamVehicleType.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1074)

don't include body vehicle miles in vehicle total miles travelled

---

src/test/scala/beam/agentsim/agents/OtherPersonAgentSpec.scala

Put new triggers into response instead of sending them separately.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1078)

Fix a concurrency bug in a test

---

src/main/scala/beam/sim/BeamHelper.scala
src/main/scala/beam/sim/RunBatch.scala
test/input/beamville/batch/batch.conf

Fixed #1068
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1069)

batch runner implemented

---

src/main/java/beam/analysis/summary/VehicleTravelTimeAnalysis.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1095)

create summary stats for average vehicle delay for motorized leg.

---

test/input/sf-light/sf-light-10k.conf
test/input/sf-light/sf-light-25k.conf
test/input/sf-light/sf-light.conf

NOT WORKING
sf-light(The config file has specified two plans file as input: beamPopulationFile and inputPlansFile)
sf-light-10k(fail fast)
sf-light-25k(warmstrart file not found)
WORKING
sf-light-0.5k
sf-light-1k
sf-light-2.5k
sf-light-5k
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1097)

fix failing run for sf-light scenario 

---

src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala
src/main/scala/beam/analysis/DelayMetricAnalysis.scala
src/main/scala/beam/sim/common/GeoUtils.scala

Fixed #1082 
Change the delayTotalByLinkCapacity plot .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1083)

change delay metric plot 

---

src/main/java/beam/analysis/summary/PersonCostAnalysis.java
src/main/java/beam/analysis/summary/VehicleTravelTimeAnalysis.java

create averageVehicleDelayPerPassengerTrip and averageTripExpenditure for each activity
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1110)

summary stats modification

---

src/main/scala/beam/agentsim/agents/ridehail/OutOfServiceVehicleManager.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailModifyPassengerScheduleManager.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailVehicleManager.scala
src/main/scala/beam/agentsim/agents/ridehail/TNCIterationStats.scala
src/main/scala/beam/agentsim/agents/ridehail/allocation/DebugRepositioning.scala
src/main/scala/beam/agentsim/agents/ridehail/allocation/Pooling.scala
src/main/scala/beam/agentsim/agents/ridehail/allocation/RandomRepositioning.scala
src/main/scala/beam/agentsim/agents/ridehail/allocation/RepositioningLowWaitingTimes.scala
src/main/scala/beam/agentsim/agents/ridehail/allocation/RideHailResourceAllocationManager.scala

moving code around
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1113)

Cs/#1100 Refactor

---

src/main/java/beam/analysis/plots/PersonTravelTimeAnalysis.java
src/main/java/beam/analysis/summary/PersonCostAnalysis.java
src/main/scala/beam/sim/BeamOutputDataDescriptionGenerator.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1124)

rename summary stats ride_hail to onDemandRide

---

src/main/java/beam/analysis/plots/GraphsStatsAgentSimEventsListener.java
src/main/java/beam/analysis/plots/PersonTravelTimeAnalysis.java
src/main/java/beam/analysis/plots/RideHailWaitingAnalysis.java
src/main/java/beam/analysis/summary/PersonCostAnalysis.java
src/main/scala/beam/sim/BeamOutputDataDescriptionGenerator.scala
src/main/scala/beam/sim/BeamSim.scala
src/main/scala/beam/sim/RideHailFleetInitializer.scala

rename ride_hail-> onDemandRide and fix null exception
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1126)

rename ride_hail-> onDemandRide and fix null exception

---

src/main/scala/beam/sim/RideHailFleetInitializer.scala
src/test/scala/beam/integration/SingleModeSpec.scala

Fixed #1131
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1132)

ride hail fleet data writer fixed

---

test/input/beamville/beam.conf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1134)

fix replanningExpBetaModechoicespec test

---

src/main/scala/beam/utils/plan/sampling/PlansSamplerApp.scala

Fixed #1147
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1148)

plan sampler

---

src/main/java/beam/analysis/plots/RideHailWaitingAnalysis.java
src/main/scala/beam/analysis/DelayMetricAnalysis.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1157)

Quick optimizations for RideHailWaitingAnalysis and DelayMetricAnalysis

---

src/test/scala/beam/sflight/SfLightRunSpec.scala
test/input/sf-light/sf-light-0.5k.conf
test/input/sf-light/sf-light-10k.conf
test/input/sf-light/sf-light-1k.conf
test/input/sf-light/sf-light-2.5k.conf
test/input/sf-light/sf-light-25k.conf
test/input/sf-light/sf-light-5k.conf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1161)

Insert new config param everywhere; re-active SFLight test

---

src/test/scala/beam/integration/ParkingSpec.scala
src/test/scala/beam/integration/ReplanningExpBetaModeChoiceSpec.scala
test/input/beamville/beam.conf
test/input/common/matsim.conf

Due to parameterset is an array type we have to set order of parameters
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1173)

change order of parameter

---

src/test/resources/logback-test.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1199)

Tests: Set root log level to INFO

---

src/main/scala/beam/utils/matsim_conversion/VehiclesDataConversion.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1206)

path fix in VehiclesDataConversion

---

src/main/scala/beam/router/osm/TollCalculator.scala
src/main/scala/beam/router/r5/R5RoutingWorker.scala
src/main/scala/beam/utils/matsim_conversion/VehiclesDataConversion.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1216)

TollCalculator: Change type for cache and fields type to java.util.Map

---

src/main/scala/beam/router/r5/R5RoutingWorker.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1225)

fix pt fare bug 

---

src/main/scala/beam/agentsim/infrastructure/ParkingManager.scala
src/main/scala/beam/utils/IdGenerator.scala

- Added `ParkingManagerIdGenerator`
- Do not use hash function as `requestId`, instead use `ParkingManagerIdGenerator`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1222)

ParkingManager: Use ParkingManagerIdGenerator to generate requestId

---

test/input/beamville/r5/osm.mapdb
test/input/beamville/r5/osm.mapdb.p
test/input/beamville/r5/tolls.dat

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1229)

r5 network files fixed

---

src/main/scala/beam/utils/plan/sampling/PlansSamplerApp.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1213)

issue fix for the case of child with work in plan

---

src/main/java/beam/analysis/StatsFactory.java

Resolving https://github.com/LBNL-UCB-STI/beam/issues/1220
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1221)

StatsFactory: Initialize stats only once

---

src/main/scala/beam/router/r5/R5RoutingWorker.scala
src/main/scala/beam/sim/BeamServices.scala
src/main/scala/beam/utils/BeamVehicleUtils.scala
src/main/scala/beam/utils/ScenarioComparator.scala
src/main/scala/beam/utils/ScenarioReaderCsv.scala
src/test/scala/beam/integration/SingleModeSpec.scala
src/test/scala/beam/router/TimeDependentRoutingSpec.scala
src/test/scala/beam/router/TransitInitializerSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1235)

refactor vehicle csv read methods to re-use

---

beam-gui/src/main/java/beam/gui/ConfigEditor.java
beam-gui/src/main/java/beam/gui/Gui.java
src/main/java/beam/agentsim/events/AgencyRevenueEvent.java
src/main/java/beam/agentsim/events/handling/BeamEventsWriterBase.java
src/main/java/beam/agentsim/events/handling/BeamEventsWriterCSV.java
src/main/java/beam/analysis/physsim/PhyssimCalcLinkSpeedStats.java
src/main/java/beam/analysis/plots/DeadHeadingAnalysis.java
src/main/java/beam/analysis/plots/FuelUsageAnalysis.java
src/main/java/beam/analysis/plots/GraphSurgePricing.java
src/main/java/beam/analysis/plots/GraphUtils.java
src/main/java/beam/analysis/plots/GraphsStatsAgentSimEventsListener.java
src/main/java/beam/analysis/plots/modality/ModalityStyleStats.java
src/main/java/beam/analysis/plots/passengerpertrip/CarPassengerPerTrip.java
src/main/java/beam/analysis/plots/passengerpertrip/GenericPassengerPerTrip.java
src/main/java/beam/analysis/plots/passengerpertrip/TncPassengerPerTrip.java
src/main/java/beam/analysis/summary/AgencyRevenueAnalysis.java
src/main/java/beam/analysis/summary/VehicleTravelTimeAnalysis.java
src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java
src/main/java/beam/physsim/jdeqsim/JDEQSimMemoryFootprint.java
src/main/java/beam/router/r5/profile/BeamMcRaptorSuboptimalPathProfileRouter.java
src/main/java/beam/utils/IntegerValueHashMap.java
src/main/java/beam/utils/R5NetWriter.java
src/main/java/beam/utils/debug/DetectDriveTransitRemainingEnRoute.java
src/main/java/beam/utils/debug/FilterAllEventsOfAgent.java
src/test/java/beam/analysis/plots/DeadHeadingGraphTest.java
src/test/java/beam/analysis/plots/FuelUsageGraphTest.java
src/test/java/beam/analysis/plots/GraphTestUtil.java

replaced c-style array definition with java-style: 10
removed unnecessary string conversion: 4
added final to fields: 79
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1245)

Cleanup code - removed 93 warnings

---

src/main/scala/beam/sim/BeamHelper.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1244)

bind EventsManager with EventsManagerImpl in debug mode

---

src/main/scala/beam/utils/plan/sampling/PlansSamplerApp.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1212)

Plan sampler issue fix for the case of child with work in plan

---

src/main/scala/beam/router/BeamSkimmer.scala
src/main/scala/beam/sim/common/GeoUtils.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1255)

skimmer OKAY

---

src/main/scala/beam/router/TransitInitializer.scala
src/main/scala/beam/router/r5/R5RoutingWorker.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1246)

path traversal with length zero, but linkIds mentioned have length non zero

---

aws/src/main/python/beam_lambda/lambda_function.py

Fixes #1254
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1256)

Use glob to gain access to wildcard search

---

src/main/scala/beam/utils/logging/LogAggregatorAppender.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1270)

only threat error messages

---

src/main/scala/beam/router/r5/R5RoutingWorker.scala
src/main/scala/beam/sim/common/GeoUtils.scala
src/main/scala/beam/utils/ScenarioComparator.scala
src/test/scala/beam/agentsim/agents/OtherPersonAgentSpec.scala
src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala
src/test/scala/beam/agentsim/agents/PersonAndTransitDriverSpec.scala
src/test/scala/beam/agentsim/agents/PersonWithCarPlanSpec.scala
src/test/scala/beam/agentsim/agents/PersonWithVehicleSharingSpec.scala
src/test/scala/beam/agentsim/agents/RideHailAgentSpec.scala
src/test/scala/beam/agentsim/agents/ridehail/RideHailSurgePricingManagerSpec.scala
src/test/scala/beam/agentsim/infrastructure/ZonalParkingManagerSpec.scala
src/test/scala/beam/integration/SingleModeSpec.scala
src/test/scala/beam/performance/RouterPerformanceSpec.scala
src/test/scala/beam/router/BicycleVehicleRoutingSpec.scala
src/test/scala/beam/router/TimeDependentRoutingSpec.scala
src/test/scala/beam/router/TollRoutingSpec.scala
src/test/scala/beam/router/WarmStartRoutingSpec.scala
src/test/scala/beam/sflight/AbstractSfLightSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1285)

SingleModeSpec. Remove mock of BeamService to improve runtime of the test

---

src/test/scala/beam/integration/SingleModeSpec.scala
src/test/scala/beam/sflight/AbstractSfLightSpec.scala
src/test/scala/beam/sflight/MultiModalRoutingSpec.scala
src/test/scala/beam/sflight/SfLightRouterSpec.scala
src/test/scala/beam/sflight/SfLightRouterTransitSpec.scala
src/test/scala/beam/utils/SimRunnerForTest.scala

- Explicitly create config
- Remove unused fields
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1287)

SingleModeSpec: Minor fixes

---

src/main/scala/beam/router/BeamRouter.scala
src/main/scala/beam/router/r5/R5RoutingWorker.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1289)

Clean-up resources: Useful for the tests

---

src/main/java/beam/analysis/PathTraversalSpatialTemporalTableGenerator.java
src/main/java/beam/analysis/plots/FuelUsageAnalysis.java
src/test/java/beam/analysis/plots/FuelUsageGraphTest.java
src/test/scala/beam/agentsim/agents/ridehail/graph/FuelUsageStatsGraphSpec.scala

closes #1200 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1305)

remove old fuel use calculation and use whats in PathTraversal

---

src/test/scala/beam/agentsim/agents/PersonWithCarPlanSpec.scala

Fixes #1310
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1315)

Fix length of travel time array in test

---

src/main/scala/beam/agentsim/scheduler/BeamAgentScheduler.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1368)

print ridehail manager state only once when stuck

---

src/main/scala/beam/agentsim/scheduler/BeamAgentScheduler.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1372)

Fix broken master branch due to fmt

---

src/main/java/beam/analysis/plots/DeadHeadingAnalysis.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1374)

change deadheading graph title and relabel legend

---

src/main/scala/beam/utils/BeamVehicleUtils.scala
src/main/scala/beam/utils/plan/sampling/PlansSamplerApp.scala

https://github.com/LBNL-UCB-STI/beam/issues/1320
The purpose of this PR is only synchronise the branches: `competitions-pin_dev` with `master`. Code are kept exactly the same
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1373)

Sync competition with master #1: PlansSamplerApp and dependencies

---

src/main/scala/beam/utils/NetworkXmlToCSV.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1360)

write matsim network out as csv

---

src/main/java/beam/analysis/plots/RealizedModeAnalysis.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1393)

create root graph for replanning count mode choice

---

src/main/scala/beam/utils/StuckFinder.scala
src/test/scala/beam/utils/StuckFinderSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1422)

StuckFinder: Stuck agent due to exceed number of messages is logged only once

---

src/main/scala/beam/router/BeamSkimmer.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1428)

destTaz with the same code as origTaz - bug fixed

---

src/main/scala/beam/router/BeamSkimmer.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1426)

Beam skimmer cleanup 4ci

---

src/main/scala/beam/router/RouteHistory.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1432)

Route history clean up code

---

src/main/java/beam/analysis/plots/GraphUtils.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1436)

keep same color code for realized mode and reference realized mode

---

src/main/scala/beam/utils/scenario/urbansim/UrbanSimScenarioSource.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1434)

replaced lazyLogging with ExponentialLazyLogging

---

src/main/scala/beam/utils/ConfigConsistencyComparator.scala

Fixed #1450
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1451)

fixed beam.inputDirectory resolution issue.

---

test/input/equil-square/equil-0.001k.conf
test/input/sf-light/rideHailFleet.csv
test/input/sf-light/urbansim-100k.conf
test/input/sf-light/urbansim-10k-test-energy.conf
test/input/sf-light/urbansim-10k.conf
test/input/sf-light/urbansim-1k.conf
test/input/sf-light/urbansim-250k.conf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1452)

update missing filePath configs

---

src/main/scala/beam/router/r5/R5RoutingWorker.scala
src/main/scala/beam/sim/BeamHelper.scala
src/main/scala/beam/sim/config/MatSimBeamConfigBuilder.scala
src/main/scala/beam/utils/ScenarioComparator.scala
src/test/scala/beam/agentsim/agents/GenericEventsSpec.scala
src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala
src/test/scala/beam/agentsim/agents/PersonAndTransitDriverSpec.scala
src/test/scala/beam/agentsim/agents/PersonWithPersonalVehiclePlanSpec.scala
src/test/scala/beam/agentsim/agents/PersonWithVehicleSharingSpec.scala
src/test/scala/beam/agentsim/agents/RideHailAgentSpec.scala
src/test/scala/beam/agentsim/agents/household/FastHouseholdCAVSchedulingSpec.scala
src/test/scala/beam/agentsim/agents/household/HouseholdCAVSchedulingTest.scala
src/test/scala/beam/agentsim/agents/ridehail/AlonsoMoraPoolingAlgForRideHailSpec.scala
src/test/scala/beam/agentsim/agents/ridehail/AsyncAlonsoMoraAlgForRideHailSpec.scala
src/test/scala/beam/agentsim/agents/ridehail/RideHailPassengersEventsSpec.scala
src/test/scala/beam/agentsim/agents/ridehail/graph/GraphRunHelper.scala
src/test/scala/beam/integration/CarSharingSpec.scala
src/test/scala/beam/integration/DriveTransitSpec.scala
src/test/scala/beam/integration/LCCMSpec.scala
src/test/scala/beam/integration/ThreeIterationsSpec.scala
src/test/scala/beam/integration/ridehail/RideHailTestHelper.scala
src/test/scala/beam/performance/RouterPerformanceSpec.scala
src/test/scala/beam/router/WarmStartRoutingSpec.scala
src/test/scala/beam/sflight/SfLightRunSpec.scala
src/test/scala/beam/utils/SimRunnerForTest.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1455)

fix matsim config builder name

---

src/main/scala/beam/sim/vehicles/UniformVehiclesAdjustment.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1449)

fixed random distribution and refactored class UniformVehiclesAdjustment

---

src/main/scala/beam/sim/BeamSim.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1457)

reproduce/fix: numberOfVehicles in root folder on production run

---

src/main/java/beam/analysis/plots/DeadHeadingAnalysis.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1463)

DeadHeadingAnalysis: Should not leak if an exception happens

---

src/main/java/beam/analysis/plots/RealizedModeAnalysis.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1465)

RealizedModeAnalysis.java: Fix NPE

---

src/main/scala/beam/utils/ConfigConsistencyComparator.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1469)

ignoring values with empty values in filePaths

---

src/main/scala/beam/sim/BeamHelper.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1476)

log vehicle types count for each household in scenario

---

src/main/scala/beam/sim/BeamHelper.scala
src/main/scala/beam/sim/vehicles/UniformVehiclesAdjustment.scala
src/main/scala/beam/utils/scenario/ScenarioLoader.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1481)

Scenario: Fixed sampling

---

src/main/scala/beam/agentsim/agents/household/HouseholdFleetManager.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1484)

use ExponentialLazyLogging in HouseholdFleetManager

---

src/test/scala/beam/agentsim/agents/ridehail/graph/RealizedModeStatsGraphSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1495)

fix failing realizedModeStatsGraphSpec test

---

src/main/scala/beam/router/BeamRouter.scala
src/main/scala/beam/router/r5/R5RoutingWorker.scala

- Init network at first (so it will create physim.xml if needed)
- Handle `MemberEvent` a bit differ way: remove node only when it's `MemberExited` or `MemberRemoved`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1501)

Cluster: Minor fixes

---

src/main/java/beam/analysis/summary/VehicleMilesTraveledAnalysis.java

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1523)

VehicleMilesTraveledAnalysis: Create string only once

---

src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1527)

only use cars for ridehail

---

src/main/scala/beam/sim/BeamHelper.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1530)

simple grouping method

---

metrics/grafana/dashboards/beam-dashboard.json

- Changed unit format from `µs` to `ns`
- Changed scale to log based 2
- Changed order of graphs
- Added tables on the right side of the tables
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1519)

Metrics: Refactored and fixed unit format

---

src/main/java/beam/analysis/plots/RideHailWaitingAnalysis.java

change unit of averageOnDemandRideWaitTime unit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1555)

change average on demand waiting time unit

---

src/main/java/beam/analysis/plots/passengerpertrip/CarPassengerPerTrip.java
src/main/java/beam/analysis/plots/passengerpertrip/GenericPassengerPerTrip.java
src/main/java/beam/analysis/plots/passengerpertrip/IGraphPassengerPerTrip.java
src/main/java/beam/analysis/plots/passengerpertrip/TncPassengerPerTrip.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1563)

add csv for numberOfPassenger graphs

---

src/main/java/beam/analysis/summary/PersonCostAnalysis.java

Ensure that semantics of total summary stat matches computation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1565)

Fix total cost/incentive summary stat

---

src/main/scala/beam/agentsim/agents/ridehail/AsyncAlonsoMoraAlgForRideHail.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1568)

sorting disk of requests before filtering by distance

---

src/main/scala/beam/router/TravelTimeObserved.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1572)

TravelTimeObserved: Write only observed

---

src/main/java/beam/analysis/plots/PersonTravelTimeAnalysis.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1583)

create graph for non arrived agents in average time analysis

---

src/main/scala/beam/agentsim/agents/PersonAgent.scala

Fixed #1566
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1591)

fix incentive benefit to agent occasionally exceeds fare

---

src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java
src/main/scala/beam/calibration/SigoptExperimentData.scala
src/main/scala/beam/calibration/utils/CreateExperiment.scala
src/main/scala/beam/calibration/utils/SigOptApiToken.scala
src/main/scala/beam/sim/BeamHelper.scala
test/input/beamville/example-calibration/experiment.yml
test/input/sf-light/sf-light-calibration/experiment.yml

Fixed #1577
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1589)

fix calibration runner

---

src/main/java/beam/analysis/plots/PersonTravelTimeAnalysis.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1594)

change others to mixedMode in averageTravelTime graph

---

src/main/scala/beam/router/TravelTimeObserved.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1587)

Draw lines to compare travel time and observed

---

src/main/scala/beam/utils/scenario/urbansim/CsvScenarioReader.scala
src/main/scala/beam/utils/scenario/urbansim/ParquetScenarioReader.scala
src/main/scala/beam/utils/scenario/urbansim/UrbanSimScenarioSource.scala
src/test/scala/beam/utils/scenario/urbansim/ParquetScenarioReaderTest.scala

- Changed `primary_id` column to `parcel_id` for parcel attribute
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1601)

UrbanSim: New column name for parcel

---

src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala

Random [access in List is linear](https://docs.scala-lang.org/overviews/collections/performance-characteristics.html)(`apply` method), better to have array here which has O(1) random access
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1600)

RideHailManager: `persons` has random access, so change it to array

---

src/main/scala/beam/router/TravelTimeObserved.scala

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1598)

Fix scatter plot grid for comparing simulation to real data

---

src/main/scala/beam/utils/GpxCompareSimulationVsReference.scala

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1599)

Add simulation vs reference gpx file

---

src/main/scala/beam/utils/LinkIdsToGpx.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1602)

Tools: Tool to generate gpx from the link ids

---

src/main/bash/warmstart/prep-warmstart-from-run.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1621)

add skims file in warmstart directory

---

src/main/scala/beam/agentsim/agents/PersonAgent.scala
src/main/scala/beam/agentsim/agents/TransitDriverAgent.scala
src/main/scala/beam/agentsim/agents/household/HouseholdCAVDriverAgent.scala
src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailAgent.scala
src/main/scala/beam/router/BeamSkimmer.scala
src/test/scala/beam/agentsim/agents/RideHailAgentSpec.scala
test/input/beamville/r5/tolls.dat

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1613)

skimming energy consumption for passengers

---

build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1625)

Update Akka to the latest

---

src/main/scala/beam/utils/scenario/urbansim/UrbanSimScenarioSource.scala

Issue: https://github.com/LBNL-UCB-STI/beam/issues/1612
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1615)

Changed severity level of log message and removed warnings

---

src/main/scala/beam/router/TravelTimeObserved.scala

```
fromTAZId,toTAZId,hour,timeSimulated,timeObserved,counts
101195,101184,23,272,101.09,1
201284,101273,18,198,106.04,1
201284,100603,7,557,1664.81,1
101254,100665,12,653,1308.12,1
101226,100842,11,731,1147.13,1
101257,101255,13,159,103.72,1
101255,101257,9,157,101.38,1
101255,101251,9,197,213.57,1
101251,101255,14,191,211.61,1
101214,100666,22,659,678.39,1
101156,100454,10,363,669.2,1
101073,10062B,15,644,1299.07,1
101016,101254,14,431,701.25,1
101003,101054,17,480,687.89,1
```
Fixes #1610 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1618)

#1610 add counts column

---

src/main/java/beam/analysis/plots/BaseModeAnalysis.java
src/main/java/beam/analysis/plots/GraphsStatsAgentSimEventsListener.java
src/main/java/beam/analysis/plots/ModeChosenAnalysis.java
src/main/java/beam/analysis/plots/RealizedModeAnalysis.java

test!
fixes #1574 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1578)

1574 - Cleanup analysis (RealizedMode, ModeChosen)

---

src/main/scala/beam/scoring/BeamScoringFunctionFactory.scala
src/main/scala/beam/sim/population/PopulationAttributes.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1596)

output generalized link stats

---

src/main/bash/zipRootAndLastIterationAndUploadToS3.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1628)
#1627

add bash script to zip and upload iteration to s3 #1627

---

src/main/scala/beam/router/BeamSkimmer.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1633)

BeamSkimmer: Set default energy to zero if it's missing in CSV

---

src/main/scala/beam/agentsim/agents/vehicles/BeamVehicleType.scala
src/main/scala/beam/sim/population/PopulationAttributes.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1635)

handle default vehicle type automation level

---

src/main/java/beam/analysis/plots/RealizedModeAnalysis.java
src/test/java/beam/analysis/plots/RealizedModeGraphTest.java

count replaning events
Closes #1593
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1607)

capture all replanning event count

---

src/main/bash/zipRootAndLastIterationAndUploadToS3.sh

#1627
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1645)

add iteration to archive name

---

test/input/sf-light/urbansim/100k/parcel_attr.csv.gz
test/input/sf-light/urbansim/100k/parcels.csv.gz
test/input/sf-light/urbansim/10k/parcel_attr.csv.gz
test/input/sf-light/urbansim/10k/parcels.csv.gz
test/input/sf-light/urbansim/1k/parcel_attr.csv.gz
test/input/sf-light/urbansim/1k/parcels.csv.gz
test/input/sf-light/urbansim/250k/parcel_attr.csv.gz
test/input/sf-light/urbansim/250k/parcels.csv.gz

Addressing : https://github.com/LBNL-UCB-STI/beam/issues/1642 and https://github.com/LBNL-UCB-STI/beam/issues/1641
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1643)

UrbanSim data for sf-light: Fix parcel_id

---

src/main/scala/beam/utils/scenario/urbansim/UrbanSimScenarioSource.scala

Issue: https://github.com/LBNL-UCB-STI/beam/issues/1612
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1649)

Logging error only in a specific condition

---

src/test/scala/beam/sflight/CaccSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1656)

Fixed test description and removed dead code

---

build.gradle

Use matsim `0.10.1-beam-6` from https://github.com/wrashid/matsim
This will solve https://github.com/LBNL-UCB-STI/beam/issues/1636
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1549)

Project: Use forked matsim

---

build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1667)

ScalaTest show execution times

---

build.gradle

Remove redendent dependencies and add lightweight gt-epsg-wkt lib instead of gt-epsg-hsql
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1661)

remove redundant dependencies

---

src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala
src/main/scala/beam/agentsim/agents/modalbehaviors/ModeChoiceCalculator.scala
src/main/scala/beam/router/model/EmbodiedBeamLeg.scala
src/main/scala/beam/router/model/EmbodiedBeamTrip.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1686)

adding replanning penalty

---

build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1694)

Use `R5` from `com.github.LBNL-UCB-STI`

---

build.gradle
src/main/java/beam/router/r5/R5MnetBuilder.java
src/main/scala/beam/router/r5/NetworkCoordinator.scala
src/main/scala/beam/utils/osm/WayFixer.scala
src/test/scala/beam/utils/osm/WayFixerTest.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1707)

Adjust speeds, highways and other things

---

src/main/scala/beam/agentsim/events/PathTraversalEvent.scala
src/main/scala/beam/analysis/DelayMetricAnalysis.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1671)

Events: Added linkTravelTime to attributes of PathTraversalEvent

---

src/main/scala/beam/agentsim/agents/PersonAgent.scala
src/main/scala/beam/router/BeamSkimmer.scala
src/main/scala/beam/router/TravelTimeObserved.scala
src/main/scala/beam/router/model/EmbodiedBeamTrip.scala
src/main/scala/beam/router/r5/R5RoutingWorker.scala
src/main/scala/beam/sim/BeamServices.scala
src/main/scala/beam/sim/BeamSim.scala
src/main/scala/beam/utils/ScenarioComparator.scala
src/test/scala/beam/agentsim/agents/household/FastHouseholdCAVSchedulingSpec.scala

- `injector` is a field of `BeamServices` (it's already god object, won't make it worse :D)
- `TravelTimeObserved` has it's own skimmer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1708)

Scatter plot should include only car travel time

---

src/main/resources/logback.xml
src/main/scala/beam/router/BeamRouter.scala
src/main/scala/beam/router/r5/R5RoutingWorker.scala
src/main/scala/beam/sim/BeamMobsim.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1717)

Log number of times when min speed has been used during the iteration

---

aws/src/main/python/beam_lambda/lambda_function.py

I believe we do not have automation to update the script so may still need to have this uploaded - but at least this way it will push to the deployment channel now
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1718)

Add slack notification for beam deployments

---

src/test/scala/beam/agentsim/agents/OtherPersonAgentSpec.scala
src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala
src/test/scala/beam/agentsim/agents/PersonAndTransitDriverSpec.scala
src/test/scala/beam/agentsim/agents/PersonWithPersonalVehiclePlanSpec.scala
src/test/scala/beam/agentsim/agents/PersonWithVehicleSharingSpec.scala
src/test/scala/beam/utils/TestConfigUtils.scala

Pushing to master since it is currently broken and requires this to work again
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1722)

Fix TravelTimeObserved related tests

---

src/main/scala/beam/router/TravelTimeObserved.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1729)

added observerVsSimulated histogram

---

src/test/scala/beam/utils/SimRunnerForTest.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1736)

SimRunnerForTest: Provide TravelTimeObserved for SimRunnerForTest

---

src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1739)

Hl/#1709 scaling fuel consumption_v2

---

src/main/scala/beam/sim/BeamSim.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1742)

log activities with non-negative end times

---

src/main/java/beam/physsim/jdeqsim/cacc/roadCapacityAdjustmentFunctions/Hao2018CaccRoadCapacityAdjustmentFunction.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1738)

new histogram for all roads

---

src/main/scala/beam/router/BeamSkimmer.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1733)

add logs to beam skimmer

---

src/main/java/beam/utils/LoggingUtil.java
src/main/resources/logback.xml
src/main/scala/beam/router/r5/R5RoutingWorker.scala
src/main/scala/beam/sim/BeamHelper.scala
src/main/scala/beam/utils/ScenarioComparator.scala

- File appender is described in `logback.xml`. Path is injected via p…
- Simplified `logback.xml`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1657)

Project: Simplified logback initialization

---

src/main/bash/zipRootAndLastIterationAndUploadToS3.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1760)

fix exclusion syntax for all iterations

---

src/main/java/beam/analysis/physsim/PhyssimNetworkLinkLengthDistribution.java
src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1762)

histogram to check link length distributions within the network

---

src/main/scala/beam/agentsim/agents/ridehail/RideHailVehicleManager.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1758)

Minor improvements for getClosestIdleVehiclesWithinRadiusByETA

---

src/main/scala/beam/utils/NetworkXmlToCSV.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1778)

NetworkXmlToCSV: Escape comma for the mergeOutput too

---

src/main/scala/beam/utils/PhyssimEventsXmlToCSV.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1777)

convert physsim event xml to csv

---

src/main/scala/beam/router/BeamSkimmer.scala
src/test/scala/beam/router/BeamSkimmerSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1784)

Added test for CSV read/write and small refactoring

---

src/main/scala/beam/utils/scenario/urbansim/CsvScenarioReader.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1785)

fixed conversion from double as string to int

---

src/test/scala/beam/router/WarmStartRoutingSpec.scala

Fixes #1786.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1786)

Fix WarmStartRoutingSpec

---

src/main/scala/beam/utils/scripts/FailFast.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1795)

Fix scheduler parallelism window and request buffer timeout condition

---

src/test/scala/beam/sflight/UrbanSimRunSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1807)

Integration test for UrbanSim (urbansim-1k.conf)

---

src/main/java/beam/analysis/summary/VehicleTravelTimeAnalysis.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1811)

updating bus crowding

---

src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala
src/test/scala/beam/agentsim/agents/DrivesVehicleTest.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1770)

Imperative way to `processLinkEvents`

---

src/main/java/beam/analysis/StatsFactory.java
src/main/java/beam/analysis/summary/PersonCostAnalysis.java
src/test/scala/beam/agentsim/agents/GenericEventsSpec.scala
src/test/scala/beam/analysis/plots/PersonCostAnalysisSpec.scala
src/test/scala/beam/analysis/plots/VehicleTravelTimeAnalysisSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1810)

update cost burden by dest act type

---

src/main/java/beam/analysis/summary/PersonCostAnalysis.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1820)

log error, when household income not set

---

src/main/scala/beam/utils/csv/writers/PopulationCsvWriter.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1821)

Use `Option` to make sure NPE won't happen

---

src/main/scala/beam/utils/csv/writers/PopulationCsvWriter.scala

NPE happens when there is no mapping personId -> householdId
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1830)

Avoid NPE when data is missing

---

src/main/scala/beam/sim/BeamHelper.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1832)

Fix dangling people

---

src/main/scala/beam/sim/ArgumentsParser.scala
src/main/scala/beam/sim/BeamHelper.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1829)

extracted class - argumentsParser

---

src/main/scala/beam/utils/csv/writers/PlansCsvWriter.scala
src/main/scala/beam/utils/scenario/Models.scala
src/main/scala/beam/utils/scenario/ScenarioLoader.scala
src/main/scala/beam/utils/scenario/ScenarioWriter.scala
src/main/scala/beam/utils/scenario/matsim/MatsimScenarioReader.scala
src/main/scala/beam/utils/scenario/urbansim/UrbanSimScenarioSource.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1837)

Renamed fields from PlanElement and added planIndex with default value

---

production/sfbay/smart/smart-a-hightech.conf
production/sfbay/smart/smart-a-lowtech.conf
production/sfbay/smart/smart-b-hightech.conf
production/sfbay/smart/smart-b-lowtech.conf
production/sfbay/smart/smart-baseline.conf
production/sfbay/smart/smart-c-hightech.conf
production/sfbay/smart/smart-c-lowtech.conf

change benchmark file path key
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1846)

Fix benchmark file path key

---

src/main/java/beam/agentsim/events/ReplanningEvent.java
src/main/java/beam/analysis/plots/RealizedModeAnalysis.java
src/main/scala/beam/agentsim/agents/PersonAgent.scala
src/main/scala/beam/agentsim/events/resources/AccessRequest.scala

Closes #1840 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1842)

Add Reason for replanning and Generate Repanning Reason count CSV

---

docs/users.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1847)

Minor improvements

---

src/main/java/beam/router/r5/R5MnetBuilder.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1859)

remove null from physsim event file

---

src/main/java/beam/analysis/plots/RealizedModeAnalysis.java
src/main/scala/beam/agentsim/agents/PersonAgent.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1860)

Generate event reason csv in root directory

---

src/main/scala/beam/utils/csv/readers/BeamCsvScenarioReader.scala
src/main/scala/beam/utils/scenario/BeamScenarioLoader.scala
src/main/scala/beam/utils/scenario/Models.scala
src/main/scala/beam/utils/scenario/ScenarioSource.scala
src/main/scala/beam/utils/scenario/UrbanSimScenarioLoader.scala
src/main/scala/beam/utils/scenario/urbansim/UrbanSimScenarioSource.scala
test/input/sf-light/sf-light-10k-csv.conf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1872)

fixed csv reader - added missing household attributes

---

src/main/scala/beam/agentsim/agents/PersonAgent.scala
src/main/scala/beam/agentsim/agents/household/HouseholdActor.scala
src/main/scala/beam/agentsim/agents/household/HouseholdCAVDriverAgent.scala
src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala
src/test/scala/beam/integration/CAVSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1879)

Simplify CAV (treat like transit; no out-of-order boardings anymore)

---

src/main/scala/beam/sim/BeamSim.scala
src/main/scala/beam/utils/csv/writers/PlansCsvWriter.scala
src/main/scala/beam/utils/csv/writers/PopulationCsvWriter.scala

Issue: https://github.com/LBNL-UCB-STI/beam/issues/1875
Plans.csv
-write file plans.csv at root folder before iteration zero
-fix: index is not increasing during the writer
Population.csv
-add the column valueOfTime to population.csv
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1878)

Csv writer changes and fixes - #1875

---

src/main/scala/beam/utils/ConfigConsistencyComparator.scala
src/test/scala/beam/utils/DuplicateConfigKeySpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1880)

check duplicate keys

---

src/main/scala/beam/router/TravelTimeObserved.scala

Fixes #1714 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1750)

fix 15% and 30% line text

---

src/main/java/beam/analysis/summary/VehicleMilesTraveledAnalysis.java

Fixes VehicleMiles Travelled
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1891)

Fix vehicle miles travelled

---

src/main/scala/beam/agentsim/agents/PersonAgent.scala
src/main/scala/beam/agentsim/agents/Population.scala
src/main/scala/beam/agentsim/agents/household/HouseholdActor.scala
src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala
src/main/scala/beam/agentsim/infrastructure/ParkingStall.scala
src/main/scala/beam/agentsim/infrastructure/ZonalParkingManager.scala
src/main/scala/beam/sim/BeamMobsim.scala
src/test/scala/beam/agentsim/agents/BeamvilleFixtures.scala
src/test/scala/beam/agentsim/agents/OtherPersonAgentSpec.scala
src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala
src/test/scala/beam/agentsim/agents/PersonAndTransitDriverSpec.scala
src/test/scala/beam/agentsim/agents/PersonWithPersonalVehiclePlanSpec.scala
src/test/scala/beam/agentsim/agents/PersonWithVehicleSharingSpec.scala
src/test/scala/beam/agentsim/agents/RideHailAgentSpec.scala
src/test/scala/beam/agentsim/infrastructure/ZonalParkingManagerSpec.scala
src/test/scala/beam/performance/RouterPerformanceSpec.scala
src/test/scala/beam/sflight/SfLightRouterTransitSpec.scala

Production run has errors like:
```
10:37:36.848 [ClusterSystem-akka.actor.default-dispatcher-68] ERROR beam.router.r5.R5RoutingWorker - calcRoute failed
java.util.concurrent.ExecutionException: Boxed Error
at scala.concurrent.impl.Promise$.resolver(Promise.scala:87)
at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:79)
at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284)
at scala.concurrent.Promise.complete(Promise.scala:53)
at scala.concurrent.Promise.complete$(Promise.scala:52)
at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
at …
```

Parking stall respects bounding box

---

build.gradle

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1902)

ScalaTest HTML reports

---

src/main/scala/beam/sim/BeamHelper.scala
src/main/scala/beam/sim/BeamScenario.scala
src/main/scala/beam/sim/BeamServices.scala
src/main/scala/beam/sim/BeamSim.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1904)

 Add documentation about lifecycle of typical objects

---

src/main/scala/beam/sim/BeamMobsim.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1909)

Better error message for when body is missing

---

src/main/scala/beam/sim/BeamHelper.scala
src/test/scala/beam/integration/EventsFileSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1917)

avoid networkiCoordinator.init run twice

---

src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceDriveIfAvailable.scala
src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceLCCM.scala
src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceMultinomialLogit.scala
src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceRideHailIfAvailable.scala
src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceTransitIfAvailable.scala
src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceUniformRandom.scala
src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala
src/main/scala/beam/agentsim/agents/modalbehaviors/ModeChoiceCalculator.scala
src/main/scala/beam/sim/BeamHelper.scala
src/main/scala/beam/utils/scenario/BeamScenarioLoader.scala
src/main/scala/scripts/CompareLogs.scala
test/input/beamville/beam-csv.conf
test/input/beamville/beam.conf
test/input/beamville/csvInput/plans.csv
test/input/beamville/csvInput/population.csv
test/input/sf-light/sf-light-1k-csv.conf
test/input/sf-light/urbansim-10k-csv.conf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1922)

Fix loaders 4ci

---

src/main/scala/beam/agentsim/agents/household/FastHouseholdCAVScheduling.scala
src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala
src/main/scala/beam/agentsim/agents/ridehail/AlonsoMoraPoolingAlgForRideHail.scala
src/main/scala/beam/router/BeamSkimmer.scala
src/main/scala/beam/sim/vehiclesharing/AvailabilityBasedRepositioning.scala
src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala
src/test/scala/beam/agentsim/agents/PersonAndTransitDriverSpec.scala
src/test/scala/beam/agentsim/agents/PersonWithPersonalVehiclePlanSpec.scala
src/test/scala/beam/agentsim/agents/PersonWithVehicleSharingSpec.scala
src/test/scala/beam/agentsim/agents/RideHailAgentSpec.scala
src/test/scala/beam/agentsim/agents/household/FastHouseholdCAVSchedulingSpec.scala
src/test/scala/beam/agentsim/agents/ridehail/AlonsoMoraPoolingAlgForRideHailSpec.scala
src/test/scala/beam/agentsim/agents/ridehail/AsyncAlonsoMoraAlgForRideHailSpec.scala
src/test/scala/beam/router/TimeDependentRoutingSpec.scala
src/test/scala/beam/router/TollRoutingSpec.scala
test/input/beamville/beam.conf
test/input/beamville/vehicleTypes.csv
test/input/beamville/vehicles.csv

Due to @zneedell
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1923)

Fix a couple of vehicle type ids

---

src/main/scala/beam/sim/BeamMobsim.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1925)

Validate vehicleTypeId for ride-hail

---

src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceLCCM.scala
src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceMultinomialLogit.scala
src/main/scala/beam/agentsim/infrastructure/ZonalParkingManager.scala
src/main/scala/beam/replanning/utilitybased/ChangeModeForTour.scala
src/main/scala/beam/sim/BeamPrepareForSim.scala
src/main/scala/beam/sim/vehiclesharing/Fleet.scala
src/main/scala/beam/utils/plan/PlansBuilder.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1934)

Use fixed seed in random instances

---

src/main/scala/beam/sim/BeamHelper.scala
src/main/scala/beam/utils/plan/sampling/AvailableModeUtils.scala
src/main/scala/beam/utils/scenario/BeamScenarioLoader.scala
src/main/scala/beam/utils/scenario/urbansim/CsvScenarioReader.scala
src/main/scala/org/matsim/core/scenario/ScenarioBuilder.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1938)

refactored BeamScenarioLoader to build population without side effects

---

build.gradle

Fixes #1961 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1962)

exclude correct r5 dependency

---

src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceLCCM.scala
src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceMultinomialLogit.scala
src/main/scala/beam/agentsim/agents/modalbehaviors/ModeChoiceCalculator.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1967)

Use random from ModeChoiceCalculator

---

src/main/scala/beam/utils/scenario/BeamScenarioLoader.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1976)

added more information to legs and fixed amount of created plans

---

src/main/scala/beam/sim/BeamHelper.scala
src/main/scala/beam/utils/ConfigConsistencyComparator.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1981)

Bring consistency checker back

---

src/main/scala/beam/sim/BeamHelper.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1982)

disabled sample when warmstart

---

src/main/scala/beam/utils/scenario/BeamScenarioLoader.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1984)

Set the score to the plan

---

src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java
src/main/java/beam/physsim/jdeqsim/cacc/roadCapacityAdjustmentFunctions/Hao2018CaccRoadCapacityAdjustmentFunction.java
src/main/java/beam/physsim/jdeqsim/cacc/roadCapacityAdjustmentFunctions/RoadCapacityAdjustmentFunction.java

Fixing https://github.com/LBNL-UCB-STI/beam/issues/1990
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1991)

Use CsvMapWriter to write caccCapacityStats.csv

---

src/main/java/beam/agentsim/events/handling/BeamEventsWriterCSV.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2000)

Always parse java-style

---

src/main/scala/beam/utils/UberOSMSpeedMapper.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2005)

Uber Speed mapper

---

src/main/bash/warmstart/prep-warmstart-new.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2009)

Shell scripting: New script to create warmstart and upload it to S3

---

src/main/scala/beam/replanning/ReplanningUtil.scala
src/main/scala/beam/scoring/BeamScoringFunctionFactory.scala

Solving https://github.com/LBNL-UCB-STI/beam/issues/2015
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2019)

Fix re-planning

---

src/main/scala/beam/replanning/ReplanningUtil.scala
src/main/scala/beam/scoring/BeamScoringFunctionFactory.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2022)

BeamScoringFunctionFactory: Make sure we access only exist elements

---

src/main/scala/beam/replanning/ReplanningUtil.scala
src/main/scala/beam/scoring/BeamScoringFunctionFactory.scala
src/test/scala/beam/integration/ParkingSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2026)

These logs are not actionable, removing them

---

src/main/scala/beam/agentsim/agents/ridehail/RideHailVehicleManager.scala
src/main/scala/beam/agentsim/agents/ridehail/allocation/PoolingAlonsoMora.scala

When I look at JFR, I can see the following:
This is minor optimization, but it allows to get `RideHailAgentLocation` in a faster manner
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2029)

PoolingAlonsoMora: Improve allocateVehiclesToCustomers

---

src/main/scala/beam/sim/BeamSim.scala
src/main/scala/beam/sim/BeamWarmStart.scala
test/input/sf-light/sf-light-25k-warmstart.conf
test/input/sf-light/sf-light-25k.conf

Root folder without compression:
Iteration folder without compression:
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2027)

Warmstart: Compress csv files and dump MATSim stuff in the end of every iteration

---

build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2031)

Update `beam-utilities` to `0.2.4`

---

src/main/bash/warmstart/prep-warmstart-new.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2034)

Reduce the size of warmstart archive

---

src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailModifyPassengerScheduleManager.scala
src/test/scala/beam/integration/AgentsimWithMaximallyBadRouterSpec.scala
test/input/beamville/beam.conf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2041)

Bring back repositioning

---

src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2043)

dont use expensive placeholder

---

src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2044)

bug fix: avoid minus infinity summation in activity end time

---

src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala
src/main/scala/beam/agentsim/events/ChargingPlugInEvent.scala
src/main/scala/beam/agentsim/events/ParkEvent.scala
src/main/scala/beam/sim/common/GeoUtils.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2049)
Closes the issue https://github.com/LBNL-UCB-STI/beam/issues/2033

Make events write location using WGS coordinates system

---

src/test/scala/beam/router/TimeDependentRoutingSpec.scala
src/test/scala/beam/router/TollRoutingSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2056)

Fix broken test case

---

src/main/java/beam/analysis/summary/RideHailSummary.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2084)

avoiding NPE

---

src/main/scala/beam/agentsim/agents/PersonAgent.scala

re: https://github.com/LBNL-UCB-STI/beam/pull/2014#discussion_r312790076
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2089)

Simple logging change

---

src/main/scala/beam/agentsim/infrastructure/ParkingSearchFilterPredicates.scala

fix bad filter tag
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2106)

bad filter value

---

src/main/scala/beam/agentsim/agents/ridehail/AlonsoMoraPoolingAlgForRideHail.scala
src/main/scala/beam/agentsim/agents/ridehail/AsyncAlonsoMoraAlgForRideHail.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2131)

spatial constraints on pool dropoffs

---

src/main/scala/beam/router/r5/R5RoutingWorker.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2132)

bug fix: replacing duration with distance

---

src/main/scala/beam/agentsim/agents/ridehail/AlonsoMoraPoolingAlgForRideHail.scala
src/main/scala/beam/agentsim/agents/ridehail/VehicleCentricMatchingForRideHail.scala
src/main/scala/beam/agentsim/agents/ridehail/allocation/PoolingAlonsoMora.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2137)

runtime improvement for pooling (part2)

---

src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2156)

fix end activity negative infinity

---

src/main/scala/beam/router/r5/R5RoutingWorker.scala

so that beamLegs for transit no longer have 0 distance
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2163)

calculate distance along non-road transit routes

---

src/main/python/events_analysis/analyze_events.py
src/main/python/events_analysis/required_module_installer.py

additional python analysis, should produce plots and stats about vehicle time usage and distance driven for different reasons
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2168)

process vehicle locations

---

aws/src/main/python/beam_lambda/lambda_function.py

to include python analysis setup
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2162)

Update lambda script

---

src/main/java/beam/analysis/plots/ModeChosenAnalysis.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2175)

Add mode chosen available alternative count

---

src/main/scala/beam/sim/BeamHelper.scala
src/main/scala/beam/utils/scenario/urbansim/UrbanSimScenarioSource.scala

#2059
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2177)

fix downloading data from s3

---

src/main/scala/beam/utils/scenario/urbansim/UrbanSimScenarioSource.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2178)

removed slash from path constructor in UrbanSimScenarioSource

---

src/main/scala/beam/router/r5/R5RoutingWorker.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2181)

make bushwhack trips normal walk speed, minkowski dist

---

src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java
src/main/java/beam/physsim/jdeqsim/JDEQSimMemoryFootprint.java
src/main/java/beam/utils/DebugLib.java
src/main/scala/beam/sim/BeamMobsim.scala
src/main/scala/beam/sim/BeamSim.scala
src/main/scala/beam/utils/DebugActorWithTimer.scala

Addressing https://github.com/LBNL-UCB-STI/beam/issues/2188
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2189)

Do not do manual GC

---

src/main/java/beam/analysis/plots/RideHailWaitingAnalysis.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2166)

Change graph yaxis label

---

src/main/scala/beam/agentsim/agents/ridehail/repositioningmanager/DemandFollowingRepositioningManager.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2199)

Make sure arrays are order by hour

---

build.gradle
src/main/scala/beam/utils/Stats.scala

Closes #2032 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2158)

Bump to 2.12.9

---

src/main/java/beam/analysis/physsim/PhyssimCalcLinkStats.java
src/test/java/beam/analysis/physsim/PhyssimCalcLinkStatsTest.java

Closes #2143 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2161)

change bin size to 6 in relative speed

---

src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala

Do not expect actor to be terminated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2210)

Fix broken PersonAgentSpec in develop branch

---

src/main/scala/beam/agentsim/events/PathTraversalEvent.scala
src/main/scala/beam/utils/RespositioingValidation.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2203)

Add Repositioning Analysis

---

src/test/scala/beam/sim/BeamWarmStartRunSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2212)

fix warmstart test error

---

src/main/scala/beam/sim/BeamMobsim.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2214)

Stagger initial tick for repositioning

---

src/test/scala/beam/utils/SpatialIndexForRideHailAgentLocationTest.scala

Cover by unit test the behavior of spatial index for `RideHailAgentLocation`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2221)

Unit test for spatial index for RideHailAgentLocation

---

src/main/scala/beam/analysis/SimpleRideHailUtilization.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2237)

minor bug-fix : to sort iterations in order

---

aws/src/main/python/idleNotifier/lambda_function.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2240)

Add name to idle notification

---

src/main/scala/beam/agentsim/agents/ridehail/repositioningmanager/RepositioningManager.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2250)

Fix compilation error

---

src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2268)

BugFix: RHM Make sure we remove vehicle from idle if we send it to refueling

---

src/main/java/beam/analysis/plots/PersonTravelTimeAnalysis.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2249)

Add csv for non arrived agents

---

src/main/scala/beam/utils/beam_to_matsim/events_filter/MutableVehiclesFilter.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2276)

inm / typo fixed in BEAM-to-MATSim events filter 

---

gradle.deploy.properties
gradle.deployPILATES.properties

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2271)

inm/better default values for deploy and deployPilates gradle tasks

---

src/main/scala/beam/agentsim/agents/ridehail/repositioningmanager/DemandFollowingRepositioningManager.scala

Instead of repositioning to the center of the cluster, reposition the random activity's location
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2281)

DemandFollowingRepositionig: Reposition the random activity's location

---

aws/build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2291)

Add email to deploy

---

build.gradle
production/sfbay/smart/smart-baseline-2010.conf
src/main/java/beam/physsim/jdeqsim/cacc/sim/Road.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2241)

modularize road class

---

aws/src/main/python/beam_lambda/lambda_function.py
aws/src/main/python/runPilates/lambda_function.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2292)

Append stop behavior to tag and backup location to tag

---

aws/src/main/python/ebsVolumeSizeMonitor/lambda_function.py

Closes #2290 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2308)

Add EBS Volume Size Notifier

---

src/main/python/smart/mep/build_diff.py
src/main/python/smart/mep/build_heatmap.py

+ minor update for heatmap script
+ script to build a diff between two datasource files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2309)

inm / heatmap script update

---

src/main/java/beam/agentsim/events/handling/BeamEventsLogger.java
src/main/python/events_analysis/analyze_events.py
src/main/resources/beam-template.conf
src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailAgent.scala
src/main/scala/beam/agentsim/events/ParkingEvent.scala
src/main/scala/beam/analysis/ParkingStatsCollector.scala
src/main/scala/beam/analysis/ParkingTypeAnalysis.scala
src/main/scala/beam/sim/config/BeamConfig.scala
src/main/scala/beam/utils/EventReader.scala
src/test/scala/beam/agentsim/agents/PersonWithPersonalVehiclePlanSpec.scala
src/test/scala/beam/agentsim/agents/PersonWithVehicleSharingSpec.scala
src/test/scala/beam/integration/ParkingSpec.scala
test/input/beamville/beam.conf
test/input/sf-light/sf-light-0.5k.conf
test/input/sf-light/sf-light-10k.conf
test/input/sf-light/sf-light-1k.conf
test/input/sf-light/sf-light-2.5k.conf
test/input/sf-light/sf-light-25k.conf
test/input/sf-light/sf-light-5k.conf
test/input/sf-light/sf-light.conf
test/input/sf-light/urbansim-100k.conf
test/input/sf-light/urbansim-10k-test-energy.conf
test/input/sf-light/urbansim-10k.conf
test/input/sf-light/urbansim-1k-geofence-test.conf
test/input/sf-light/urbansim-1k-rh-ev-cavs.conf
test/input/sf-light/urbansim-1k-rh-ev-humans.conf
test/input/sf-light/urbansim-1k.conf
test/input/sf-light/urbansim-250k.conf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2322)

change ParkEvent to ParkingEvent

---

src/main/scala/beam/utils/FileUtils.scala

Closes #2316 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2326)

add random suffix in output directory

---

build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2330)

resolvers https

---

build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2333)

To fix issue with cert host name validation

---

build.gradle
src/main/scala/beam/agentsim/agents/ridehail/RideHailVehicleManager.scala

This seems simple at it's root - however I want to double check that my GC thoughts are in line - that this will only be a big issue if set to debug or info. Otherwise it's merely adding logging
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2329)

Add more logging

---

src/main/scala/beam/analysis/cartraveltime/CarRideStatsFromPathTraversalEventHandler.scala
src/main/scala/beam/analysis/cartraveltime/models.scala
src/test/scala/beam/agentsim/agents/GenericEventsSpec.scala
src/test/scala/beam/analysis/cartraveltime/CarRideStatsFromPathTraversalEventHandlerSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2337)

#2336 - Add averageCarSpeed.png

---

src/main/scala/beam/router/r5/R5RoutingWorker.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2363)

bug-fix : toll should be applied only to car modes

---

src/main/scala/beam/replanning/ReplanningUtil.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2369)

bug-fix: overflow exception when agent end time less than 23:00:00

---

src/main/scala/beam/utils/data/ctpp/JointDistribution.scala
src/test/scala/beam/utils/JointDistributionTest.scala
test/input/beamville/test-data/joint-distribution.csv

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2388)

joint distribution

---

src/main/java/beam/utils/ReadWriteLockUtil.scala
src/main/scala/beam/agentsim/agents/PersonAgent.scala
src/main/scala/beam/agentsim/agents/household/HouseholdActor.scala
src/main/scala/beam/agentsim/agents/household/HouseholdFleetManager.scala
src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailAgent.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala
src/main/scala/beam/sim/vehiclesharing/FixedNonReservingFleetManager.scala
src/main/scala/beam/sim/vehiclesharing/InexhaustibleReservingFleetManager.scala
src/test/scala/beam/agentsim/agents/PersonWithVehicleSharingSpec.scala
src/test/scala/beam/agentsim/agents/RideHailAgentSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2402)

Make BeamVehicle thread safe

---

src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala
src/main/scala/beam/sim/BeamSim.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2406)

BugFix: Clear the state of BeamVehicle in the end of iteration

---

src/main/scala/beam/analysis/cartraveltime/CarRideStatsFromPathTraversalEventHandler.scala
src/main/scala/beam/analysis/cartraveltime/models.scala

Added graph for hourly average speed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2404)

hourly average speed

---

aws/src/main/python/beam_lambda/lambda_function.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2407)

Deploy: Copy GC logs to S3

---

src/main/java/beam/utils/LoggingUtil.java
src/test/resources/logback-test.xml
src/test/scala/beam/integration/IntegrationSpecCommon.scala

Issue: https://github.com/LBNL-UCB-STI/beam/issues/2415
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2420)

generate Integration tests log in the right output folder

---

src/test/scala/beam/sflight/CaccSpec.scala

Issue #2414
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2422)

Added Car and CAV as car travel time modes

---

src/main/scala/beam/agentsim/agents/choice/logit/LatentClassChoiceModel.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2423)

refactoring: tightened visibility, fixed typo and others

---

src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
src/main/scala/beam/sim/monitoring/ErrorListener.scala

- Add more logs to debug easier
- shiftEndTime is bounded to maxActivityEndTime
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2452)

RideHailManager: RideHailAgent shift is bounded to maxActivityEndTime

---

src/main/python/calibration/generate_rides_with_google_maps.py
src/main/scala/beam/analysis/AnalysisProcessor.scala
src/main/scala/beam/analysis/carridestats/CarRideStatsAdapter.scala
src/main/scala/beam/analysis/carridestats/CarRideStatsAreaBoundBox.scala
src/main/scala/beam/analysis/carridestats/CarRideStatsDepartureTimeIntervalInSeconds.scala
src/main/scala/beam/analysis/carridestats/CarRideStatsInputContent.scala
src/main/scala/beam/analysis/carridestats/CarRideStatsParam.scala
src/main/scala/beam/analysis/carridestats/CarRideStatsRequest.scala
src/main/scala/beam/analysis/carridestats/CarRideStatsSample.scala
src/main/scala/beam/analysis/carridestats/CarRideStatsTravelDistanceIntervalInMeters.scala
src/main/scala/beam/analysis/carridestats/Example1.scala

Resolves: https://github.com/LBNL-UCB-STI/beam/issues/2457
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2468)

Added Scala wrapper for calling CarRideStats python script

---

aws/build.gradle
aws/src/main/python/beam_lambda/lambda_function.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2470)

parse correctly

---

build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2475)

Update Scala to 2.12.11

---

src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2455)

remove dead code

---

src/main/python/nhts_analysis/get_NHTS_work_plans.py
src/main/python/nhts_analysis/outputs/work_activities_12420.csv
src/main/python/nhts_analysis/outputs/work_activities_all_us.csv

addresses #2353
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2361)

generate conditional work start time / duration distribution for Austin and the whole U.S. 

---

aws/src/main/python/beam_lambda/lambda_function.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2481)

Fix lambda boolean even more

---

src/main/python/calibration/generate_rides_with_google_maps.py

- Add departure time to the Google Link
- Print departure time
- Print dataframe information: column names and types
- Limit output for tabulate
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2494)

Route in Google map: minor improvements

---

src/main/java/beam/analysis/plots/RealizedModeAnalysis.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2498)

fix colors for realized mode

---

aws/src/main/python/updateDependencies/lambda_function.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2510)

Simple dependency addition

---

build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2516)

JMX: Fix config to allow to connect from remote via tunelling

---

src/main/scala/beam/utils/data/synthpop/GeoService.scala
src/main/scala/beam/utils/data/synthpop/PumaLevelScenarioGenerator.scala
src/main/scala/beam/utils/data/synthpop/ScenarioGenerator.scala
src/main/scala/beam/utils/data/synthpop/models/Models.scala
src/main/scala/beam/utils/scenario/generic/writers/ParkingInfoWriter.scala

Generates parking files based on regression from San Francisco data. Ex:
> taz,parkingType,pricingModel,chargingType,numStalls,feeInCents,reservedFor
00000123,Public,Block,None,50,0.0,Any
00000123,Workplace,Block,None,183,0.0,Any
00001536,Public,Block,None,30,0.0,Any
00001536,Workplace,Block,None,121,0.0,Any
00000537,Public,Block,None,5,0.0,Any
00000537,Workplace,Block,None,21,0.0,Any
00000236,Public,Block,None,61,0.0,Any
00000236,Workplace,Block,None,247,0.0,Any
00000585,Public,Block,None,14,0.0,Any
00000585,Workplace,Block,None,58,0.0,Any
00000117,Workplace,Block,None,9,0.0,Any
00000117,Residential,Block,None,7,0.0,Any
00001008,Public,Block,None,1,0.0,Any
00001008,Workplace,Block,None,20,0.0,Any
00001008,Residential,Block,None,13,0.0,Any
00001949,Public,Block,None,4,0.0,Any …

Generate parking from ctpp

---

build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2524)

Updated geootols library and repository

---

production/common/metrics.conf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2527)

beam-map-envelope metric enabled for production runs

---

src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala

Changes: waiting until the BeamMobsim.iteration actor actually terminated.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2534)

#2514 Fix of Actor name [BeamMobsim.iteration] is not unique at PersonAgentSpec

---

src/main/java/beam/analysis/plots/ModeChosenAnalysis.java
src/main/java/beam/analysis/plots/RealizedModeAnalysis.java
src/main/java/beam/analysis/plots/RideHailWaitingAnalysis.java
src/main/java/beam/analysis/plots/passengerpertrip/CarPassengerPerTrip.java
src/main/java/beam/analysis/spatialtemporalTAZ/SpatialTemporalTAZVizDataWriter.java
src/main/java/beam/physsim/jdeqsim/cacc/roadCapacityAdjustmentFunctions/Hao2018CaccRoadCapacityAdjustmentFunction.java
src/test/java/beam/analysis/plots/DeadHeadingGraphTest.java
src/test/java/beam/analysis/plots/GraphTestUtil.java
src/test/java/beam/analysis/plots/ModeChosenGraphTest.java
src/test/java/beam/analysis/plots/PersonTravelTimeTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2528)

Refactor - removed 17 warnings

---

src/main/java/beam/analysis/physsim/PhyssimSpeedHandler.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2584)

PhyssimSpeedHandler: Bug fix and replace collection by Mean

---

src/main/scala/beam/agentsim/agents/ridehail/RideHailAgent.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
src/main/scala/beam/agentsim/agents/ridehail/allocation/Pooling.scala
src/main/scala/beam/agentsim/agents/ridehail/allocation/RideHailResourceAllocationManager.scala
src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala
src/main/scala/beam/router/model/BeamLeg.scala
src/main/scala/beam/sim/BeamHelper.scala
src/main/scala/beam/utils/scripts/FailFast.scala

Changes:
- Removed 3 warnings. Replaced equals/Some with contains
- Removed 5 warnings. Replaced find/isDefined with exists
- Removed 4 warnings. Replaced trivial matching with if statement
- Extracted variable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2582)

Refactor - Removed 8 warnings

---

src/main/scala/beam/physsim/jdeqsim/ApproxPhysSim.scala
src/main/scala/beam/physsim/jdeqsim/PhysSim.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2587)

Propagate max hour to travelTimeCalculator config

---

aws/src/main/python/beam_lambda/lambda_function.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2589)

Lambda: Zip and copy JFR to final path

---

src/test/scala/beam/utils/SimRunnerForTest.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2599)

adding Skims.setup(services) and Skims.clear() to SimRunnerForTest

---

src/main/scala/beam/analysis/cartraveltime/CarTripStatsFromPathTraversalEventHandler.scala
src/main/scala/beam/sim/BeamSim.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2608)

fix last hour in average speed and average speed percentage

---

src/main/java/beam/agentsim/events/handling/BeamEventsWriterCSV.java
src/main/java/beam/analysis/PathTraversalSpatialTemporalTableGenerator.java
src/main/java/beam/analysis/plots/RealizedModeAnalysis.java
src/main/java/beam/analysis/plots/RideHailWaitingAnalysis.java
src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailModifyPassengerScheduleManager.scala
src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala
src/main/scala/beam/agentsim/agents/vehicles/PassengerSchedule.scala
src/main/scala/beam/analysis/LoadOverTimeAnalysis.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2595)

Refactor - 20 small improvements

---

src/main/scala/beam/replanning/BeamExpBeta.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2610)

get iterationNumber of BeamExpBeta

---

src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailModifyPassengerScheduleManager.scala
src/main/scala/beam/agentsim/agents/vehicles/PassengerSchedule.scala
src/main/scala/beam/agentsim/agents/vehicles/VehicleEnergy.scala
src/main/scala/beam/router/model/BeamLeg.scala
src/main/scala/beam/sim/RunBatch.scala
src/main/scala/beam/sim/common/Range.scala
src/main/scala/beam/sim/vehicles/VehiclesAdjustment.scala
src/main/scala/beam/sim/vehiclesharing/Fleet.scala
src/main/scala/beam/utils/OptionalUtils.scala
src/main/scala/beam/utils/map/R5NetworkPlayground.scala
src/main/scala/beam/utils/matsim_conversion/MatsimPlanConversion.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2611)

Refactor - simplified 20 expressions

---

src/main/resources/beam-template.conf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2616)

Remove duplicate config

---

src/main/java/beam/analysis/plots/DeadHeadingAnalysis.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2617)

fix deadheading metric

---

src/main/scala/beam/analysis/cartraveltime/CarTripStatsFromPathTraversalEventHandler.scala
src/main/scala/beam/analysis/cartraveltime/models.scala
src/main/scala/beam/utils/Statistics.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2614)

#2597 calculate the weighted mean

---

src/main/scala/beam/analysis/cartraveltime/CarTripStatsFromPathTraversalEventHandler.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2625)

eliminate first link while calculating free speed

---

src/main/java/beam/analysis/plots/DeadHeadingAnalysis.java
src/main/java/beam/analysis/plots/ModeChosenAnalysis.java
src/main/java/beam/analysis/plots/PersonTravelTimeAnalysis.java
src/main/java/beam/analysis/plots/RealizedModeAnalysis.java
src/main/java/beam/analysis/plots/RideHailWaitingTazAnalysis.java
src/main/java/beam/analysis/summary/AboveCapacityPtUsageDurationAnalysis.java
src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java
src/main/scala/beam/agentsim/events/RefuelSessionEvent.scala
src/main/scala/beam/agentsim/infrastructure/taz/TAZ.scala
src/test/scala/beam/agentsim/infrastructure/ZonalParkingManagerSpec.scala
src/test/scala/beam/cosim/helics/BeamFederateSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2631)

Refactor - 30 small improvements / warnings removed

---

build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2638)

simple change to fix fmt check

---

build.gradle
src/main/scala/beam/utils/hereapi/HereAdapter.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2650)

removed play-ws-standalone

---

src/main/java/beam/router/r5/R5MnetBuilder.java
src/main/scala/beam/agentsim/infrastructure/geozone/H3Wrapper.scala
src/main/scala/beam/agentsim/infrastructure/geozone/WgsCoordinate.scala
src/main/scala/beam/router/R5Requester.scala
src/main/scala/beam/router/TransitInitializer.scala
src/main/scala/beam/router/r5/NetworkCoordinator.scala
src/main/scala/beam/router/r5/R5RoutingWorker.scala
src/main/scala/beam/sim/population/PopulationAdjustment.scala
src/main/scala/beam/utils/csv/GenericCsvReader.scala
src/main/scala/beam/utils/csv/writers/PopulationCsvWriter.scala
src/main/scala/beam/utils/data/ctpp/JointDistribution.scala
src/main/scala/beam/utils/map/OsmosisPolygonFilterGenerator.scala
src/main/scala/beam/utils/map/R5MapStatsCalculator.scala
src/main/scala/beam/utils/map/ShapefileReader.scala

https://github.com/LBNL-UCB-STI/beam/tree/art/cttp-parser-4ci is too huge, so this is the first part of the things to be merged to develop
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2655)

Extracted common things to be merged to develop

---

src/main/scala/beam/sim/metrics/SimulationMetricCollector.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2663)

an improved reaction for missing InfluxDB database and disabled metrics

---

src/main/scala/beam/sim/BeamSim.scala
src/main/scala/beam/utils/watcher/MethodWatcher.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2668)

- Time analysis of writing

---

src/main/scala/beam/agentsim/agents/household/HouseholdSolverActor.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
src/main/scala/beam/agentsim/agents/ridehail/allocation/RandomRepositioning.scala
src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala
src/main/scala/beam/agentsim/infrastructure/ParkingStall.scala
src/main/scala/beam/analysis/cartraveltime/CarTripStatsFromPathTraversalEventHandler.scala
src/main/scala/beam/physsim/jdeqsim/CarTravelTimeHandler.scala
src/main/scala/beam/router/model/BeamPath.scala
src/main/scala/beam/router/skim/AbstractSkimmer.scala
src/main/scala/beam/router/skim/CsvSkimReader.scala
src/main/scala/beam/router/skim/ODSkimmer.scala
src/main/scala/beam/router/skim/SkimsUtils.scala
src/main/scala/beam/sim/BeamSim.scala
src/main/scala/beam/sim/BeamWarmStart.scala
src/main/scala/beam/sim/common/GeoUtils.scala
src/main/scala/beam/utils/CoordInBoundsUtil.scala
src/main/scala/beam/utils/RandomUtils.scala
src/main/scala/beam/utils/map/GpxWriter.scala
src/test/scala/beam/sim/RideHailFleetInitializerSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2679)
- removed 1 warnings(possible bug) - comparing unrelated types
- removed 2 warnings - using map in Unit expression
- removed 12 warnings - redundant expressions
- removed 16 warnings - redundant parenthesis
- removed 5 warnings - redundant partial function
Probable bug:
https://github.com/LBNL-UCB-STI/beam/pull/2679/files#diff-be0af8411f14566557c41a2f299029bbR147

Removed 36 warnings

---

src/main/scala/beam/agentsim/infrastructure/geozone/GeoZoneUtil.scala
src/main/scala/beam/analysis/ChargingAnalysis.scala
src/main/scala/beam/utils/shape/GenericFeatureBuilder.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2686)

deprecation warnings broking compilation

---

src/main/java/beam/analysis/PathTraversalSpatialTemporalTableGenerator.java
src/main/java/beam/analysis/plots/PersonTravelTimeAnalysis.java
src/main/java/beam/analysis/summary/NumberOfVehiclesAnalysis.java
src/main/java/beam/analysis/summary/PersonCostAnalysis.java
src/main/java/beam/analysis/via/ExpectedMaxUtilityHeatMap.java
src/main/java/beam/matsim/MatsimConfigUpdater.java
src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java
src/main/java/beam/physsim/jdeqsim/cacc/roadCapacityAdjustmentFunctions/Hao2018CaccRoadCapacityAdjustmentFunction.java
src/main/java/beam/router/r5/BeamDominatingList.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2689)

removed 30 warnings - final fields

---

src/main/scala/beam/sim/BeamWarmStart.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2673)

ensure warmstart works even without population

---

src/main/scala/beam/agentsim/agents/ridehail/allocation/PoolingAlonsoMora.scala

here is the fix suggested by @colinsheppard causing solo rides to replan
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2649)

ridehail fix

---

gradle/wrapper/gradle-wrapper.properties

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2685)

- Changing version to Gradle 5.0;

---

src/main/scala/beam/agentsim/infrastructure/taz/H3TAZ.scala
src/test/scala/beam/agentsim/infrastructure/taz/H3TAZSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2691)

make class usage uniform

---

test/input/sf-light/sf-light-10k-csv.conf
test/input/sf-light/sf-light-1k-csv.conf

Issue
https://github.com/LBNL-UCB-STI/beam/issues/2646
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2690)

Fixed config files (CSV as input)

---

src/main/scala/beam/utils/scenario/UrbanSimScenarioLoader.scala

Probabalistically adds vehicles to households with more workers than vehicles to bring up the total number of vehicles when beamScenario.beamConfig.beam.agentsim.agents.vehicles.fractionOfInitialVehicleFleet > 1.0
Something is off with the ratios, but does successfully upsample vehicles. Will look more closely ASAP but it will work in a pinch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2676)

Upsample household vehicles vehicles

---

src/main/java/beam/agentsim/agents/choice/logit/NestedLogit.java
src/main/java/beam/agentsim/agents/choice/logit/UtilityFunctionJava.java
src/main/java/beam/analysis/PathTraversalSpatialTemporalTableGenerator.java
src/main/java/beam/analysis/R5NetworkLink.java
src/main/java/beam/analysis/StatsFactory.java
src/main/java/beam/analysis/physsim/PhyssimCalcLinkSpeedDistributionStats.java
src/main/java/beam/analysis/physsim/PhyssimCalcLinkStats.java
src/main/java/beam/analysis/physsim/PhyssimNetworkComparisonEuclideanVsLengthAttribute.java
src/main/java/beam/analysis/physsim/PhyssimNetworkLinkLengthDistribution.java
src/main/java/beam/analysis/plots/GraphSurgePricing.java
src/main/java/beam/analysis/plots/GraphsStatsAgentSimEventsListener.java
src/main/java/beam/analysis/plots/ModeChosenAnalysis.java
src/main/java/beam/analysis/plots/PersonTravelTimeAnalysis.java
src/main/java/beam/analysis/plots/PersonVehicleTransitionAnalysis.java
src/main/java/beam/analysis/plots/RealizedModeAnalysis.java
src/main/java/beam/analysis/plots/RideHailRevenueAnalysis.java
src/main/java/beam/analysis/plots/RideHailWaitingAnalysis.java
src/main/java/beam/analysis/plots/RideHailWaitingTazAnalysis.java
src/main/java/beam/analysis/plots/passengerpertrip/TncPassengerPerTrip.java
src/main/java/beam/analysis/spatialtemporalTAZ/SpatialTemporalTAZVizDataWriter.java
src/main/java/beam/analysis/summary/PersonCostAnalysis.java
src/main/java/beam/analysis/summary/RideHailSummary.java
src/main/java/beam/analysis/summary/VehicleTravelTimeAnalysis.java
src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java
src/main/java/beam/physsim/jdeqsim/cacc/handler/EventCollector.java
src/main/java/beam/physsim/jdeqsim/cacc/sim/Road.java
src/main/java/beam/utils/LoggingUtil.java
src/main/java/beam/utils/TravelTimeCalculatorHelper.java
src/main/scala/beam/utils/mapsapi/hereapi/PolylineEncoderDecoder.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2697)

Removed 93 warnings

---

src/main/java/beam/analysis/StatsFactory.java
src/main/java/beam/analysis/plots/RealizedModeAnalysis.java
src/main/java/beam/analysis/plots/RealizedModesStatsComputation.java
src/test/java/beam/analysis/plots/RealizedModeGraphTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2705)
This tasks precedes the execution of the Issue https://github.com/LBNL-UCB-STI/beam/issues/2681
Contains 26 small improvements

Refactored RealizedModeAnalysis

---

src/main/scala/beam/agentsim/agents/household/HouseholdFleetManager.scala
src/main/scala/beam/sim/BeamSim.scala
src/main/scala/beam/sim/population/PopulationAdjustment.scala

https://github.com/LBNL-UCB-STI/beam/issues/2558
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2704)

Small logging improvement

---

src/main/java/beam/analysis/physsim/PhyssimCalcLinkStats.java
src/main/java/beam/analysis/plots/DeadHeadingAnalysis.java
src/main/java/beam/analysis/plots/FuelUsageAnalysis.java
src/main/java/beam/analysis/plots/ModeChosenAnalysis.java
src/main/java/beam/analysis/plots/RideHailWaitingAnalysis.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2712)

10 improvements - Refactoring

---

src/main/scala/beam/sim/BeamHelper.scala

Replaced the old CCH name with the new one: CCHRoutingAssignment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2714)

Fixed the old name of CCHRoutingAssignment physsim

---

production/sfbay/parking/taz_parking_plugs_0.3_power_150.csv
production/sfbay/parking/taz_parking_plugs_0.6_power_150.csv
production/sfbay/parking/taz_parking_plugs_0.9_power_150.csv

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2736)

add new parking files

---

src/main/scala/beam/agentsim/infrastructure/geozone/aggregation/ParkingEntriesReader.scala
src/main/scala/beam/agentsim/infrastructure/geozone/aggregation/TazCentersReader.scala
src/main/scala/beam/agentsim/infrastructure/taz/CsvTaz.scala
src/main/scala/beam/agentsim/infrastructure/taz/TAZTreeMap.scala
src/main/scala/beam/utils/matsim_conversion/MatsimConversionTool.scala
src/main/scala/beam/utils/matsim_conversion/ShapeUtils.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2734)
Issue: https://github.com/LBNL-UCB-STI/beam/issues/2602

[Issue 2602] Replace taz and parking readers with stronged type one and avoid duplication

---

src/main/scala/scripts/SortTests.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2746)

added sort tests possibility

---

src/main/java/beam/physsim/cchRoutingAssignment/RoutingFrameworkWrapper.scala

Use Unix path for all paths which are passed to Docker container
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2745)

BugFix: CCH on Windows machine fails

---

src/main/scala/beam/sim/RideHailFleetInitializer.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2752)
Issue: https://github.com/LBNL-UCB-STI/beam/issues/1854

write rideHailFleet file only once and at root folder

---

.gitignore
src/main/python/calibration/requirements.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2753)
Issue: https://github.com/LBNL-UCB-STI/beam/issues/2469

Make python call right version 4ci

---

src/main/java/beam/analysis/plots/RealizedModeAnalysis.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2758)

fixed typo on the graph name

---

.lfsconfig
src/main/scala/beam/utils/scenario/UrbanSimScenarioLoader.scala
src/test/scala/beam/utils/scenario/UrbanSimScenarioLoaderTest.scala
test/input/sf-light/urbansim-1k.conf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2738)

Write tests for UrbanSimScenarioLoader

---

src/main/scala/beam/physsim/jdeqsim/ApproxPhysSim.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2756)

BugFix: ApproxPhysSim passes wrong agent sim number

---

src/main/scala/beam/sim/RideHailFleetInitializer.scala

Reverts LBNL-UCB-STI/beam#2752
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2764)

Revert "write rideHailFleet file only once and at root folder"

---

src/main/scala/beam/agentsim/infrastructure/geozone/H3Index.scala
src/main/scala/beam/agentsim/infrastructure/geozone/TopDownEqualDemandSplitter.scala
src/test/scala/beam/agentsim/infrastructure/geozone/GeoZoneSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2763)

allowed method to set minimum resolution

---

src/test/scala/beam/integration/ParkingSpec.scala
test/input/beamville/parking/taz-parking-expensive-old.csv
test/input/beamville/parking/taz-parking-expensive.csv
test/input/beamville/parking/taz-parking-very-expensive.csv

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2767)
Issue: https://github.com/LBNL-UCB-STI/beam/issues/2008

fixed ParkingSpec flaky tests

---

src/main/scala/beam/agentsim/agents/household/HouseholdActor.scala
src/main/scala/beam/replanning/SupplementaryTripGenerator.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2760)

Fix agent sim for plans with one activity

---

src/main/scala/beam/sim/population/PercentagePopulationAdjustment.scala
src/main/scala/beam/sim/population/PopulationAdjustment.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2774)

fixed PopulationAdjustment to load attributes first

---

aws/src/main/python/beam_lambda/lambda_function.py
aws/src/main/python/runPilates/lambda_function.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2768)

Deploy lambda: Read GOOGLE_API_KEY from Lambda ENV

---

build.gradle
src/main/scala/beam/agentsim/infrastructure/ParallelParkingManager.scala
src/main/scala/beam/agentsim/scheduler/BeamAgentScheduler.scala
src/main/scala/beam/router/BeamRouter.scala
src/main/scala/beam/router/R5RoutingApp.scala
src/main/scala/beam/router/r5/R5RoutingWorker.scala
src/main/scala/beam/sim/BeamMobsim.scala
src/main/scala/beam/utils/mapsapi/googleapi/GoogleAdapter.scala
src/main/scala/beam/utils/mapsapi/hereapi/HereAdapter.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2775)

Bump to Akka 2.6.6 in prep for Akka Typed

---

src/main/scala/beam/router/LinkTravelTimeContainer.scala
src/main/scala/beam/router/R5RoutingApp.scala
src/main/scala/beam/sim/BeamWarmStart.scala
test/input/beamville/beam.conf

Issue: https://github.com/LBNL-UCB-STI/beam/issues/2001
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2780)

Make Warmstart singleton for same configuration and avoid multiple downloads

---

src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2803)

fix NPE if writeInterval is 0

---

src/main/scala/beam/scoring/BeamScoringFunctionFactory.scala

- Mark `BeamScoringFunctionFactory` as `Singleton` so only one instance will exist
- Moved global state to the class field(s)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2836)

Remove global state from BeamScoringFunctionFactory 

---

build.gradle
src/test/scala/beam/agentsim/infrastructure/ParallelParkingManagerSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2839)

MATSim: Update to `0.10.1-beam-15`

---

src/main/scala/beam/agentsim/agents/vehicles/EventsAccumulator.scala
src/main/scala/beam/cosim/helics/BeamFederate.scala
src/main/scala/beam/sim/BeamMobsim.scala
src/test/scala/beam/cosim/helics/BeamFederateSpec.scala

- Load Helics only once
- Release helics library in the end
- Make sure there were some number of chargingPlugIn/PlugOut events
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2832)

Load Helics only once

---

src/main/scala/beam/utils/beam_to_matsim/EventsByVehicleMode.scala
src/main/scala/beam/utils/beam_to_matsim/utils/FindIdsInCircles.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2840)

fix for 'object XML is not a member of package xml'

---

src/main/java/beam/analysis/plots/filterevent/ActivitySimFilterEvent.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2842)

Use only activities from the plan elements

---

build.gradle

They removed the deprecated API in Akka 2.6, see https://doc.akka.io/docs/akka/current/project/migration-guide-2.5.x-2.6.x.html
We need to update Akka-http in order to avoid NoClassDefFoundError and similar.
Uncaught error from thread [ClusterSystem-akka.actor.default-dispatcher-42]: java.lang.NoClassDefFoundError: akka/stream/actor/ActorSubscriber, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[ClusterSystem]
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: akka/stream/actor/ActorSubscriber
at akka.http.impl.engine.client.PoolInterfaceActor$.props(PoolInterfaceActor.scala:34)
at akka.http.impl.engine.client.PoolMasterActor.akka$http$impl$engine$client$PoolMasterActor$$startPoolInterfaceActor(PoolMasterActor.scala:54)
at …

Updated Akka-http version to 10.1.10

---

src/main/resources/beam-template.conf
src/main/scala/beam/sim/BeamHelper.scala
src/main/scala/beam/sim/config/BeamConfig.scala
src/main/scala/beam/sim/config/ConfigHelper.scala

@REASY can we move this `writeFullConfigs` method in ConfigConsistencyCheck class because all config related task we are doing in this class?
Resolves #2735
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2766)

run beam with default results

---

src/main/scala/beam/utils/FileUtils.scala
src/main/scala/beam/utils/GTFSToShape.scala
src/main/scala/beam/utils/csv/GenericCsvReader.scala
src/main/scala/beam/utils/gtfs/GTFSReader.scala
src/main/scala/beam/utils/gtfs/GTFSToShape.scala
src/main/scala/beam/utils/gtfs/Model.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2819)

A tool to get a shape file out of stops coordinates from GTFS archive

---

src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2875)

BugFix: fix for RideHailManager for scenario with people with only home activity

---

src/main/resources/beam-template.conf
src/main/scala/beam/agentsim/events/handling/TravelTimeGoogleStatistic.scala
src/main/scala/beam/sim/config/BeamConfig.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2877)

TravelTimeGoogleStatistic: flag to control whether to query off-peak routes

---

src/main/scala/beam/agentsim/events/handling/TravelTimeGoogleStatistic.scala
src/main/scala/beam/utils/mapsapi/googleapi/GoogleAdapter.scala
src/main/scala/beam/utils/mapsapi/googleapi/Route.scala

Added `duration_in_traffic` to Google stats
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2878)

TravelTimeGoogleStatistic: Add duration_in_traffic to the output stats

---

src/main/resources/beam-template.conf
src/main/scala/beam/sim/config/BeamConfig.scala
src/main/scala/beam/sim/population/PopulationAdjustment.scala

Might reduce number of unrealistically long walk trips
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2912)

set config for minimum VOT (default to federal minimum wage)

---

src/main/scala/beam/agentsim/infrastructure/ParkingManagerBenchmark.scala
src/main/scala/beam/agentsim/infrastructure/ZonalParkingManager.scala
src/main/scala/beam/replanning/SupplementaryTripGenerator.scala
src/main/scala/beam/sim/BeamMobsim.scala
src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala
src/test/scala/beam/agentsim/agents/PersonAndTransitDriverSpec.scala
src/test/scala/beam/agentsim/agents/RideHailAgentSpec.scala

Only worth pursuing if it reduces the long walk trips in NYC
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2911)

Snap parking stalls and secondary activities to r5 network

---

src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceMultinomialLogit.scala
src/main/scala/beam/agentsim/infrastructure/NetworkUtilsExtensions.scala
src/main/scala/beam/router/r5/BikeLanesAdjustment.scala
src/main/scala/beam/router/r5/BikeLanesData.scala
src/main/scala/beam/router/r5/R5Wrapper.scala
src/main/scala/beam/sim/BeamHelper.scala
src/test/scala/beam/router/r5/BikeLaneAdjustmentSpec.scala
src/test/scala/beam/utils/FixtureUtils.scala
src/test/scala/beam/utils/TestConfigUtils.scala

Closes #2922 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2925)

added tests for BikeLanesAdjustment

---

src/main/scala/beam/replanning/SupplementaryTripGenerator.scala

Hopefully this fixes the problem with disappearing work activities
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2936)

fix bug in secondary activities

---

src/test/scala/beam/agentsim/agents/GenericEventsSpec.scala
src/test/scala/beam/analysis/plots/PersonCostAnalysisSpec.scala
src/test/scala/beam/integration/IntegrationSpecCommon.scala
test/input/beamville/multipleTolls-prices.csv

Closes #2933 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2948)

fixed flaky PersonConstAnalysisSpec test

---

src/main/scala/beam/agentsim/agents/vehicles/EventsAccumulator.scala
src/test/scala/beam/cosim/helics/BeamFederateSpec.scala
test/input/beamville/vehicleTypesForMoreFrequentCharges.csv

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2934)

Fix flaky tests

---

src/main/java/beam/agentsim/events/ModeChoiceEvent.java
src/main/java/beam/analysis/physsim/PhyssimCalcLinkSpeedDistributionStats.java
src/main/java/beam/analysis/plots/RealizedModeAnalysis.java
src/main/java/beam/analysis/summary/PersonCostAnalysis.java
src/main/java/beam/router/r5/R5MnetBuilder.java
src/main/scala/beam/physsim/bprsim/ConcurrentPriorityQueue.scala
src/main/scala/beam/physsim/bprsim/Coordinator.scala
src/main/scala/beam/physsim/bprsim/SimEvent.scala
src/main/scala/beam/physsim/jdeqsim/JDEQSimRunner.scala
src/main/scala/beam/router/RoutingWorker.scala
src/main/scala/beam/router/graphhopper/GraphHopperWrapper.scala
src/main/scala/beam/router/skim/TransitCrowdingSkimmer.scala
src/main/scala/beam/router/skim/TransitCrowdingSkimmerEvent.scala
src/main/scala/beam/sim/BeamScenario.scala
src/main/scala/beam/sim/BeamServices.scala
src/main/scala/beam/utils/MathUtils.scala
src/main/scala/beam/utils/TravelTimeGoogleApp.scala
src/main/scala/beam/utils/data/ctpp/readers/residence/TotalPopulationTableReader.scala
src/main/scala/beam/utils/json/AllNeededFormats.scala
src/main/scala/beam/utils/mapsapi/googleapi/GoogleAdapter.scala
src/main/scala/beam/utils/scenario/urbansim/censusblock/UrbansimConverter.scala
src/test/scala/beam/integration/EventsFileSpec.scala
src/test/scala/beam/physsim/bprsim/PhysSimulationSpec.scala
src/test/scala/beam/physsim/bprsim/VolumeCalculatorSpec.scala
src/test/scala/beam/router/R5IssueVisitingTooManySpatialIndexCells.scala
src/test/scala/beam/utils/FileUtilsSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2952)

Warnings removed

---

src/main/scala/beam/router/skim/ODSkimmer.scala
src/main/scala/beam/router/skim/TransitCrowdingSkimmerEvent.scala
src/test/scala/beam/cosim/helics/BeamFederateSpec.scala
src/test/scala/beam/physsim/bprsim/PhysSimulationSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2956)

Fixed issue with casting a tuple to a skimmer key in ODSkimmer

---

src/main/scala/beam/agentsim/infrastructure/ParkingManagerBenchmark.scala
src/main/scala/beam/agentsim/infrastructure/ZonalParkingManager.scala
src/main/scala/beam/replanning/SupplementaryTripGenerator.scala
src/main/scala/beam/sim/BeamMobsim.scala
src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala
src/test/scala/beam/agentsim/agents/PersonAndTransitDriverSpec.scala
src/test/scala/beam/agentsim/agents/RideHailAgentSpec.scala

because of changes from following PR https://github.com/LBNL-UCB-STI/beam/pull/2911 increases beam execution time about 3 times.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2935)

Revert snap to r5 pr

---

src/main/scala/beam/analysis/ActivityTypeAnalysis.scala

Closes #2921 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2930)

write activity type csv in root and iteration directory

---

src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala
src/main/scala/beam/router/r5/R5Wrapper.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2940)

R5Router: Fix bush walking trip

---

src/main/scala/beam/router/RoutingWorker.scala
src/main/scala/beam/router/graphhopper/AbstractBeamTimeDetails.scala
src/main/scala/beam/router/graphhopper/BeamPathDetailsBuilderFactory.scala
src/main/scala/beam/router/graphhopper/BeamTimeDetails.scala
src/main/scala/beam/router/graphhopper/BeamTimeReverseDetails.scala
src/main/scala/beam/router/graphhopper/BeamWeighting.scala
src/main/scala/beam/router/graphhopper/GraphHopperWrapper.scala
src/main/scala/beam/router/model/BeamPath.scala
test/input/texas/austin-prod-200k.conf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2916)

Call R5 when GH return empty response. Fixed quasiGh.

---

src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceMultinomialLogit.scala
src/test/scala/beam/agentsim/agents/choice/mode/ModeChoiceMultinomialLogitSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2938)

added tests to ModeChoiceMultinomialLogit

---

src/main/scala/beam/router/skim/TransitCrowdingSkimmerEvent.scala
src/test/scala/beam/cosim/helics/BeamFederateSpec.scala
src/test/scala/beam/physsim/bprsim/PhysSimulationSpec.scala

Closes #2830
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2953)

add extra requirement to test for transient issues

---

src/test/scala/beam/cosim/helics/BeamFederateSpec.scala
src/test/scala/beam/sim/SecondaryActivitiesSpec.scala
test/test-resources/beam/agentsim/activities/activity-intercepts-0.csv
test/test-resources/beam/agentsim/activities/activity-intercepts-high.csv
test/test-resources/beam/agentsim/activities/activity-intercepts.csv
test/test-resources/beam/agentsim/activities/activity-params.csv

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2879)

Add secondary activities test cases

---

src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala
src/main/scala/beam/router/RoutingWorker.scala
src/main/scala/beam/router/graphhopper/GraphHopperWrapper.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2975)

get transit from available modes

---

src/main/java/beam/analysis/StatsFactory.java
src/main/scala/beam/agentsim/agents/household/FastHouseholdCAVScheduling.scala
src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala
src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailAgent.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
src/main/scala/beam/agentsim/agents/ridehail/allocation/Pooling.scala
src/main/scala/beam/agentsim/agents/ridehail/allocation/PoolingAlonsoMora.scala
src/main/scala/beam/analysis/RoutingRequestAnalysis.scala
src/main/scala/beam/physsim/jdeqsim/ReRouter.scala
src/main/scala/beam/router/BeamRouter.scala
src/main/scala/beam/router/R5Requester.scala
src/main/scala/beam/router/R5RoutingApp.scala
src/main/scala/beam/utils/json/AllNeededFormats.scala
src/test/scala/beam/agentsim/agents/PersonWithVehicleSharingSpec.scala
src/test/scala/beam/router/TimeDependentRoutingSpec.scala
src/test/scala/beam/router/TollRoutingSpec.scala

Closes #2941 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2960)

connect mode choice with routing request ids

---

src/main/java/beam/agentsim/events/handling/BeamEventsLogger.java
src/main/java/beam/agentsim/events/handling/BeamEventsLoggingSettings.java
src/main/java/beam/agentsim/events/handling/BeamEventsWriterBase.java
src/main/java/beam/agentsim/events/handling/BeamEventsWriterCSV.java
src/main/resources/beam-template.conf
src/main/scala/beam/analysis/RealizedModeChoiceWriter.scala
src/main/scala/beam/sim/BeamSim.scala
src/main/scala/beam/sim/config/BeamConfig.scala

Resolves #2814 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2978)

#2814 RealizedModeChoiceWriter

---

build.gradle
src/main/scala/beam/agentsim/agents/PersonAgent.scala
src/main/scala/beam/agentsim/agents/household/HouseholdSolverActor.scala
src/main/scala/beam/agentsim/agents/parking/ChoosesParking.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
src/main/scala/beam/agentsim/infrastructure/ZonalParkingManager.scala
src/main/scala/beam/agentsim/infrastructure/parking/ParkingMNL.scala
src/main/scala/beam/agentsim/infrastructure/taz/H3TAZ.scala
src/main/scala/beam/physsim/jdeqsim/PhysSimReplayer.scala
src/main/scala/beam/replanning/utilitybased/ChainBasedTourVehicleAllocator.scala
src/main/scala/beam/router/BeamRouter.scala
src/main/scala/beam/router/RoutingWorker.scala
src/main/scala/beam/sim/BeamHelper.scala
src/main/scala/beam/sim/BeamSim.scala
src/main/scala/beam/utils/GpxCompareSimulationVsReference.scala
src/main/scala/beam/utils/beam_to_matsim/EventsByVehicleMode.scala
src/main/scala/beam/utils/data/synthpop/FlowStatsForParking.scala
src/main/scala/beam/utils/map/GpxWriter.scala
src/main/scala/beam/utils/map/R5MapStatsCalculator.scala
src/main/scala/beam/utils/matsim_conversion/MatsimConversionTool.scala
src/main/scala/beam/utils/scenario/urbansim/UrbanSimScenarioSource.scala
src/main/scala/beam/utils/watcher/MethodWatcher.scala
src/main/scala/json/converter/NyuDataTazConverter.scala
src/main/scala/json/converter/SfGovTazConverter.scala

add flag `report` in compile command to run plugin
`./gradlew compileScala -Preport`
Resolves #2947
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2983)

Add scapegoat plugin

---

build.gradle
src/main/scala/beam/agentsim/agents/choice/logit/MultinomialLogit.scala
src/main/scala/beam/agentsim/agents/choice/mode/RideHailDefaults.scala
src/main/scala/beam/agentsim/agents/choice/mode/TransitFareDefaults.scala
src/main/scala/beam/agentsim/agents/household/FastHouseholdCAVScheduling.scala
src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailDebugEventHandler.scala
src/main/scala/beam/agentsim/agents/ridehail/RideHailSurgePricingManager.scala
src/main/scala/beam/agentsim/agents/ridehail/TNCIterationStats.scala
src/main/scala/beam/agentsim/agents/ridehail/allocation/RandomRepositioning.scala
src/main/scala/beam/analysis/cartraveltime/models.scala
src/main/scala/beam/physsim/bprsim/Coordinator.scala
src/main/scala/beam/router/r5/R5Wrapper.scala
src/main/scala/beam/sim/BeamHelper.scala
src/main/scala/beam/utils/ActivitySegment.scala
src/main/scala/beam/utils/MathUtils.scala
src/main/scala/beam/utils/RespositioingValidation.scala
src/main/scala/beam/utils/data/ctpp/readers/flow/HouseholdIncomeTableReader.scala
src/main/scala/beam/utils/data/ctpp/readers/flow/TimeLeavingHomeTableReader.scala
src/main/scala/beam/utils/data/ctpp/readers/flow/TravelTimeTableReader.scala
src/main/scala/beam/utils/map/GeoFenceVerifier.scala
src/main/scala/beam/utils/scenario/urbansim/censusblock/ScenarioAdjuster.scala

Closes https://github.com/LBNL-UCB-STI/beam/issues/2990
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2994)

Removed 30 Scapegoat Errors related to ComparingFloatingPointTypes

---

src/main/scala/beam/agentsim/agents/choice/mode/TransitFareDefaults.scala
src/main/scala/beam/calibration/impl/example/ModeChoiceObjectiveFunction.scala
src/main/scala/beam/router/BeamRouter.scala
src/main/scala/beam/router/r5/NetworkCoordinator.scala
src/main/scala/beam/router/r5/R5Wrapper.scala
src/main/scala/beam/router/skim/CsvSkimReader.scala
src/main/scala/beam/sim/BeamSim.scala
src/main/scala/beam/utils/data/ctpp/models/FlowGeoParser.scala
src/main/scala/beam/utils/data/ctpp/readers/flow/AgeOfWorkerTableReader.scala
src/main/scala/beam/utils/data/ctpp/readers/flow/HouseholdIncomeTableReader.scala
src/main/scala/beam/utils/data/ctpp/readers/flow/IndustryTableReader.scala
src/main/scala/beam/utils/data/ctpp/readers/flow/MeansOfTransportationTableReader.scala
src/main/scala/beam/utils/data/ctpp/readers/flow/TimeLeavingHomeTableReader.scala
src/main/scala/beam/utils/data/ctpp/readers/flow/TravelTimeTableReader.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2992)

Fix TryGet and EitherGet error

---

aws/src/main/python/s3BucketHandler/lambda_function.py
aws/src/main/python/s3BucketHandler/s3BucketHandler.yaml

Resolves #2986 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3026)

Added lambda funcation and configurations for checking bucket size

---

src/main/scala/beam/agentsim/agents/BeamAgent.scala
src/main/scala/beam/agentsim/agents/choice/logit/MultinomialLogit.scala
src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala
src/main/scala/beam/agentsim/infrastructure/ParkingInquiry.scala
src/main/scala/beam/agentsim/infrastructure/ParkingSearchFilterPredicates.scala
src/main/scala/beam/agentsim/infrastructure/ZonalParkingManager.scala
src/main/scala/beam/analysis/DelayMetricAnalysis.scala
src/main/scala/beam/router/RoutingWorker.scala
src/main/scala/beam/router/graphhopper/BeamGraphHopper.scala
src/main/scala/beam/router/graphhopper/GraphHopperWrapper.scala
src/main/scala/beam/router/r5/R5Parameters.scala
src/main/scala/beam/sim/BeamHelper.scala
src/main/scala/beam/sim/BeamServices.scala
src/main/scala/beam/sim/LoggingEventsManager.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3037)

GH walk mode. Parallel event manager. Perfomance fixes.

---

src/main/java/beam/physsim/jdeqsim/cacc/roadcapacityadjustmentfunctions/Hao2018CaccRoadCapacityAdjustmentFunction.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3036)

Optimization of Hao2018CaccRoadCapacityAdjustmentFunction.printStats

---

src/main/scala/beam/agentsim/agents/ridehail/allocation/RideHailResourceAllocationManager.scala
src/main/scala/beam/sim/BeamSim.scala
src/test/scala/beam/agentsim/agents/PersonWithPersonalVehiclePlanSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3040)

Using RideHailIterationsStatsCollector only if RepositioningManager is REPOSITIONING_LOW_WAITING_TIMES

---

aws/build.gradle
aws/src/main/python/s3BucketList/lambda_function.py
aws/src/main/python/s3BucketList/s3BucketList.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3030)

AWS bucket listing

---

src/main/scala/beam/utils/csv/readers/BeamCsvScenarioReader.scala
src/main/scala/beam/utils/geospatial/PolygonUtil.scala
src/main/scala/beam/utils/scenario/urbansim/CsvScenarioReader.scala
src/main/scala/beam/utils/scenario/urbansim/DataExchange.scala
src/main/scala/beam/utils/scenario/urbansim/ParquetScenarioReader.scala
src/main/scala/beam/utils/scenario/urbansim/UrbanSimScenarioSource.scala
src/main/scala/beam/utils/scenario/urbansim/censusblock/entities/PersonInfo.scala
src/main/scala/beam/utils/scenario/urbansim/censusblock/merger/PersonMerger.scala
src/test/scala/beam/utils/scenario/urbansim/ParquetScenarioReaderTest.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3048)

#3035 - Fixed passing of industry to all PersonInfo instances

---

src/main/scala/beam/sim/population/PopulationAdjustment.scala
src/main/scala/beam/utils/geospatial/PolygonUtil.scala
src/test/scala/beam/sim/population/PopulationAdjustmentSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3049)

#3014 Fixed log modes for case when excluded modes are configured as a sequence/array instead of string coma separated

---

src/main/resources/beam-template.conf
src/main/scala/beam/sim/config/BeamConfig.scala
src/main/scala/beam/sim/modules/BeamAgentModule.scala
src/test/scala/beam/agentsim/agents/ridehail/MatchingAlgorithmsForRideHailSpec.scala
src/test/scala/beam/agentsim/infrastructure/taz/H3TAZSpec.scala
src/test/scala/beam/cosim/helics/BeamFederateSpec.scala
src/test/scala/beam/integration/CAVSpec.scala
src/test/scala/beam/integration/CarSharingSpec.scala
src/test/scala/beam/replanning/ModeIterationPlanCleanerSpec.scala
src/test/scala/beam/router/GHRouterSpec.scala
src/test/scala/beam/router/skim/SkimmerSpec.scala
src/test/scala/beam/sflight/BeamIncentiveSpec.scala
src/test/scala/beam/sflight/CaccSpec.scala
src/test/scala/beam/sflight/SfLightRunSpec.scala
src/test/scala/beam/utils/TestConfigUtils.scala

Closes #2976 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3044)

[Issue-2976] Added actorSystemName to beam-template-config

---

src/main/java/beam/utils/DebugLib.java
src/main/scala/beam/physsim/bprsim/Coordinator.scala
src/main/scala/beam/physsim/jdeqsim/JDEQSimRunner.scala
src/main/scala/beam/physsim/jdeqsim/PhysSimEventWriter.scala
src/main/scala/beam/utils/ConcurrentUtils.scala

Do in parallel as much operations as possible in physsim runner
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3053)

ParallelEventsManagerImpl in physsim

---

src/main/scala/beam/replanning/ReplanningUtil.scala

While creating new plan elements we were using matsim mode. Now we have change this with beam mode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3060)

Fix others and transit_walk in test

---

src/main/scala/beam/router/RoutingWorker.scala
src/main/scala/beam/router/graphhopper/BeamGraphHopper.scala
src/main/scala/beam/router/graphhopper/BeamWeighting.scala
src/main/scala/beam/router/graphhopper/CarGraphHopperWrapper.scala
src/main/scala/beam/router/graphhopper/GraphHopperWrapper.scala
src/main/scala/beam/router/graphhopper/WalkGraphHopperWrapper.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3055)

rebuild only car gh

---

build.gradle
src/main/scala/beam/utils/mapsapi/RichSegments.scala
src/main/scala/beam/utils/mapsapi/Segment.scala
src/main/scala/beam/utils/mapsapi/SegmentSerializer.scala
src/main/scala/beam/utils/mapsapi/hereapi/HereService.scala

Closes #3058 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3059)

[Issue-3058] Update akka http version and fix here adapter 4ci

---

src/main/scala/beam/utils/ConfigAnalysis.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3065)

compare beam template with existing config

---

src/main/scala/beam/utils/mapsapi/bingapi/BingAdapter.scala
src/main/scala/beam/utils/mapsapi/bingapi/BingExampleOfUsage.scala
src/main/scala/beam/utils/mapsapi/bingapi/SnappedPoint.scala

Closes https://github.com/LBNL-UCB-STI/beam/issues/3068
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3072)

Added BingApi - SnapToRoute

---

.dockerignore
build.gradle
docker/entrypoint.sh
docs/developers.rst
src/main/scala/beam/sim/BeamHelper.scala
src/main/scala/beam/sim/RunBeam.scala
src/main/scala/beam/utils/MathUtils.scala

Uses `docker-java-application` plugin for Gradle to create docker image
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3063)

Beam in Docker

---

src/main/scala/beam/router/graphhopper/BeamPathDetailsBuilderFactory.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3087)

Fix gh path details

---

aws/src/main/python/cloudwatchAllInstances/lambda_function.py
aws/src/main/python/idleNotifier/idleNotifier.yaml
aws/src/main/python/idleNotifier/lambda_function.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3088)

Tweak lambdas

---

src/main/scala/beam/router/graphhopper/WalkGraphHopperWrapper.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3112)

Fix gh walk mode

---

aws/build.gradle
aws/src/main/python/beam_lambda/lambda_function.py
build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3100)

add profiler

---

src/main/scala/beam/utils/csv/writers/HouseholdsCsvWriter.scala
src/main/scala/beam/utils/csv/writers/PlansCsvWriter.scala
src/main/scala/beam/utils/csv/writers/PopulationCsvWriter.scala
src/main/scala/beam/utils/scenario/BeamScenarioLoader.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3126)

Fix output simulation files

---

production/sfbay/toll-prices.csv

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3111)

updated sf-bay toll data

---

build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3129)

BugFix: Align type and remove null in build.gradle

---

aws/src/main/python/beam_lambda/lambda_function.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3127)

Sync up with latest used lambda

---

src/main/scala/beam/router/RoutingWorker.scala
src/main/scala/beam/router/r5/CarWeightCalculator.scala
src/main/scala/beam/router/r5/R5Wrapper.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3114)

New weights for GH

---

src/main/scala/beam/utils/FileUtils.scala
test/input/beamville/beam.conf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3085)

add secure download from s3

---

src/main/scala/beam/router/skim/core/DriveTimeSkimmer.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3137)

to prevent java.lang.IllegalArgumentException: Null or zero length 'values' argument.

---

src/main/resources/beam-template.conf
src/main/scala/beam/agentsim/infrastructure/ZonalParkingManager.scala
src/main/scala/beam/sim/config/BeamConfig.scala
src/test/scala/beam/agentsim/infrastructure/ZonalParkingManagerSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3140)

this will fix human ridehail access to charging

---

build.gradle
src/main/scala/beam/analysis/AnalysisProcessor.scala
src/main/scala/beam/analysis/carridestats/CarRideStatsAdapter.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3148)

Remove python2

---

build.gradle
src/main/scala/beam/agentsim/agents/PersonAgent.scala
src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3162)

Prep for bintray

---

src/main/scala/beam/agentsim/agents/ridehail/RideHailManagerHelper.scala
src/main/scala/beam/agentsim/agents/ridehail/allocation/Pooling.scala

There is no algorithm change. This PR only encapsulated some properties and used IDE tool to extract methods and variables
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3167)

[issue-3164] Refactored code to make possible test

---

build.gradle
src/main/scala/scripts/s3wrapper/S3Wrapper.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3187)

Fix test run issue with AWS dependency

---

build.gradle

Closes #3180 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3191)

Multiple libraries upgrade

---

src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala
src/test/scala/scripts/s3wrapper/S3WrapperTest.scala

Closes #3194 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3195)

Fix object comparison bug

---

src/main/scala/beam/sim/vehiclesharing/Fleet.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3205)

Fixed misleading error text

---

build.gradle
src/main/scala/beam/calibration/BeamSigoptTuner.scala
src/main/scala/beam/router/r5/RouteDumper.scala
src/main/scala/beam/sim/BeamMobsim.scala
src/main/scala/beam/utils/data/ctpp/JointDistribution.scala
src/main/scala/beam/utils/shape/GenericFeatureBuilder.scala
src/main/scala/beam/utils/shape/ShapeWriter.scala

Closes #2991
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3202)

Fixed messages for ComparingUnrelatedTypes

---

src/main/scala/beam/router/skim/ActivitySimPathType.scala
src/main/scala/beam/router/skim/urbansim/WorkerActor.scala

After merging #2718 there were two errors which scapegoat found on newly merged new code. I should have first update that PR from the latest develop to avoid this to happen.
This PR should fix these errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3212)

Fix scapegoat errors after merging

---

src/main/scala/beam/utils/map/R5MapStatsCalculator.scala

utility script to calculate parameters for overwriteRoadTypeProperties based on OSM map link analysis
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3204)

Util: calculation of parameters for overwriteRoadTypeProperties config value

---

src/main/resources/beam-template.conf
src/main/scala/beam/sim/config/BeamConfig.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3216)

change default listing differences to comments - remove warning

---

src/main/scala/beam/utils/scenario/urbansim/censusblock/entities/Block.scala
src/main/scala/beam/utils/scenario/urbansim/censusblock/merger/HouseholdMerger.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3219)

Urbansim scenario reader: fix for whitespaces in block ids

---

build.gradle

Before:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3223)

Add more memory to Scala compiler, should fix build GC issues

---

src/main/scala/beam/utils/scenario/urbansim/censusblock/entities/Block.scala
src/main/scala/beam/utils/scenario/urbansim/censusblock/entities/InputHousehold.scala
src/main/scala/beam/utils/scenario/urbansim/censusblock/merger/HouseholdMerger.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3222)

setting blockId to Long because in input data there is a leading zero in id field

---

src/main/resources/beam-template.conf
src/main/scala/beam/sim/BeamHelper.scala
src/main/scala/beam/sim/config/BeamConfig.scala
src/main/scala/beam/utils/BeamConfigUtils.scala
src/main/scala/beam/utils/scenario/urbansim/censusblock/UrbansimConverter.scala
src/main/scala/beam/utils/scenario/urbansim/censusblock/UrbansimReaderV2.scala
src/main/scala/beam/utils/scenario/urbansim/censusblock/merger/PlanMerger.scala
test/input/texas/austin-prod-200k.conf
test/input/texas/austin-prod-200k_cch.conf
test/input/texas/austin-prod-200k_second.conf

One  must set beam.exchange.scenario.modeMap parameter when they use urbansim_v2 scenario
Resolves #3218
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3221)

Urbansim mode mapping from config

---

build.gradle
src/main/resources/beam-template.conf
src/main/scala/beam/sim/config/BeamConfig.scala
src/main/scala/beam/sim/vehiclesharing/Fleet.scala
src/test/scala/beam/router/skim/urbansim/BackgroundSkimsCreatorTest.scala

This allows the users to have better understanding of the errors happens during usage of shared vehicle scenarios.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3214)

Validate type id for shared vehicles. Require it to start with "sharedVehicle" instead of adding it silently.

---

src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala
src/main/scala/beam/agentsim/infrastructure/ZonalParkingManager.scala
src/main/scala/beam/utils/csv/CsvWriter.scala
test/input/sf-light/parking/shared-bike-parking-hubs-test.csv

These fixes allows shared vehicles to park only on their dedicated parking stalls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3224)

Fixes of shared vehicle parking

---

src/main/scala/beam/router/skim/urbansim/BackgroundSkimsCreatorApp.scala

Fix `BackgroundSkimsCreatorApp` timeout issue on NERSC
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3241)

Fix timeout

---

src/main/scala/beam/router/TravelTimeAndDistanceCalculatorApp.scala
src/main/scala/beam/utils/shape/FilterPointsInShapeFile.scala

This is a small tool that, probably, never won't be used as is.
I have caught myself writing almost the same script third time, so, here it is.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3242)

A script to filter points by shapefile

---

build.gradle

Using mainClass property of JavaExec task
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3245)

Gradle execute task fix

---

src/jmh/scala/beam/agentsim/infrastructure/GeometryPerformance.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3252)

fixing loading parking zones

---

src/main/scala/beam/agentsim/infrastructure/ChargingNetwork.scala
src/main/scala/beam/agentsim/infrastructure/ChargingNetworkManager.scala
src/test/scala/beam/agentsim/infrastructure/ChargingNetworkManagerSpec.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3253)

fix Stuckness In Develop Due To RH Refactoring PR

---

src/main/java/beam/analysis/plots/GraphUtils.java
src/main/scala/beam/analysis/cartraveltime/CarTripStatsFromPathTraversalEventHandler.scala

**Old picture:**
**New picture:**
Also fixed the legend items order to be consistent - added sorting for car types.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3260)

Fix averageCarSpeed color switching

---

src/main/scala/beam/utils/ConfigValuesComparator.scala

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3266)

Util to compare values of two config files
