- src/main/scala/beam/agentsim/scheduler/BeamAgentScheduler.scala
- src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala
- src/test/scala/beam/sim/BeamAgentSchedulerSpec.scala
Now the single-threaded test works without hanging, and can replace the regular one.
> Replace blocking 'sleep' with non-blocking scheduling an Akka event.

- src/main/java/beam/agentsim/agents/choice/logit/DiscreteProbabilityDistribution.java
- src/main/java/beam/agentsim/agents/choice/logit/NestedLogit.java
Techniques applied for refactoring:
- Extracted method: getScalingFactor, updateCumulativeProbabilityAndReturnLastKey
- Extracted constant: PRECISION (repeated in the code)
- Minor formatting issues
- `this` keyword redudancy:
it is a common doubt when and when should not use `this` keyword. 
I suggest using it only when there is a name collision. this way we can have a common standard in the whole team
Improvement: make the code cleaner and resolve ambiguity rule
- Performance improvement
```Java
for (String key : this.pdf.keySet()){
double theProb = Double.isInfinite(this.pdf.get(key)) 
? 1.0 
: this.pdf.get(key) / scalingFactor;
```
Problem: Traversing keySet and getting the value twice
Replaced by
```Java
for (Map.Entry<String, Double> entry : pdf.entrySet()) {
final String key = …
```
> Refactored file DiscreteProbabilityDistribution

- src/main/scala/beam/agentsim/agents/rideHail/RideHailingManager.scala
In `getClosestIdleRideHailingAgent` method we use only one element - so we don't really need to sort `distances2RideHailingAgents` - it's faster and less GC pressure(`sortBy` allocates new collection)
> RideHailingManager: Optimized get closest idle ride hailing agent

- README.md
- src/main/scala/beam/agentsim/agents/vehicles/PassengerSchedule.scala
- src/main/scala/beam/agentsim/scheduler/BeamAgentScheduler.scala
Also, remove the Tuple2 creation, used only for comparison purposes
This is pending a full test, but otherwise preliminary findings found a 33% reduction in memory footprint when used against sf-light.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/313)
> Reduce memory allocation by using static compare

- src/main/java/beam/agentsim/events/handling/BeamEventsFileFormats.java
- src/main/java/beam/agentsim/events/handling/BeamEventsLogger.java
- src/main/java/beam/agentsim/events/handling/BeamEventsWriterCSV.java
- src/main/java/beam/agentsim/events/handling/BeamEventsWriterXML.java
What changed:
- Improved cohesion: moved the suffix files to the Enumeration `BeamEventsFileFormats`
- Extract method: large method broken down
- Extract variable: avoided multiple calls to the same method
- Demeter law adapted: `beamServices.beamConfig().beam().outputs().events()`
- SOLID Decoupling improved: concrete classes replaced by interfaces
- Readability: some simplifications
- Premature declaration removed: variables with unused value due to intermediate conditions
- Removed warnings: Unchecked type and others
- Small performance gains: usage of `Map.containsKey` followed by `Map.get` and others
- Fixed encapsulation issues: tightened visibility
- Conventions: renamed enumeration and variables to follow conventions
- Others: string first in literal comparison, limit line size, …
> BeamEventsLogger clean up - iteration 1

- src/main/scala/beam/agentsim/agents/ridehail/RideHailModifyPassengerScheduleManager.scala
- src/main/scala/beam/agentsim/agents/ridehail/allocation/EVFleetAllocationManager.scala
- src/main/scala/beam/agentsim/agents/ridehail/allocation/ImmediateDispatchWithOverwrite.scala
- src/main/scala/beam/agentsim/agents/ridehail/allocation/RideHailResourceAllocationManager.scala
Use `getClosestIdleRideHailAgent` instead of `getClosestIdleVehiclesWithinRadius` because **only head element** is consumed
Use lazy logging instead of strict one:
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/497)
> Project: Use getClosestIdleRideHailAgent instead of getClosestIdleVehiclesWithinRadius

- src/main/scala/beam/router/r5/R5RoutingWorker.scala
[NoSuchElementException](https://docs.oracle.com/javase/7/docs/api/java/util/NoSuchElementException.html) are thrown in https://github.com/LBNL-UCB-STI/beam/blob/master/src/main/scala/beam/router/r5/R5RoutingWorker.scala#L73
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/535)
> R5RoutingWorker: Use `onComplete` to not to throw `NoSuchElementException`

- src/main/java/beam/analysis/plots/RideHailWaitingStats.java
non rideHail vehicle ids were coming due do introducing of another modechoice event because of replanning event
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/578)
> remove non rideHail vehicle ids from rideHailIndividualWaiting file

- src/main/java/beam/analysis/plots/PersonTravelTimeStats.java
fix all average travel time graphs and created a new graph for others category
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/586)
> fix all average travel time graphs and create new graph for others

- src/main/scala/beam/agentsim/infrastructure/ZonalParkingManager.scala
We log very often and even when log level is not DEBUG, we still need [to calculate argument](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/event/Logging.scala#L1243) (it's call by value, not call by name)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/738)
> Parking: Lazy logging for `ZonalParkingManager`

- src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
- src/main/scala/beam/agentsim/agents/ridehail/allocation/RepositioningLowWaitingTimes.scala
`TrieMap` is used mostly for `concurrent` read/write. But in our case we have a guarantee that two threads reads/writes map simultaneously
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/823)
> RideHailManager: Replace TrieMap by HashMap

- src/main/scala/beam/calibration/CalibrationArguments.scala
- src/main/scala/beam/calibration/RunCalibration.scala
- src/main/scala/beam/experiment/ExperimentApp.scala
**Problem 1**: The trait `ExperimentApp` was not able to read `args` from `App`. Probably is related to stackable trait behaviour, but I did not have enough time to test and really understand the reason. After transforming it in a `class` the problem was solved. 
**Problem 2**: Due to polymorphism and Java/Scala behaviour `ExperimentApp` was executed first and than called the inherited method `parseArgs` from `RunCalibration`. However the constants were not initialized since the class `RunCalibration` is initialized only after `ExperimentApp` constructor finishes. Therefore the constant defined in the object constructor returned `null`; Extracting it to an external object solved this issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> Issue 849: RunCalibration execution exception with NullpointerException after refactoring

- build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/918)
> set tagID instead of master-SNAPSHOT

- docs/developers.rst
- Description how to proceed when face git-lfs timeout
- Removed `2` warnings from `rst` file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1065)
> Workaround for git-lfs timeout

- src/main/scala/beam/router/r5/R5RoutingWorker.scala
- Daemon threads in ExecutionContext
- Set threads name format to be able to distinguish in profiler
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1138)
> BugFix: R5RoutingWorker should use daemon threads in ExecutionContext

- src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala
- src/main/scala/beam/agentsim/agents/vehicles/EnergyEconomyAttributes.scala
- Removed `linkIds.toList` because it's redundant and makes `nextLinkIds.length` linear operation ([List documentation](https://www.scala-lang.org/api/2.12.7/scala/collection/immutable/List.html))
- Extracted `networkLinks` as local value
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1142)
> BeamVehicle.collectFuelConsumptionData is slow due to the usage of List type

- src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
- src/main/scala/beam/sim/RideHailFleetInitializer.scala
I noticed that initialization takes more time than usual. 
Logs before optimization:
```
15:33:44.282 [main] INFO  beam.sim.BeamMobsim - Preparing new Iteration (Start)
15:33:44.297 [ClusterSystem-akka.actor.default-dispatcher-2] INFO  beam.utils.StuckFinder - StuckFinder is ** DISABLED **
15:33:45.023 [ClusterSystem-akka.actor.default-dispatcher-2] INFO  hsqldb.db.HSQLDB4AD417742A.ENGINE - dataFileCache open start
15:36:40.820 [ClusterSystem-akka.actor.default-dispatcher-17] INFO  b.a.agents.ridehail.RideHailManager - Initialized 206909 ride hailing agents
15:36:45.766 [ClusterSystem-akka.actor.default-dispatcher-21] INFO  beam.agentsim.agents.Population - Initialized 154337 households
```
**Time to initialize ride hailing agents: 176 seconds(diff between 15:33:44.282 and 15:36:40.820)** …
> RideHailManager: Use mutable `ArrayBuffer` to reduce GC pressure and improve performance

- src/main/scala/beam/sim/LoggingParallelEventsManager.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1181)
> BugFix: LoggingParallelEventsManager process all events before calling finishProcessing on underlying eventManager

- src/main/scala/beam/agentsim/agents/ridehail/RideHailRequest.scala
- src/main/scala/beam/router/BeamRouter.scala
- src/main/scala/beam/utils/IdGenerator.scala
- src/test/scala/beam/agentsim/agents/OtherPersonAgentSpec.scala
- src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala
- src/test/scala/beam/agentsim/agents/PersonAndTransitDriverSpec.scala
- src/test/scala/beam/agentsim/agents/PersonWithCarPlanSpec.scala
- src/test/scala/beam/agentsim/agents/PersonWithVehicleSharingSpec.scala
- Added `RideHailRequestIdGenerator` instead of using `IdGeneratorImpl ` to avoid high thread contention. IDs for `RideHailRequest` and( `RoutingRequest`, `EmbodyWithCurrentTravelTime`) have different meanings, so they can intersect (? @colinsheppard)
- Removed `java.util.UUID.randomUUID().hashCode()` from all tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1182)
> Change the way how we generate `RideHailRequest.requestId`

- test/input/sf-light/sf-light-0.5k.conf
- test/input/sf-light/sf-light-10k.conf
- test/input/sf-light/sf-light-1k.conf
- test/input/sf-light/sf-light-2.5k.conf
- test/input/sf-light/sf-light-25k.conf
- test/input/sf-light/sf-light-5k.conf
- test/input/sf-light/sf-light.conf
Increased twice the thresholds for next trigger types:
- beam.agentsim.agents.modalbehaviors.DrivesVehicle$AlightVehicleTrigger
- beam.agentsim.agents.modalbehaviors.DrivesVehicle$BoardVehicleTrigger
- beam.agentsim.agents.modalbehaviors.DrivesVehicle$EndLegTrigger
- beam.agentsim.agents.modalbehaviors.DrivesVehicle$StartLegTrigger
Build failed with error that max number of messages to actor type is exceed (https://beam-ci.tk/blue/rest/organizations/jenkins/pipelines/master/runs/501/log/?start=0).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1202)
> StuckFinder: Increased twice the thresholds

- test/input/sf-light/sf-light-0.5k.conf
- test/input/sf-light/sf-light-10k.conf
- test/input/sf-light/sf-light-1k.conf
- test/input/sf-light/sf-light-2.5k.conf
- test/input/sf-light/sf-light-25k.conf
- test/input/sf-light/sf-light-5k.conf
- test/input/sf-light/sf-light.conf
Increased twice the thresholds for next trigger types:
- beam.agentsim.agents.modalbehaviors.DrivesVehicle$StartLegTrigger
- beam.agentsim.agents.modalbehaviors.DrivesVehicle$EndLegTrigger
I can still see some messages in master branch (https://beam-ci.tk/blue/rest/organizations/jenkins/pipelines/master/runs/503/log/?start=0):
```
21:41:43.564 [single-mode-test-akka.actor.default-dispatcher-25] WARN  beam.utils.StuckFinder - ScheduledTrigger(TriggerWithId(StartLegTrigger(61540,BeamLeg(WALK @ 61540,dur:0,path: 55754 .. 55755)),647327),Actor[akka://single-mode-test/user/BeamMobsim.iteration/population/032700-2016001305358-0/032700-2016001305358-0-2605704#-1262364630],0) is exceed max number of messages threshold. Trigger type: 'class …
```
> StuckFinder: Increased twice the thresholds. Attempt #2

- test/input/sf-light/sf-light-0.5k.conf
- test/input/sf-light/sf-light-10k.conf
- test/input/sf-light/sf-light-1k.conf
- test/input/sf-light/sf-light-2.5k.conf
- test/input/sf-light/sf-light-25k.conf
- test/input/sf-light/sf-light-5k.conf
- test/input/sf-light/sf-light.conf
Increased twice the thresholds for `beam.agentsim.agents.PersonAgent$PersonDepartureTrigger` because I saw error:
```
06:33:37.348 [single-mode-test-akka.actor.default-dispatcher-13] WARN  beam.utils.StuckFinder - ScheduledTrigger(TriggerWithId(PersonDepartureTrigger(84955),916549),Actor[akka://single-mode-test/user/BeamMobsim.iteration/population/033000-2015000413884-0/033000-2015000413884-0-5912962#1643075731],0) is exceed max number of messages threshold. Trigger type: 'class beam.agentsim.agents.PersonAgent$PersonDepartureTrigger', current count: 11, max: 10
```
https://beam-ci.tk/blue/rest/organizations/jenkins/pipelines/beam-4ci/runs/3394/log/?start=0
--- …
> StuckFinder: Increased twice the thresholds. Attempt #3

- src/main/scala/beam/utils/matsim_conversion/VehiclesDataConversion.scala
- test/input/sf-light/sf-light-0.5k.conf
- test/input/sf-light/sf-light-10k.conf
- test/input/sf-light/sf-light-1k.conf
- test/input/sf-light/sf-light-2.5k.conf
- test/input/sf-light/sf-light-25k.conf
- test/input/sf-light/sf-light-5k.conf
- test/input/sf-light/sf-light.conf
Increase thresholds for `beam.agentsim.agents.modalbehaviors.DrivesVehicle$EndLegTrigger` and `beam.agentsim.agents.modalbehaviors.DrivesVehicle$StartLegTrigger`.
Have seen errors in [periodic master build logs](https://beam-ci.tk/blue/rest/organizations/jenkins/pipelines/master-periodic/runs/199/log/?start=0):
```
05:05:09.583 [ClusterSystem-akka.actor.default-dispatcher-27] WARN  beam.utils.StuckFinder - ScheduledTrigger(TriggerWithId(StartLegTrigger(82043,BeamLeg(CAR @ 82043,dur:143,path: 2821 .. 70906)),1544874),Actor[akka://ClusterSystem/user/BeamMobsim.iteration/RideHailManager/rideHailAgent-031400-2015000474543-0-6806555#-1874477004],0) is exceed max number of messages threshold. Trigger type: 'class beam.agentsim.agents.modalbehaviors.DrivesVehicle$StartLegTrigger', current count: …
```
> StuckFinder: Increased twice the thresholds. Attempt #4

- src/main/scala/beam/replanning/ReplanningUtil.scala
Experienced plans not getting endtimes from selected plans... fixes observed end time drift
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1299)
> Fix replanning bug/omission

- src/main/scala/beam/agentsim/events/handling/BeamEventsWriterXML.scala
- src/main/scala/beam/router/osm/TollCalculator.scala
- Initialize special chars only once in `BeamEventsWriterXML.scala`
- Use `TIntObjectHashMap` to avoid boxing (heap allocation)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1551)
> Project:  Minor memory improvements

- src/test/scala/beam/agentsim/agents/household/FastHouseholdCAVSchedulingSpec.scala
- src/test/scala/beam/utils/SimRunnerForTest.scala
After fix, when I run tests:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1570)
> FastHouseholdCAVSchedulingSpec: Use real BeamService instead of mock

- src/main/scala/beam/utils/scenario/Models.scala
- src/main/scala/beam/utils/scenario/ScenarioLoader.scala
- src/main/scala/beam/utils/scenario/ScenarioSource.scala
- src/main/scala/beam/utils/scenario/ScenarioWriter.scala
- src/main/scala/beam/utils/scenario/matsim/MatsimScenarioReader.scala
- src/main/scala/beam/utils/scenario/matsim/MatsimScenarioSource.scala
- src/main/scala/beam/utils/scenario/urbansim/CsvScenarioReader.scala
- src/main/scala/beam/utils/scenario/urbansim/DataExchange.scala
- src/main/scala/beam/utils/scenario/urbansim/ParquetScenarioReader.scala
- src/main/scala/beam/utils/scenario/urbansim/UrbanSimScenarioReader.scala
- src/main/scala/beam/utils/scenario/urbansim/UrbanSimScenarioSource.scala
- src/test/scala/beam/utils/scenario/urbansim/ParquetScenarioReaderTest.scala
- Renamed `PlanInfo` to `PlanElement`
- Drop planElements which are corrupted
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1608)
> UrbanSim: Drop corrupted planElement

- src/main/scala/beam/router/BeamSkimmer.scala
AllModes (Prepare data in parallel):
01:39:50.021 INFO  beam.router.BeamSkimmer - Get weightedSkims for modes executed in 35092 ms
01:39:50.021 INFO  beam.router.BeamSkimmer - weightedSkims size: 22394880
01:41:21.614 INFO  beam.router.BeamSkimmer - writeAllModeSkimsForPeakNonPeakPeriods on iteration 0 executed in 126686 ms
AllModes (Single thread):
00:28:58.692 INFO  beam.router.BeamSkimmer - writeAllModeSkimsForPeakNonPeakPeriods on iteration 0 executed in 243807 ms, compressed size: 188 MBytes 
Only CAR mode:
00:33:56.431 INFO  beam.router.BeamSkimmer - writeCarSkimsForPeakNonPeakPeriods on iteration 0 executed in 26972 ms, complressed size: 26.0 MB
--- …
> Include all modes in excerpt skims

- build.gradle
- src/main/java/beam/router/r5/R5MnetBuilder.java
- src/main/resources/logback.xml
- src/main/scala/beam/agentsim/agents/PersonAgent.scala
- src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala
- src/main/scala/beam/router/BeamRouter.scala
- src/main/scala/beam/router/BeamSkimmer.scala
- src/main/scala/beam/router/TravelTimeObserved.scala
- src/main/scala/beam/router/model/EmbodiedBeamTrip.scala
- src/main/scala/beam/router/r5/NetworkCoordinator.scala
- src/main/scala/beam/router/r5/R5RoutingWorker.scala
- src/main/scala/beam/sim/BeamMobsim.scala
- src/main/scala/beam/sim/BeamServices.scala
- src/main/scala/beam/sim/BeamSim.scala
- src/main/scala/beam/utils/ScenarioComparator.scala
- src/main/scala/beam/utils/osm/WayFixer.scala
- src/test/scala/beam/agentsim/agents/OtherPersonAgentSpec.scala
- src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala
- src/test/scala/beam/agentsim/agents/PersonAndTransitDriverSpec.scala
- src/test/scala/beam/agentsim/agents/PersonWithPersonalVehiclePlanSpec.scala
- src/test/scala/beam/agentsim/agents/PersonWithVehicleSharingSpec.scala
- src/test/scala/beam/agentsim/agents/household/FastHouseholdCAVSchedulingSpec.scala
- src/test/scala/beam/utils/SimRunnerForTest.scala
- src/test/scala/beam/utils/TestConfigUtils.scala
- src/test/scala/beam/utils/osm/WayFixerTest.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1712)
> Sync up with master: Part 1

- src/main/java/beam/agentsim/events/handling/BeamEventsLogger.java
- src/main/scala/beam/agentsim/events/PathTraversalEvent.scala
- src/main/scala/beam/agentsim/events/handling/BeamEventsWriterXML.scala
- Safe previously created attributes in `PathTraversalEvent`
- Memory optimization for XML event writer
- Do not allocate extra HashSet, map already contains keys as Set `keySet`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1755)
> Memory optimizations for events writers (CSV, XML)

- src/main/scala/beam/sim/BeamHelper.scala
- src/main/scala/beam/utils/ConfigConsistencyComparator.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1765)
Both: startup message and config consistency validator are logged twice when application starts:
```
________
___  __ )__________ _______ ___
__  __  |  _ \  __ `/_  __ `__ \
_  /_/ //  __/ /_/ /_  / / / / /
/_____/ \___/\__,_/ /_/ /_/ /_/
_____________________________________
****************************************************************************************************************************  
** Config File Consistency Check
**  
** Testing your config file against what BEAM is expecting.
**  
** Found the following deprecated parameters, you can safely remove them from your config file:
...
```
> Startup message logged twice 4ci - fixed

- src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java
Write csv and plot to compare euclidean vs. length attribute plot for
matsim network #1697
csv example:
```
euclidean,length
75.251034,75.065000
75.251034,75.065000
146.482438,146.110000
25.642816,26.915000
12.238537,12.260000
3.537632,3.542000
3.537632,3.542000
3.511446,3.516000
3.511446,3.516000
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1754)
> Write csv and plot to compare euclidean vs. length attribute plot #1697

- src/main/scala/beam/utils/NetworkXmlToCSV.scala
- Added `main` method
- Ability to read compressed XML (.xml.gz)
Example of args: `"C:\Users\User\Downloads\physSimNetwork.xml.gz" "," "C:\temp\nodeOutput.csv" "C:\temp\linkOutput.csv" "C:\temp\mergeOutput.csv"`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1775)
> NetworkXmlToCSV.scala: Ability to run

- src/main/scala/beam/sim/BeamHelper.scala
- src/main/scala/beam/utils/scenario/ScenarioLoader.scala
- src/test/scala/beam/integration/EventsFileSpec.scala
Ccaldas/#1753 a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1766)
Main changes:
- Warmstart was executed before loading specific configuration. 
- General refactoring: extracted methods and made things clear
- Script loaded twice: first Matsim config xml files are loaded and then the values are replaced by specific parameters (like Urbasim). This was not completely solved due to highly coupling but at least not is clear this behavior and some redundant steps were removed
> Avoid scenario loaded twice 4ci

- src/main/java/beam/analysis/physsim/PhyssimNetworkComparisonEuclideanVsLengthAttribute.java
- src/main/java/beam/physsim/jdeqsim/cacc/roadCapacityAdjustmentFunctions/Hao2018CaccRoadCapacityAdjustmentFunction.java
- src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
- src/main/scala/beam/analysis/DelayMetricAnalysis.scala
- src/main/scala/beam/router/BeamSkimmer.scala
- src/main/scala/beam/sim/BeamHelper.scala
- src/main/scala/beam/sim/BeamMobsim.scala
- Added timeout for RideHailManagerInit
- Make sure there is only one matsimScenario(`fillScenarioFromExternalSources` fills passed scenario, not creating new one)
- Fix java.lang.ArrayIndexOutOfBoundsException in beam.analysis.DelayMetricAnalysis.process 
- Fixed default `autoSort=true` when create `XYSeries`
- Fix high thread contention during the writing of the skims
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1798)
> Cumulative fixes

- src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
- src/main/scala/beam/agentsim/agents/ridehail/allocation/PoolingAlonsoMora.scala
- src/main/scala/beam/sim/BeamMobsim.scala
It should solve a problem when we try to use `UNIFORM_RANDOM` with `UrbanSim` data:
```
15:23:13.408 [ClusterSystem-akka.actor.default-dispatcher-24] ERROR b.a.agents.ridehail.RideHailManager - Could not createRideHailVehicleAndAgent: cannot add a point at x=667806.803402751, y=4109056.4709358355 with bounds topLeft: (442704.66790294164,4073548.042681266) bottomRight: (665356.5467613721,4313187.271314456)
java.lang.IllegalArgumentException: cannot add a point at x=667806.803402751, y=4109056.4709358355 with bounds topLeft: (442704.66790294164,4073548.042681266) bottomRight: (665356.5467613721,4313187.271314456)
at org.matsim.core.utils.collections.QuadTree$Node.put(QuadTree.java:602)
at org.matsim.core.utils.collections.QuadTree$Node.put(QuadTree.java:623)
at …
```
> RideHailManager: Bounding box big enough for initial location

- src/main/scala/beam/agentsim/agents/choice/logit/MultinomialLogit.scala
- src/test/scala/beam/agentsim/agents/choice/logit/MultinomialLogitSpec.scala
dropped use of SortedSet in favor of a List in MultinomialLogit's sampleAlternative function, per discussions about the issues with equality testing in SortedSet (see #1884 and [this link](https://stackoverflow.com/questions/4952374/scala-sortedset-sorted-by-one-ordering-and-unique-by-something-else) for details).
tracking infinitely-valued alternatives is now done by placing infinitely-valued alternatives at the tail of the list, and afterward, checking the `lastOption` of the list for a utility which equals Double.PositiveInfinity.
this also changed the Tuple2 of (AlternativeType, Double) into it's own case class, which is clearer.
in support of this change, the following happened:
- added a test for dealing with positively infinite values
- added a test for dealing with equally-valued …
> dropped use of SortedSet in favor of a List in Multinomial Logit function

- src/main/scala/beam/sim/BeamMobsim.scala
- test/input/common/akka.conf
This gives two things:
- Slightly improves performance because of decreasing context switching
- More important one is ability to see what's going on with those actors in Java Mission Control:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1907)
> Pin BeamAgentScheduler, ZonalParkingManager and RideHailManager to dedicated threads

- src/main/scala/beam/agentsim/agents/PersonAgent.scala
- src/main/scala/beam/agentsim/agents/household/HouseholdActor.scala
- src/main/scala/beam/agentsim/agents/ridehail/RideHailAgent.scala
- src/test/scala/beam/integration/AgentsimWithMaximallyBadRouterSpec.scala
Agents that talk to the router, and/or that pipe Futures to themselves, must receive Status.Failure() and deal with it by dying, otherwise they can get stuck.
Test this by letting the Agentsim talk to a bogus router.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1913)
> Exception-throwing-router stress test

- src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java
- src/main/scala/beam/router/r5/R5RoutingWorker.scala
The router was logging cases with extremely low reported link speeds before, and I removed that while working on the travel times per vehicle type, and forgot to put it back in. (Only the logging, the fix was never removed.)
Here, I put in pack in, but where the link travel times are computed, not where they are used.
It happens a lot, even in BeamVille. There it is because of busses, they take like a day to traverse a link.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1912)
> Put the logging for the link speed quick fix back in, but at the source

- src/main/java/beam/analysis/StatsFactory.java
- src/main/scala/beam/analysis/SimpleRideHailUtilization.scala
- src/test/scala/beam/analysis/SimpleRideHailUtilizationTest.scala
Simple ridehail utilization which creates the stats from number of passengers to amount of trips. It is implemented as one more `IterationSummaryAnalysis `, so the stats are automatically added to `summaryStats.csv` file. Stats column name are `RideTripsWith0Passengers`, `RideTripsWith1Passengers` and so on. PNGs files are automatically created with name `RideTripsWith0Passengers.png`, `RideTripsWith1Passengers.png` and so on. Example:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1901)
> Added SimpleRideHailUtilization

- src/main/scala/beam/router/BeamRouter.scala
- src/main/scala/beam/router/r5/R5RoutingWorker.scala
- src/test/scala/beam/sflight/SfLightRouterSpec.scala
When the `R5RoutingWorker` has an Exception while serving a request, it would reply with a `Status.Failure(_)`, because it pipes a `Future`.
`BeamRouter` would not relay that reply.
With this change, that reply is relayed to the agent who makes the request. Implemented by using another message type between `BeamRouter` and `R5RoutingWorker`.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1924)
> Relay Failure responses from router

- src/main/scala/beam/agentsim/agents/PersonAgent.scala
- src/main/scala/beam/agentsim/agents/TransitDriverAgent.scala
- src/main/scala/beam/agentsim/agents/TransitSystem.scala
- src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala
- src/main/scala/beam/agentsim/agents/vehicles/VehicleAccessRequest.scala
- src/main/scala/beam/router/TransitInitializer.scala
- src/main/scala/beam/router/model/RoutingModel.scala
- src/main/scala/beam/router/r5/R5RoutingWorker.scala
- src/main/scala/beam/sim/BeamHelper.scala
- src/main/scala/beam/sim/BeamScenario.scala
- src/main/scala/beam/sim/monitoring/ErrorListener.scala
- src/test/scala/beam/agentsim/agents/PersonAgentSpec.scala
- src/test/scala/beam/agentsim/agents/PersonAndTransitDriverSpec.scala
- src/test/scala/beam/sflight/SfLightRouterSpec.scala
As a precondition to #1711, don't require passengers to present the exact same sequence of legs to the bus driver that they are going to ride. Instead, tell them the "slice" of the trip we want to take, by start and end index into the stop sequence.
As a side effect, the big global transit map isn't required anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1928)
> Refer to transit segments by index, not by leg

- src/main/scala/beam/sim/BeamSim.scala
After run Beamville
```xml
<person id="47">
<plan score="127.78246793517155" selected="yes">
<attributes>
<attribute name="modality-style" class="java.lang.String" >class2</attribute>
</attributes>
<activity type="Home" link="sfpt173961" x="170308.4" y="2964.6474" end_time="06:45:00" >
</activity>
<activity type="Work" link="sfpt539076" x="169346.4" y="876.7536" end_time="19:59:58" >
</activity>
<activity type="Home" link="sfpt173961" x="170308.4" y="2964.6474" >
</activity>
</plan>
</person>
```
```csv
47,0,activity,0,Home,170308.4,2964.6474,24300.0,
47,0,activity,1,Work,169346.4,876.7536,71998.0,
47,0,activity,2,Home,170308.4,2964.6474,-Infinity,
``` …
> Write plans.csv before iteration starts instead of after finish

- src/main/scala/beam/agentsim/infrastructure/charging/ChargingPointType.scala
errors were occurring because the legacy `ChargingPointType`s were not properly "cased out" in pattern matching over `ChargingPointType` values.
i also modified the ChargingPointType Regex so that it is "unanchored" and can grab occurrences of the named charging point from a row at any position. that is consistent with the design, but, now that i'm thinking about it, if a user used a reserved ChargingPointType or PricingModel name in their TAZ name, then the regex would find that. maybe we should restrict our parsing to the row/column instead of the entire row.
anyhow, this fixes the bug. perhaps additionally we should add test class(es) for the charging code. 
Closes #1940.
--- …
> all pattern matching ops on ChargingPointType now cover all cases

- src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
- src/main/scala/beam/sim/RideHailFleetInitializer.scala
- src/main/scala/beam/utils/csv/CsvWriter.scala
- src/main/scala/beam/utils/csv/GenericCsvReader.scala
- src/test/scala/beam/sim/RideHailFleetInitializerSpec.scala
- Simplify the reading/writing of ride-hail fleet
- When read ride-hail fleet from file, use `fleetData.vehicleType` as vehicle type
- Added test for `RideHailFleetInitializer`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1978)
> Simplify the reading/writing of ride-hail fleet

- src/main/scala/beam/sim/BeamHelper.scala
- src/main/scala/beam/sim/BeamWarmStart.scala
- src/test/scala/beam/agentsim/agents/GenericEventsSpec.scala
- src/test/scala/beam/agentsim/agents/ridehail/AlonsoMoraPoolingAlgForRideHailSpec.scala
- src/test/scala/beam/agentsim/agents/ridehail/AsyncAlonsoMoraAlgForRideHailSpec.scala
- src/test/scala/beam/agentsim/agents/ridehail/RideHailPassengersEventsSpec.scala
- src/test/scala/beam/agentsim/agents/ridehail/RideHailSurgePricingManagerSpec.scala
- src/test/scala/beam/integration/CAVSpec.scala
- src/test/scala/beam/integration/CarSharingSpec.scala
- src/test/scala/beam/integration/DriveTransitSpec.scala
- src/test/scala/beam/integration/EventsFileSpec.scala
- src/test/scala/beam/integration/LCCMSpec.scala
- src/test/scala/beam/integration/ridehail/RideHailAllocationRandomRepositioningSpec.scala
- src/test/scala/beam/integration/ridehail/RideHailReplaceAllocationSpec.scala
- src/test/scala/beam/sflight/CaccSpec.scala
- src/test/scala/beam/sflight/SfLightRunSpec.scala
- src/test/scala/beam/utils/SimRunnerForTest.scala
- test/input/sf-light/urbansim-100k-warmstart.conf
- test/input/sf-light/urbansim-100k.conf
- Warmstart respects ride-hail fleet state
- `module` uses passed `beamConfig` instead of creating new instance
- We still need `typesafeConfig` for `ConfigModule`
Closes #1985 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1986)
> Warmstart: Read ride-hail fleet state

- src/main/java/beam/analysis/StatsFactory.java
- src/main/scala/beam/analysis/VehicleChargingAnalysis.scala
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2018)
> Add charging Graph

- src/main/scala/beam/agentsim/agents/ridehail/allocation/PoolingAlonsoMora.scala
- src/main/scala/beam/agentsim/agents/ridehail/allocation/RideHailResourceAllocationManager.scala
`RideHailResourceAllocationManager` already creates reposition manager internally, no need to do it in `PoolingAlonsoMora`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2023)
> Pooling should not be aware of reposition manager

- src/main/scala/beam/sim/vehicles/IncomeBasedVehiclesAdjustment.scala
Minor fix--realized the structure collecting income groups and vehicle probabilities was being re-made within a loop over vehicle types, where it should have only been made after the last vehicle type was looped through.
Shouldn't affect the results at all, just fixing for neatness
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2060)
> do not re-calculate income group -> vehicle mapping unnecessarily

- src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java
- src/main/java/beam/physsim/jdeqsim/cacc/roadCapacityAdjustmentFunctions/Hao2018CaccRoadCapacityAdjustmentFunction.java
- src/main/java/beam/physsim/jdeqsim/cacc/sim/Road.java
- src/main/scala/beam/agentsim/agents/modalbehaviors/DrivesVehicle.scala
- src/main/scala/beam/agentsim/agents/ridehail/AlonsoMoraPoolingAlgForRideHail.scala
- src/main/scala/beam/agentsim/agents/ridehail/AsyncAlonsoMoraAlgForRideHail.scala
- src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
- src/main/scala/beam/agentsim/agents/ridehail/repositioningmanager/DemandFollowingRepositioningManager.scala
- src/main/scala/beam/scoring/BeamScoringFunctionFactory.scala
- src/main/scala/beam/sim/BeamConfigChangesObservable.scala
- src/main/scala/beam/sim/BeamHelper.scala
- src/main/scala/beam/sim/BeamServices.scala
Closes #2074 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2085)
> Auto refresh config when values change

- src/main/scala/beam/agentsim/events/RefuelSessionEvent.scala
- src/main/scala/beam/analysis/LoadOverTimeAnalysis.scala
adds an output plot for `chargingPowerByParkingType.png` which looks like this:
had to change RefuelSessionEvent so that the parkingType String was exposed from the class. 
Closes #2111.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2112)
> add new plot. expose parking type in RefuelSessionEvent.

- src/main/java/beam/analysis/plots/RideHailWaitingAnalysis.java
Average wait times and the ride hail waiting time duration plots were only looking at mode choice events with mode `ride_hail` not `ride_hail_pooled`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2140)
> look at trips with mode ride_hail_pooled in events analysis

- src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala
fixes an issue with initial waiting time not being factored in to ridehail mode choice
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2139)
> make dummy walk trip start at the time of the ridehail request

- src/main/scala/beam/agentsim/agents/TransitSystem.scala
- src/main/scala/beam/router/TransitInitializer.scala
- src/main/scala/beam/router/r5/R5RoutingWorker.scala
We were defaulting to 0.0 in the length attribute for PathTraversals that don't follow the road network (i.e. rail modes). This fills in the euclidean distance between the start and end for each non-road transit leg between stops.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2147)
> euclidean distance for non road transit

- src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala
- src/main/scala/beam/sim/population/PopulationAttributes.scala
We've observed some generalized times in the skims that are higher than they should be based on the config VOTT multipliers, implying that generalized times are getting artificially inflated somewhere. 
I think this is because generalized TT is calculated by looping over all links in car paths, whereas the driver does not necessarily need to drive the full distance of the first and last link. By matsim convention this means ignoring the first link when calculating travel time and distance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2155)
> Fix inflated generalized times (#2153)

- src/main/scala/beam/agentsim/events/RefuelSessionEvent.scala
Fixes #2179
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2180)
> #2179 print vehicle type id in refuelsessionevent

- src/main/scala/beam/agentsim/agents/ridehail/RideHailAgent.scala
- src/main/scala/beam/agentsim/agents/ridehail/RideHailModifyPassengerScheduleManager.scala
- src/main/scala/beam/utils/IdGenerator.scala
- src/test/scala/beam/agentsim/agents/RideHailAgentSpec.scala
- Changed `interruptId` to be Int
- Added `InterruptIdIdGenerator` to generate monotonically increasing ids for interrupts
Solves https://github.com/LBNL-UCB-STI/beam/issues/2190
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2191)
> Use InterruptIdIdGenerator to generate interrupt ids

- src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
- src/main/scala/beam/agentsim/agents/vehicles/VehicleAccessRequest.scala
- src/main/scala/beam/utils/IdGenerator.scala
- src/test/scala/beam/agentsim/agents/PersonAndTransitDriverSpec.scala
- src/test/scala/beam/agentsim/agents/RideHailAgentSpec.scala
- src/test/scala/beam/integration/AgentsimWithMaximallyBadRouterSpec.scala
- Added `ReservationRequestIdGenerator`
- `ReservationRequest.requestId` is an integer and it uses `ReservationRequestIdGenerator`
===
I've just removed an unused method from `RideHailManager.scala` and optimized its imports that's why so many changes in that file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2195)
> Use ReservationRequestIdGenerator to generate requestId for reservation  #2191

- aws/src/main/python/beam_lambda/lambda_function.py
- aws/src/main/python/cloneAMI/lambda_function.py
- aws/src/main/python/createAMI/lambda_function.py
- aws/src/main/python/updateBeamAMI/lambda_function.py
- aws/src/main/python/updateDependencies/lambda_function.py
- aws/src/main/python/updateSimulateBeamEnvVars/lambda_function.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2198)
> Make sure what is in AWS is what is in git

- src/main/java/beam/analysis/plots/RideHailWaitingAnalysis.java
- src/main/scala/beam/agentsim/agents/PersonAgent.scala
Changes which are in `production-sfbay-develop-debug`, but not in `pr…oduction-sfbay-develop` (and not in `develop` too)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2205)
> Changes to bring back to develop because they were pushed directly to production-sfbay-develop-debug

- src/main/scala/beam/agentsim/agents/ridehail/RideHailVehicleManager.scala
- src/main/scala/beam/agentsim/agents/ridehail/allocation/PoolingAlonsoMora.scala
- test/input/sf-light/sf-light-25k.conf
`idleRideHailAgentSpatialIndex` is growing because of containing multiple `RideHailAgentLocation` for the same vehicle.
We have
```
08:02:41.370 [ClusterSystem-akka.actor.default-dispatcher-50] INFO  b.a.agents.ridehail.RideHailManager - Initialized 6946 ride hailing agents
```
But if you look to the result from spatial index, there are 7117 RideHailAgentLocations (which is more than the number of ride hail agents!), when it has only 993 unique vehicle id:
If I group by vehicleId, the same vehicle has 10 entries:
Two instances of `RideHailAgentLocation` are equal if they have the same `vehicleId`. This solves problem when `RideHailAgentLocation` is removed from Spatial index: problem of having multiple `RideHailAgentLocation` for the single `vehicleId` in spatial index.
With this fix …
> Fix the grow of idleRideHailAgentSpatialIndex

- src/main/scala/beam/agentsim/agents/ridehail/AlonsoMoraPoolingAlgForRideHail.scala
- src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
- src/main/scala/beam/agentsim/agents/ridehail/RideHailVehicleManager.scala
- src/main/scala/beam/agentsim/agents/ridehail/VehicleCentricMatchingForRideHail.scala
- src/main/scala/beam/agentsim/agents/ridehail/allocation/Pooling.scala
- src/main/scala/beam/agentsim/agents/ridehail/allocation/PoolingAlonsoMora.scala
- src/main/scala/beam/agentsim/agents/ridehail/allocation/RandomRepositioning.scala
- src/main/scala/beam/agentsim/agents/ridehail/allocation/RideHailResourceAllocationManager.scala
- src/main/scala/beam/agentsim/agents/ridehail/repositioningmanager/DemandFollowingRepositioningManager.scala
- src/main/scala/beam/agentsim/agents/ridehail/repositioningmanager/RepositioningLowWaitingTimes.scala
- src/main/scala/beam/agentsim/agents/ridehail/repositioningmanager/RepositioningManager.scala
- src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala
- Replace data structures to appropriate one to reduce runtime
- Explicitly put check for the log level because Actor Logging need to calculate args before calling logging method
- Intensive operation to get idle vehicles is cached and passed instead of re-computing it
- Config: `production/sfbay/smart/smart-b-hightech-2040.conf`, for 5 iterations
- Baseline: branch [art/#2223-prod-dev-updated](https://github.com/LBNL-UCB-STI/beam/tree/art/%232223-prod-dev-updated), commit 674b838aefac6c9ed16de6bfa3fd17999b8235e2, result: https://s3.us-east-2.amazonaws.com/beam-outputs/index.html#output/sfbay/sfbay-smart-b-ht-2040__2019-10-25_19-37-05
- Optimized: branch [art/#2223-prod-dev-updated](https://github.com/LBNL-UCB-STI/beam/tree/art/%232223-prod-dev-updated), commit …
> Performance improvements

- src/main/scala/beam/agentsim/infrastructure/ZonalParkingManager.scala
- src/main/scala/beam/utils/CriticalActor.scala
Closes #2311
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2312)
> Add Critical Actor trait and use in ZPM

- src/main/scala/beam/agentsim/infrastructure/taz/H3TAZ.scala
- Added logs how much time does it take to fill the box and to compute `tazToH3TAZMapping` 
- Compute `tazToH3TAZMapping` in parallel
- Extracted `transformation` to local val because internally it throws a lot of exception which slows down the loop
I'm currently working on Austin data and during the loading of simulation I saw it takes some time in H3TAZ. The main reason of course because the map contains 10kk nodes and bounding box area is pretty big. Here are the logs from H3TAZ to get some sense of the numbers of elements and the bounding box area
```
22:46:00.220 INFO  b.agentsim.infrastructure.taz.H3TAZ - fillBox for boundingBox QuadTreeBounds(-106.69448850456033,25.81901984758941,-93.3861787743846,36.69892793549934) with resolution 10 executed in 230483 ms
22:46:00.220 INFO …
```
> H3TAZ: Minor improvements

- build.gradle
- src/main/scala/beam/agentsim/agents/ridehail/AlonsoMoraPoolingAlgForRideHail.scala
- src/main/scala/beam/agentsim/agents/ridehail/allocation/PoolingAlonsoMora.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2377)
https://github.com/LBNL-UCB-STI/or-tools-wrapper
> Add or-tools

- src/main/scala/beam/analysis/cartraveltime/CarTripStatsFromPathTraversalEventHandler.scala
- src/main/scala/beam/analysis/cartraveltime/models.scala
- src/main/scala/beam/sim/BeamSim.scala
- src/test/scala/beam/analysis/cartraveltime/CarTripStatsFromPathTraversalEventHandlerSpec.scala
- src/test/scala/beam/sim/BeamWarmStartRunSpec.scala
- Added departure location (`start_x`, `start_y`) and arrival location (`end_x`, `end_y`) to `CarTripStat`
- Fixed bug in `writeCarTripStats` which was caused by using the same name of output file for all car types
- Renamed types to have less confusion with RideHail
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2429)
> Improvements in CarTripStatsFromPathTraversalEventHandler

- build.gradle
If `MAXRAM` parameter is odd number, then `./gradlew run` fails with:
```
$ ./gradlew run -PappArgs="['--config', 'test/input/texas/austin-prod-100k.conf']"
[-Xmx25g, -Xms12.5g, -XX:+UseParallelGC, -XX:+UseParallelOldGC, -XX:MetaspaceSize=150M, -Djava.awt.headless=true, -Dlogback.configurationFile=logback_prod.xml, -Xss2048k, -XX:+PrintGCDetails, -XX:+PrintGCDateStamps, -Xloggc:gc_03-22-2020_11-38-38.log, -Dcom.sun.management.jmxremote, -Dcom.sun.management.jmxremote.port=9005, -Dcom.sun.management.jmxremote.host=127.0.0.1, -Dcom.sun.management.jmxremote.local.only=true, -Dcom.sun.management.jmxremote.authenticate=false, -Dcom.sun.management.jmxremote.ssl=false, -Djava.net.preferIPv4Stack=true, -Djava.rmi.server.hostname=127.0.0.1]
:compileJava NO-SOURCE
:compileScala
Note: Some input …
```
> Gradle: Fix error when myAvailableRam/2 is not integer

- src/main/scala/beam/sim/metrics/SimulationMetricCollector.scala
This will cause to see the following error in the logs in case if InfluxDB is not available:
```
22:15:53.495 ERROR b.s.m.InfluxDbSimulationMetricCollector - Could not connect to InfluxDB at http://localhost:8086, database: beam: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:8086
org.influxdb.InfluxDBIOException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:8086
at org.influxdb.impl.InfluxDBImpl.ping(InfluxDBImpl.java:395)
at beam.sim.metrics.InfluxDbSimulationMetricCollector.liftedTree1$1(SimulationMetricCollector.scala:226)
at beam.sim.metrics.InfluxDbSimulationMetricCollector.<init>(SimulationMetricCollector.scala:222)
at beam.sim.metrics.InfluxDbSimulationMetricCollector$$FastClassByGuice$$ae09cc89.newInstance(<generated>)
at …
```
> Try to open connection to InfluxDB

- src/main/java/beam/analysis/physsim/PhyssimCalcLinkSpeedStats.java
- src/main/java/beam/analysis/physsim/PhyssimCalcLinkSpeedStatsObject.scala
- src/main/java/beam/analysis/summary/VehicleMilesTraveledAnalysis.java
- src/main/java/beam/physsim/jdeqsim/cacc/sim/Road.java
Road:
- Transformed instance variables into class variables: 1
- Added suffix to avoid loose of precision: 1
- Assigned variable never used: 1
- Removed redundant initialization: 1
PhyssimCalcLinkSpeedStats:
- Transformed static variables into constants: 3
- Transformed mutable object into immutable: 1
- Extracted method: 1
- Transformed instance variable into final instance variables: 5
- Removed redundant comments: 8
- Removed premature declaration: 1
- Transformed Boxed type into primitive type: 1
VehicleMilesTraveledAnalysis:
- Transformed instance variables into class variables: 1
- Added suffix to avoid loose of precision: 1
- Transformed instance variable into final instance variables: 2
- Avoid NullPointerException: 1
- Removed redundant comments: 1
#Relevant changes:
Previous: …
> Refactoring: 30 small improvements/fixes

- src/main/scala/beam/agentsim/agents/PersonAgent.scala
- src/main/scala/beam/router/model/BeamLeg.scala
- src/main/scala/beam/router/model/EmbodiedBeamLeg.scala
I think the problem is that the walk leg from a parking stall was given as having duration 0 despite starting/ending after the previous car leg finished. So its duration was being accounted for in `trip.totalTravelTimeInSecs` but not in generalized time, which sums the leg travel times multiplied by mode-specific VOTT factors.
should fix #2287 but still need to test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2288)
> add duration to dummy walk leg

- aws/src/main/python/updateDependencies/lambda_function.py
for #2486 
added `docker-ce`
added `docker-compose` of a specific version, because, there is a bag in the modern version of docker-compose.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2491)
> Added docker and docker-compose to AMI build script

- docs/grafana.rst
- gradle.deploy.properties
- production/common/metrics.conf
Grafana metrics are enabled by default for production configs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2496)
> Grafana metrics enabled by default for production runs

- src/main/scala/beam/agentsim/agents/PersonAgent.scala
During trip planning (in ChoosesMode) we build a trip with legs that looks like e.g. WALK,RIDE_HAIL,WALK. When we do this we make the start time of the WALK leg be “now” and start time of the RIDE_HAIL be set to the pickup time, which therefore allows our mode choice alg to include wait time in the option.
So far so good. 
But then when we execute the trip we are taking the dummy WALK leg which takes 0 seconds and we are sending a reservation request to RHM with the start time of the RIDE_HAIL leg as the requested departure time. So this is a problem because the RHM takes requested departure time on faith and won’t dispatch a vehicle more quickly even if it were possible.
--- …
> Use now for ride hail reservation time

- aws/src/main/python/updateDependencies/lambda_function.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2549)
> updateDependencies: Updated GCC to 8 to support CXXABI_1.3.12

- src/main/scala/beam/utils/CriticalActor.scala
Write stack trace to STDERR and increase wait time to make sure the message is written to the logs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2569)
> CriticalActor: Increase waiting time and write to STDERR too

- src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java
It's a hot place currently:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2573)
> AgentSimToPhysSimPlanConverter: Use mean to compute average instead of collecting all speeds

- aws/build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2607)
> Use reboot version and allow for no default instance

- docs/users.rst
Env: Ubuntu 18.04, only JRE is installed (openjdk-8-jre-headless). Got an error during compilation of beam:
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileScala'.
> java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-openjdk-amd64/bin/javac": error=2, No such file or directory
```
As we can see it needs `javac`, Java compiler. After installing JDK (`sudo apt-get install openjdk-8-jdk`) it worked:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2654)
> We need to have JDK installed in order to get javac (java compiler)

- aws/build.gradle
- instance_type is a string
- set `payload` before using it
Got an error during deploy:
```
:aws:deploy
{
"title": "art/austin-prod-200k-plans-from-urbnasim_reasyuATgmail_com",
"git_user_email": "reasyuATgmail_com",
"deploy_type_tag": "null",
"branch": "AK/#2624-merg-urbansim-with-austin",
"commit": "d9644ad64a1432000602cd9c1ec8da8640152f00",
"deploy_mode": "config",
"configs": "test/input/texas/austin-prod-100k.conf",
"experiments": "null",
"execute_class": "beam.sim.RunBeam",
"execute_args": "null",
"max_ram": "300g",
"storage_size": 256,
"batch": false,
"s3_publish": true,
"instance_type": c5.9xlarge,
"region": "us-east-2",
"shutdown_wait": "15",
"shutdown_behaviour": "terminate",
"command": "deploy",
"run_grafana" : false,
"is_spot" : false,
"min_cores": 0,
"max_cores": 0, …
```
> AWS Deploy: Instance type should be string

- src/main/java/beam/analysis/physsim/PhyssimCalcLinkSpeedDistributionStats.java
- src/main/java/beam/analysis/physsim/PhyssimCalcLinkSpeedStats.java
- src/main/java/beam/analysis/physsim/PhyssimCalcLinkStats.java
- src/main/java/beam/analysis/physsim/PhyssimSpeedHandler.java
- src/main/java/beam/analysis/plots/BaseModeAnalysis.java
- src/main/java/beam/analysis/plots/DeadHeadingAnalysis.java
- src/main/java/beam/analysis/plots/FuelUsageAnalysis.java
- src/main/java/beam/analysis/plots/GraphSurgePricing.java
- src/main/java/beam/analysis/plots/GraphUtils.java
- src/main/java/beam/analysis/plots/PersonTravelTimeAnalysis.java
- src/main/java/beam/analysis/plots/RealizedModeAnalysis.java
- src/main/java/beam/analysis/plots/RideHailWaitingAnalysis.java
- src/main/java/beam/analysis/plots/modality/ModalityStyleStats.java
- src/main/java/beam/analysis/plots/passengerpertrip/CarPassengerPerTrip.java
- src/main/java/beam/analysis/plots/passengerpertrip/IGraphPassengerPerTrip.java
- src/main/java/beam/analysis/plots/passengerpertrip/TncPassengerPerTrip.java
- src/main/scala/beam/analysis/DelayMetricAnalysis.scala
- src/main/scala/beam/analysis/SimpleRideHailUtilization.scala
- src/main/scala/beam/analysis/cartraveltime/CarTripStatsFromPathTraversalEventHandler.scala
- src/main/scala/beam/sim/BeamSim.scala
Move some jfree usage to GraphUtils.
Examples
1. Old version of `passengerPerTripRideHail.png` is
Fixed version is
2. Old version of `physsimFreeFlowSpeedDistribution.png` is
Fixed version is
Pngs looks same, bug in csv file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2652)
> Move jfree usage to GraphUtils, part1

- src/main/scala/beam/agentsim/agents/TransitSystem.scala
- src/main/scala/beam/agentsim/agents/choice/mode/ModeIncentive.scala
- src/main/scala/beam/agentsim/agents/choice/mode/PtFares.scala
- src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala
- src/main/scala/beam/agentsim/agents/ridehail/TNCIterationStats.scala
- src/main/scala/beam/calibration/impl/example/ModeChoiceObjectiveFunction.scala
- src/main/scala/beam/calibration/impl/example/RideHailObjectiveFunction.scala
- src/main/scala/beam/router/BeamRouter.scala
- src/main/scala/beam/router/osm/TollCalculator.scala
- src/main/scala/beam/router/r5/FrequencyAdjustingNetworkCoordinator.scala
- src/main/scala/beam/utils/FileUtils.scala
- src/main/scala/beam/utils/GeoJsonReader.scala
- src/main/scala/beam/utils/map/GeoFenceVerifier.scala
- src/main/scala/beam/utils/map/TazTravelTimeAnalyzer.scala
- src/main/scala/beam/utils/matsim_conversion/MatsimConversionTool.scala
- src/test/scala/beam/integration/EventsFileSpec.scala
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2651)
> Removed 20 warnings

- src/main/scala/beam/router/skim/AbstractSkimmer.scala
- src/main/scala/beam/router/skim/CsvSkimReader.scala
- src/main/scala/beam/router/skim/DriveTimeSkimmer.scala
- src/main/scala/beam/router/skim/ODSkimmer.scala
- src/main/scala/beam/router/skim/TAZSkimmer.scala
- Reduce memory pressure by using `scala.collection.Map`
- Stop parsing in `initHeaders` and `readAggregatedSkims` in any case
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2684)
> CsvSkimReader: Minor improvements

- src/main/java/beam/analysis/physsim/PhyssimSpeedHandler.java
Using compute instead of getOrDefault in order to store values to the map
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2692)
> Fixed not storing physsim speed statistic

- src/main/java/beam/analysis/physsim/PhyssimCalcLinkStats.java
- src/main/java/beam/matsim/MatsimConfigUpdater.java
- src/main/java/beam/physsim/jdeqsim/AgentSimToPhysSimPlanConverter.java
- src/main/java/beam/physsim/jdeqsim/cacc/roadCapacityAdjustmentFunctions/Hao2018CaccRoadCapacityAdjustmentFunction.java
- src/main/scala/beam/scoring/BeamScoringFunctionFactory.scala
- src/main/scala/beam/sim/BeamConfigChangesObservable.scala
- src/main/scala/beam/sim/BeamConfigChangesObserver.scala
- src/main/scala/beam/sim/config/BeamConfigHolder.scala
There used to be memory leaks because PhyssimCalcLinkStats is recreated every iteration and resubscribed for BeamConfig changes through BeamConfigChangesObservable.
The BeamConfigChangesObservable have had a link to all subscribers together with all old instances of PhyssimCalcLinkStats.
Now BeamConfigChangesObservable using a WeakReference to store all subscribers. This should solve the problem not only for now but for future uses too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2698)
> Memory leak fix

- .lfsconfig
- src/main/python/nhts_analysis/generate-city-data-from-NHTS.py
allows for a python script to be called with an argument determining which NHTS urban areas to include in producing work end time / duration distribution and activity end times and intercepts.
The first argument defines the urban areas and can take several formats:
String: (e.g. '12420') just gives the distribution for the urban area defined by the FIPS code in the string
List of strings: (e.g. '[12420,12060]') returns a single distribution averaged across all regions, weighted by sample size
Dict: (e.g.  '{12420:0.25,12060:0.25,-1:0.5}'), returns a single distribution weighted by the dictionary values. 
In all cases, a negative input defaults averaging across all CBSAs
The second argument is the path to the output.
Still needs a way of handling the NHTS input data. Right now it's just …
> new script to automatically generate nhts inputs

- src/main/scala/beam/sim/BeamHelper.scala
- src/main/scala/beam/sim/config/ConfigModule.scala
BeamConfig is modified by BeamWarmStart class. This PR injects this modified config into Guice instead of the original one so that we have a single config in the system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2812)
> Fixed using wrong beam config in the warm start related classes

- build.gradle
Resolves #2781 
This will NOT pass CI because we are removing the old name. I thought about aliasing it, but then you have the same problem as brought up in #2781 - so I think it'll be better to temporarily break branches until they merge this change. It's such a minor one anyway that it could be done manually if needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2861)
> change name to mitigate confusion of plugin

- src/main/scala/beam/replanning/SupplementaryTripGenerator.scala
to fix a fatal exception:
```
09:05:47.099 [main] INFO  beam.sim.BeamMobsim - Filling in secondary trips in plans
09:09:34.884 [main] ERROR o.m.c.controler.AbstractController - Mobsim did not complete normally! afterMobsimListeners will be called anyway.
java.util.NoSuchElementException: None.get
at scala.None$.get(Option.scala:529)
at scala.None$.get(Option.scala:527)
at beam.replanning.SupplementaryTripGenerator.generateSubtour(SupplementaryTripGenerator.scala:163)
at beam.replanning.SupplementaryTripGenerator.$anonfun$generateNewPlans$1(SupplementaryTripGenerator.scala:82)
at beam.replanning.SupplementaryTripGenerator.$anonfun$generateNewPlans$1$adapted(SupplementaryTripGenerator.scala:78)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> BugFix: a fix for java.util.NoSuchElementException: None.get

- src/main/scala/beam/agentsim/agents/modalbehaviors/ChoosesMode.scala
- src/test/scala/beam/agentsim/agents/PersonWithVehicleSharingSpec.scala
Seems to work in SF-light-1k. Before the fix, if we run a scenario with very limited parking we get 3727 car mode choices. With the fix, we now get 2160 car mode choices, implying that considering walk egress time makes the car mode less attractive. As reference, unlimited parking gives 4796 car mode choices, implying that before the fix some people were still being driven away from choosing the car mode because of the cost associated with the scarce parking (which checks out with expectations).
Should fix #2870
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2874)
> add duration to walk egress leg after parking in mode choice

- src/main/scala/beam/replanning/AddSupplementaryTrips.scala
- src/main/scala/beam/replanning/SupplementaryTripGenerator.scala
Previously non-workers were limited to one secondary tour per day (it was one tour per mandatory activity). Added a fix allowing up to three secondary tours for non-workers. Could be generalized in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2915)
> multiple secondary activities from home

- build.gradle
[Scala 2.12.12](https://github.com/scala/scala/releases/tag/v2.12.12) is being for a while, let's move to it!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2944)
> Project: Update to Scala 2.12.12

- src/main/scala/beam/utils/csv/readers/BeamCsvScenarioReader.scala
- src/main/scala/beam/utils/csv/writers/BeamCsvScenarioWriter.scala
- src/main/scala/beam/utils/csv/writers/HouseholdsCsvWriter.scala
- src/main/scala/beam/utils/csv/writers/NetworkCsvWriter.scala
- src/main/scala/beam/utils/csv/writers/PlansCsvWriter.scala
- src/main/scala/beam/utils/csv/writers/PopulationCsvWriter.scala
- src/main/scala/beam/utils/csv/writers/ScenarioCsvWriter.scala
- src/main/scala/beam/utils/csv/writers/VehiclesCsvWriter.scala
- src/main/scala/beam/utils/data/synthpop/PumaLevelScenarioGenerator.scala
- src/main/scala/beam/utils/data/synthpop/ScenarioGenerator.scala
- src/main/scala/beam/utils/plan/sampling/AvailableModeUtils.scala
- src/main/scala/beam/utils/scenario/Models.scala
- src/main/scala/beam/utils/scenario/generic/readers/PersonInfoReader.scala
- src/main/scala/beam/utils/scenario/urbansim/UrbanSimScenarioSource.scala
- src/main/scala/beam/utils/scenario/urbansim/censusblock/merger/PersonMerger.scala
- src/test/scala/beam/utils/scenario/UrbanSimScenarioLoaderTest.scala
Resolves #2894 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2961)
Example of usage below:
```Scala
// Implicits supports conversion from Iterable and also Array
import beam.utils.csv.readers.BeamCsvScenarioReader
import beam.utils.csv.writers.BeamCsvScenarioWriter._
val vehicles: Iterable[VehicleInfo] =
BeamCsvScenarioReader.readVehiclesFile("vehicles.csv")
vehicles.writeCsvVehiclesFile("vehicles_output.csv")
val households: Array[HouseholdInfo] =
BeamCsvScenarioReader.readHouseholdsFile("householdsFile.csv", vehicles)
vehicles.writeCsvVehiclesFile("households_output.csv")
val persons: Array[PersonInfo] =
BeamCsvScenarioReader.readPersonsFile("persons.csv") …
```
> BeamCsvScenarioWriter compatible with ScenarioInfo classes

- src/main/scala/beam/router/skim/ODSkimmer.scala
- `generalizedTime` was written twice (the second time it should have been `generalizedCost`), fixed it. Now we write `generalizedCost`
- Fix the order of columns `count` and `energy`
- Added the value for `iterations` column
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2984)
> Bug: ODSkimmer writes full skim with incorrect order of columns

- src/main/scala/beam/agentsim/infrastructure/ParkingStall.scala
- src/main/scala/beam/agentsim/infrastructure/ZonalParkingManager.scala
We're seeing the problem in NYC of really long walk trips, potentially to some extent caused by cars being initialized in emergency parking stalls really far away from home (so a really long walk trip still is favorable compared to a really long walk access trip to a car). We should assume that all cars have somewhere reasonably close by their household location to park.
First pass solution is to create a new version of an emergency parking stall that can only be created on vehicle initialization and for "home" activities. The new default residential stall is located at the request location and free, so no access time and cost. These stalls only are created when all other nearby spots are filled up, so hopefully it shouldn't artificially get rid of all parking scarcity.
Should fix #2882 …
> generate free residential stall when needed

- src/main/scala/beam/agentsim/agents/ridehail/RideHailMatching.scala
Optimized version increased AVG CPU utilization from 28.8% to 36% by removing thread contention. As a result of increased CPU utilization the total AgentSim time is reduced from 31908 seconds (08h:51m:48s) to 26156 seconds (07h:15m:56s), around 21% of improvement.
- Before optimization: https://s3.us-east-2.amazonaws.com/beam-outputs/index.html#output/austin/austin-prod-full-after-opt-commits__2020-10-12_18-02-42_ebp/
- After optimization: https://s3.us-east-2.amazonaws.com/beam-outputs/index.html#output/austin/austin-prod-full-thread-local-geo-calc__2020-10-13_16-22-14_hud/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3043)
> RideHailMatching: Per thread GeodeticCalculator

- src/main/scala/beam/agentsim/infrastructure/ChargingNetworkManager.scala
- src/main/scala/beam/router/skim/core/AbstractSkimmer.scala
- src/main/scala/beam/router/skim/core/DriveTimeSkimmer.scala
- src/main/scala/beam/router/skim/core/ODSkimmer.scala
- src/main/scala/beam/router/skim/readonly/TAZSkims.scala
Latest production run on smart-baseline scenario with twice lower population has bad performance for 0-th iteration. Decided to add some logs  and collect stats from profiler. Here what I saw:
```
15:54:50.193 [ClusterSystem-akka.actor.default-dispatcher-90] INFO  b.a.scheduler.BeamAgentScheduler - Hour 59.5 completed. 73.3(GB)
15:55:02.950 [ClusterSystem-akka.actor.default-dispatcher-100] INFO  b.a.i.ChargingNetworkManager - timeSpentToPlanEnergyDispatchTrigger: 2624753 ms, nHandledPlanEnergyDispatchTrigger: 717, AVG: 3660.7433751743374
15:55:15.516 [ClusterSystem-akka.actor.default-dispatcher-65] INFO  b.a.scheduler.BeamAgentScheduler - Hour 60.0 completed. 91.3(GB)
15:55:15.517 [ClusterSystem-akka.actor.default-dispatcher-17] INFO  b.a.scheduler.BeamAgentScheduler - Stopping …
```
> Optimize abstract skimmer

- build.gradle
Explicitly create /app/output for NERSC environment. Without this change when I try to run Beam in Docker in NERSC I get the following error:
```
abalaian@cori02:~> shifter -V /global/cscratch1/sd/abalaian/beam/output:/app/output --image=beammodel/beam:0.8.6 /app/entrypoint.sh --config /app/test/input/beamville/beam.conf
FAILED to create volume "to": /var/udiMount//app/output, cannot create mount points in that location
FAILED to setup user-requested mounts.
FAILED to setup image.
```
After [applying this change](https://hub.docker.com/layers/beammodel/beam/0.8.6.4-nersc/images/sha256-e6b8736d98b467d6cac527770696155cf6f16abc2f42d084210bc928b2e2a8fc?context=repo) it can successfully run it in NERSC:
```
abalaian@cori02:~> shifterimg pull beammodel/beam:0.8.6.4-nersc
2021-03-24T05:54:42 …
```
> Docker: NERSC friendly

- src/test/scala/beam/router/PhyssymXmlToOsmConverter.scala
Closes #3153 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3159)
Changes:
- Fix bug: currently the Physym to OSM repeats the wayId. In the new version a unique wayId is extracted from linkId of Physsim network
- Allow to convert Physym network to PBF (in addition to OSM XML) 
- Small refactoring to improve log
> Added option to convert Physsim network to pbf directly

- docs/users.rst
in the getting started guide -- 0.7.0 is really obsolete now
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3269)
> tell people to use develop branch
